// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module Canny_Filter_Hysteresis_Filter (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        Suppression_to_Hysteresis_dout,
        Suppression_to_Hysteresis_empty_n,
        Suppression_to_Hysteresis_read,
        Suppression_to_Hysteresis_num_data_valid,
        Suppression_to_Hysteresis_fifo_cap,
        Output_Stream_TDATA,
        Output_Stream_TVALID,
        Output_Stream_TREADY,
        Output_Stream_TKEEP,
        Output_Stream_TSTRB,
        Output_Stream_TUSER,
        Output_Stream_TLAST,
        Output_Stream_TID,
        Output_Stream_TDEST,
        Rows_dout,
        Rows_empty_n,
        Rows_read,
        Rows_num_data_valid,
        Rows_fifo_cap,
        Cols_dout,
        Cols_empty_n,
        Cols_read,
        Cols_num_data_valid,
        Cols_fifo_cap,
        High_Threshold_dout,
        High_Threshold_empty_n,
        High_Threshold_read,
        High_Threshold_num_data_valid,
        High_Threshold_fifo_cap,
        Low_Threshold_dout,
        Low_Threshold_empty_n,
        Low_Threshold_read,
        Low_Threshold_num_data_valid,
        Low_Threshold_fifo_cap
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] Suppression_to_Hysteresis_dout;
input   Suppression_to_Hysteresis_empty_n;
output   Suppression_to_Hysteresis_read;
input  [3:0] Suppression_to_Hysteresis_num_data_valid;
input  [3:0] Suppression_to_Hysteresis_fifo_cap;
output  [31:0] Output_Stream_TDATA;
output   Output_Stream_TVALID;
input   Output_Stream_TREADY;
output  [3:0] Output_Stream_TKEEP;
output  [3:0] Output_Stream_TSTRB;
output  [2:0] Output_Stream_TUSER;
output  [0:0] Output_Stream_TLAST;
output  [4:0] Output_Stream_TID;
output  [5:0] Output_Stream_TDEST;
input  [31:0] Rows_dout;
input   Rows_empty_n;
output   Rows_read;
input  [2:0] Rows_num_data_valid;
input  [2:0] Rows_fifo_cap;
input  [31:0] Cols_dout;
input   Cols_empty_n;
output   Cols_read;
input  [2:0] Cols_num_data_valid;
input  [2:0] Cols_fifo_cap;
input  [31:0] High_Threshold_dout;
input   High_Threshold_empty_n;
output   High_Threshold_read;
input  [3:0] High_Threshold_num_data_valid;
input  [3:0] High_Threshold_fifo_cap;
input  [31:0] Low_Threshold_dout;
input   Low_Threshold_empty_n;
output   Low_Threshold_read;
input  [3:0] Low_Threshold_num_data_valid;
input  [3:0] Low_Threshold_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Rows_read;
reg Cols_read;
reg High_Threshold_read;
reg Low_Threshold_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Rows_blk_n;
reg    Cols_blk_n;
reg    High_Threshold_blk_n;
reg    Low_Threshold_blk_n;
reg   [31:0] Low_Threshold_1_reg_171;
reg    ap_block_state1;
reg   [31:0] High_Threshold_1_reg_176;
reg   [31:0] Cols_3_reg_181;
reg   [31:0] Rows_3_reg_187;
wire   [30:0] smax_fu_129_p3;
reg   [30:0] smax_reg_192;
wire   [30:0] smax1_fu_143_p3;
reg   [30:0] smax1_reg_197;
wire    ap_CS_fsm_state2;
wire   [31:0] add_ln70_fu_159_p2;
reg   [31:0] add_ln70_reg_212;
wire    ap_CS_fsm_state3;
wire   [31:0] add_ln70_1_fu_165_p2;
reg   [31:0] add_ln70_1_reg_217;
wire   [61:0] grp_fu_110_p2;
reg   [61:0] bound_reg_222;
wire    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start;
wire    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_done;
wire    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_idle;
wire    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_ready;
wire    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Suppression_to_Hysteresis_read;
wire    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TREADY;
wire   [31:0] grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDATA;
wire    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID;
wire   [3:0] grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TKEEP;
wire   [3:0] grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TSTRB;
wire   [2:0] grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TUSER;
wire   [0:0] grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TLAST;
wire   [4:0] grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TID;
wire   [5:0] grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDEST;
reg    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [31:0] Output_Stream_TDATA_reg;
reg   [3:0] Output_Stream_TKEEP_reg;
reg   [3:0] Output_Stream_TSTRB_reg;
reg   [2:0] Output_Stream_TUSER_reg;
reg   [0:0] Output_Stream_TLAST_reg;
reg   [4:0] Output_Stream_TID_reg;
reg   [5:0] Output_Stream_TDEST_reg;
wire   [30:0] grp_fu_110_p0;
wire   [30:0] grp_fu_110_p1;
wire   [0:0] empty_71_fu_123_p2;
wire   [30:0] empty_fu_115_p1;
wire   [0:0] empty_72_fu_137_p2;
wire   [30:0] empty_70_fu_119_p1;
wire    ap_CS_fsm_state5;
wire    regslice_both_Output_Stream_V_data_V_U_apdone_blk;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg   [31:0] Output_Stream_TDATA_int_regslice;
wire    Output_Stream_TVALID_int_regslice;
wire    Output_Stream_TREADY_int_regslice;
wire    regslice_both_Output_Stream_V_data_V_U_vld_out;
wire    regslice_both_Output_Stream_V_keep_V_U_apdone_blk;
reg   [3:0] Output_Stream_TKEEP_int_regslice;
wire    regslice_both_Output_Stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_Output_Stream_V_keep_V_U_vld_out;
wire    regslice_both_Output_Stream_V_strb_V_U_apdone_blk;
reg   [3:0] Output_Stream_TSTRB_int_regslice;
wire    regslice_both_Output_Stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_Output_Stream_V_strb_V_U_vld_out;
wire    regslice_both_Output_Stream_V_user_V_U_apdone_blk;
reg   [2:0] Output_Stream_TUSER_int_regslice;
wire    regslice_both_Output_Stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_Output_Stream_V_user_V_U_vld_out;
wire    regslice_both_Output_Stream_V_last_V_U_apdone_blk;
reg   [0:0] Output_Stream_TLAST_int_regslice;
wire    regslice_both_Output_Stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_Output_Stream_V_last_V_U_vld_out;
wire    regslice_both_Output_Stream_V_id_V_U_apdone_blk;
reg   [4:0] Output_Stream_TID_int_regslice;
wire    regslice_both_Output_Stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_Output_Stream_V_id_V_U_vld_out;
wire    regslice_both_Output_Stream_V_dest_V_U_apdone_blk;
reg   [5:0] Output_Stream_TDEST_int_regslice;
wire    regslice_both_Output_Stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_Output_Stream_V_dest_V_U_vld_out;
wire   [61:0] grp_fu_110_p00;
wire   [61:0] grp_fu_110_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg = 1'b0;
end

Canny_Filter_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2 grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start),
    .ap_done(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_done),
    .ap_idle(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_idle),
    .ap_ready(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_ready),
    .Suppression_to_Hysteresis_dout(Suppression_to_Hysteresis_dout),
    .Suppression_to_Hysteresis_empty_n(Suppression_to_Hysteresis_empty_n),
    .Suppression_to_Hysteresis_read(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Suppression_to_Hysteresis_read),
    .Suppression_to_Hysteresis_num_data_valid(4'd0),
    .Suppression_to_Hysteresis_fifo_cap(4'd0),
    .Output_Stream_TREADY(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TREADY),
    .Cols_3(Cols_3_reg_181),
    .add_ln70(add_ln70_reg_212),
    .High_Threshold_1(High_Threshold_1_reg_176),
    .Low_Threshold_1(Low_Threshold_1_reg_171),
    .add_ln70_1(add_ln70_1_reg_217),
    .Output_Stream_TDATA(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDATA),
    .Output_Stream_TVALID(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID),
    .Output_Stream_TKEEP(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TKEEP),
    .Output_Stream_TSTRB(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TSTRB),
    .Output_Stream_TUSER(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TUSER),
    .Output_Stream_TLAST(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TLAST),
    .Output_Stream_TID(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TID),
    .Output_Stream_TDEST(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDEST),
    .bound(bound_reg_222)
);

Canny_Filter_mul_31ns_31ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31ns_31ns_62_2_1_U80(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_110_p0),
    .din1(grp_fu_110_p1),
    .ce(1'b1),
    .dout(grp_fu_110_p2)
);

Canny_Filter_regslice_both #(
    .DataWidth( 32 ))
regslice_both_Output_Stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Output_Stream_TDATA_int_regslice),
    .vld_in(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID),
    .ack_in(Output_Stream_TREADY_int_regslice),
    .data_out(Output_Stream_TDATA),
    .vld_out(regslice_both_Output_Stream_V_data_V_U_vld_out),
    .ack_out(Output_Stream_TREADY),
    .apdone_blk(regslice_both_Output_Stream_V_data_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_Output_Stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Output_Stream_TKEEP_int_regslice),
    .vld_in(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID),
    .ack_in(regslice_both_Output_Stream_V_keep_V_U_ack_in_dummy),
    .data_out(Output_Stream_TKEEP),
    .vld_out(regslice_both_Output_Stream_V_keep_V_U_vld_out),
    .ack_out(Output_Stream_TREADY),
    .apdone_blk(regslice_both_Output_Stream_V_keep_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_Output_Stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Output_Stream_TSTRB_int_regslice),
    .vld_in(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID),
    .ack_in(regslice_both_Output_Stream_V_strb_V_U_ack_in_dummy),
    .data_out(Output_Stream_TSTRB),
    .vld_out(regslice_both_Output_Stream_V_strb_V_U_vld_out),
    .ack_out(Output_Stream_TREADY),
    .apdone_blk(regslice_both_Output_Stream_V_strb_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 3 ))
regslice_both_Output_Stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Output_Stream_TUSER_int_regslice),
    .vld_in(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID),
    .ack_in(regslice_both_Output_Stream_V_user_V_U_ack_in_dummy),
    .data_out(Output_Stream_TUSER),
    .vld_out(regslice_both_Output_Stream_V_user_V_U_vld_out),
    .ack_out(Output_Stream_TREADY),
    .apdone_blk(regslice_both_Output_Stream_V_user_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_Output_Stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Output_Stream_TLAST_int_regslice),
    .vld_in(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID),
    .ack_in(regslice_both_Output_Stream_V_last_V_U_ack_in_dummy),
    .data_out(Output_Stream_TLAST),
    .vld_out(regslice_both_Output_Stream_V_last_V_U_vld_out),
    .ack_out(Output_Stream_TREADY),
    .apdone_blk(regslice_both_Output_Stream_V_last_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 5 ))
regslice_both_Output_Stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Output_Stream_TID_int_regslice),
    .vld_in(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID),
    .ack_in(regslice_both_Output_Stream_V_id_V_U_ack_in_dummy),
    .data_out(Output_Stream_TID),
    .vld_out(regslice_both_Output_Stream_V_id_V_U_vld_out),
    .ack_out(Output_Stream_TREADY),
    .apdone_blk(regslice_both_Output_Stream_V_id_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 6 ))
regslice_both_Output_Stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Output_Stream_TDEST_int_regslice),
    .vld_in(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID),
    .ack_in(regslice_both_Output_Stream_V_dest_V_U_ack_in_dummy),
    .data_out(Output_Stream_TDEST),
    .vld_out(regslice_both_Output_Stream_V_dest_V_U_vld_out),
    .ack_out(Output_Stream_TREADY),
    .apdone_blk(regslice_both_Output_Stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((regslice_both_Output_Stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_ready == 1'b1)) begin
            grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        Cols_3_reg_181 <= Cols_dout;
        High_Threshold_1_reg_176 <= High_Threshold_dout;
        Low_Threshold_1_reg_171 <= Low_Threshold_dout;
        Rows_3_reg_187 <= Rows_dout;
        smax1_reg_197 <= smax1_fu_143_p3;
        smax_reg_192 <= smax_fu_129_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID == 1'b1))) begin
        Output_Stream_TDATA_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDATA;
        Output_Stream_TDEST_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDEST;
        Output_Stream_TID_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TID;
        Output_Stream_TKEEP_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TKEEP;
        Output_Stream_TLAST_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TLAST;
        Output_Stream_TSTRB_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TSTRB;
        Output_Stream_TUSER_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln70_1_reg_217 <= add_ln70_1_fu_165_p2;
        add_ln70_reg_212 <= add_ln70_fu_159_p2;
        bound_reg_222 <= grp_fu_110_p2;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Cols_blk_n = Cols_empty_n;
    end else begin
        Cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        Cols_read = 1'b1;
    end else begin
        Cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        High_Threshold_blk_n = High_Threshold_empty_n;
    end else begin
        High_Threshold_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        High_Threshold_read = 1'b1;
    end else begin
        High_Threshold_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Low_Threshold_blk_n = Low_Threshold_empty_n;
    end else begin
        Low_Threshold_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        Low_Threshold_read = 1'b1;
    end else begin
        Low_Threshold_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID == 1'b1))) begin
        Output_Stream_TDATA_int_regslice = grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDATA;
    end else begin
        Output_Stream_TDATA_int_regslice = Output_Stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID == 1'b1))) begin
        Output_Stream_TDEST_int_regslice = grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDEST;
    end else begin
        Output_Stream_TDEST_int_regslice = Output_Stream_TDEST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID == 1'b1))) begin
        Output_Stream_TID_int_regslice = grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TID;
    end else begin
        Output_Stream_TID_int_regslice = Output_Stream_TID_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID == 1'b1))) begin
        Output_Stream_TKEEP_int_regslice = grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TKEEP;
    end else begin
        Output_Stream_TKEEP_int_regslice = Output_Stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID == 1'b1))) begin
        Output_Stream_TLAST_int_regslice = grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TLAST;
    end else begin
        Output_Stream_TLAST_int_regslice = Output_Stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID == 1'b1))) begin
        Output_Stream_TSTRB_int_regslice = grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TSTRB;
    end else begin
        Output_Stream_TSTRB_int_regslice = Output_Stream_TSTRB_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID == 1'b1))) begin
        Output_Stream_TUSER_int_regslice = grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TUSER;
    end else begin
        Output_Stream_TUSER_int_regslice = Output_Stream_TUSER_reg;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Rows_blk_n = Rows_empty_n;
    end else begin
        Rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        Rows_read = 1'b1;
    end else begin
        Rows_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_Output_Stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_Output_Stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_Output_Stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((regslice_both_Output_Stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Output_Stream_TVALID = regslice_both_Output_Stream_V_data_V_U_vld_out;

assign Output_Stream_TVALID_int_regslice = grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID;

assign Suppression_to_Hysteresis_read = grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Suppression_to_Hysteresis_read;

assign add_ln70_1_fu_165_p2 = ($signed(Cols_3_reg_181) + $signed(32'd4294967295));

assign add_ln70_fu_159_p2 = ($signed(Rows_3_reg_187) + $signed(32'd4294967295));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((1'b0 == Low_Threshold_empty_n) | (1'b0 == High_Threshold_empty_n) | (1'b0 == Cols_empty_n) | (1'b0 == Rows_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign empty_70_fu_119_p1 = Rows_dout[30:0];

assign empty_71_fu_123_p2 = (($signed(Cols_dout) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_72_fu_137_p2 = (($signed(Rows_dout) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_fu_115_p1 = Cols_dout[30:0];

assign grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TREADY = (ap_CS_fsm_state4 & Output_Stream_TREADY_int_regslice);

assign grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start = grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg;

assign grp_fu_110_p0 = grp_fu_110_p00;

assign grp_fu_110_p00 = smax1_reg_197;

assign grp_fu_110_p1 = grp_fu_110_p10;

assign grp_fu_110_p10 = smax_reg_192;

assign smax1_fu_143_p3 = ((empty_72_fu_137_p2[0:0] == 1'b1) ? empty_70_fu_119_p1 : 31'd0);

assign smax_fu_129_p3 = ((empty_71_fu_123_p2[0:0] == 1'b1) ? empty_fu_115_p1 : 31'd0);

endmodule //Canny_Filter_Hysteresis_Filter
