// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Canny_Filter_Canny_Filter,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.395562,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=27,HLS_SYN_DSP=0,HLS_SYN_FF=5899,HLS_SYN_LUT=6721,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module Canny_Filter (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        Input_Stream_TDATA,
        Input_Stream_TKEEP,
        Input_Stream_TSTRB,
        Input_Stream_TUSER,
        Input_Stream_TLAST,
        Input_Stream_TID,
        Input_Stream_TDEST,
        Output_Stream_TDATA,
        Output_Stream_TKEEP,
        Output_Stream_TSTRB,
        Output_Stream_TUSER,
        Output_Stream_TLAST,
        Output_Stream_TID,
        Output_Stream_TDEST,
        Input_Stream_TVALID,
        Input_Stream_TREADY,
        Output_Stream_TVALID,
        Output_Stream_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [31:0] Input_Stream_TDATA;
input  [3:0] Input_Stream_TKEEP;
input  [3:0] Input_Stream_TSTRB;
input  [2:0] Input_Stream_TUSER;
input  [0:0] Input_Stream_TLAST;
input  [4:0] Input_Stream_TID;
input  [5:0] Input_Stream_TDEST;
output  [31:0] Output_Stream_TDATA;
output  [3:0] Output_Stream_TKEEP;
output  [3:0] Output_Stream_TSTRB;
output  [2:0] Output_Stream_TUSER;
output  [0:0] Output_Stream_TLAST;
output  [4:0] Output_Stream_TID;
output  [5:0] Output_Stream_TDEST;
input   Input_Stream_TVALID;
output   Input_Stream_TREADY;
output   Output_Stream_TVALID;
input   Output_Stream_TREADY;

 reg    ap_rst_n_inv;
wire   [31:0] Rows;
wire   [31:0] Cols;
wire   [31:0] High_Threshold;
wire   [31:0] Low_Threshold;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [31:0] entry_proc_U0_High_Threshold_c_din;
wire    entry_proc_U0_High_Threshold_c_write;
wire   [31:0] entry_proc_U0_Low_Threshold_c_din;
wire    entry_proc_U0_Low_Threshold_c_write;
wire    Gaussian_Filter_U0_ap_start;
wire    Gaussian_Filter_U0_ap_done;
wire    Gaussian_Filter_U0_ap_continue;
wire    Gaussian_Filter_U0_ap_idle;
wire    Gaussian_Filter_U0_ap_ready;
wire    Gaussian_Filter_U0_start_out;
wire    Gaussian_Filter_U0_start_write;
wire    Gaussian_Filter_U0_Input_Stream_TREADY;
wire   [31:0] Gaussian_Filter_U0_Gaussian_to_Sobel_din;
wire    Gaussian_Filter_U0_Gaussian_to_Sobel_write;
wire   [31:0] Gaussian_Filter_U0_Rows_c2_din;
wire    Gaussian_Filter_U0_Rows_c2_write;
wire   [31:0] Gaussian_Filter_U0_Cols_c4_din;
wire    Gaussian_Filter_U0_Cols_c4_write;
wire    Sobel_Filter_U0_ap_start;
wire    Sobel_Filter_U0_ap_done;
wire    Sobel_Filter_U0_ap_continue;
wire    Sobel_Filter_U0_ap_idle;
wire    Sobel_Filter_U0_ap_ready;
wire    Sobel_Filter_U0_start_out;
wire    Sobel_Filter_U0_start_write;
wire    Sobel_Filter_U0_Gaussian_to_Sobel_read;
wire   [31:0] Sobel_Filter_U0_Sobel_to_Suppression_din;
wire    Sobel_Filter_U0_Sobel_to_Suppression_write;
wire    Sobel_Filter_U0_Rows_read;
wire    Sobel_Filter_U0_Cols_read;
wire   [31:0] Sobel_Filter_U0_Rows_c1_din;
wire    Sobel_Filter_U0_Rows_c1_write;
wire   [31:0] Sobel_Filter_U0_Cols_c3_din;
wire    Sobel_Filter_U0_Cols_c3_write;
wire    Suppression_Filter_U0_ap_start;
wire    Suppression_Filter_U0_ap_done;
wire    Suppression_Filter_U0_ap_continue;
wire    Suppression_Filter_U0_ap_idle;
wire    Suppression_Filter_U0_ap_ready;
wire    Suppression_Filter_U0_Sobel_to_Suppression_read;
wire   [31:0] Suppression_Filter_U0_Suppression_to_Hysteresis_din;
wire    Suppression_Filter_U0_Suppression_to_Hysteresis_write;
wire    Suppression_Filter_U0_Rows_read;
wire    Suppression_Filter_U0_Cols_read;
wire   [31:0] Suppression_Filter_U0_Rows_c_din;
wire    Suppression_Filter_U0_Rows_c_write;
wire   [31:0] Suppression_Filter_U0_Cols_c_din;
wire    Suppression_Filter_U0_Cols_c_write;
wire    Hysteresis_Filter_U0_ap_start;
wire    Hysteresis_Filter_U0_ap_done;
wire    Hysteresis_Filter_U0_ap_continue;
wire    Hysteresis_Filter_U0_ap_idle;
wire    Hysteresis_Filter_U0_ap_ready;
wire    Hysteresis_Filter_U0_Suppression_to_Hysteresis_read;
wire   [31:0] Hysteresis_Filter_U0_Output_Stream_TDATA;
wire    Hysteresis_Filter_U0_Output_Stream_TVALID;
wire   [3:0] Hysteresis_Filter_U0_Output_Stream_TKEEP;
wire   [3:0] Hysteresis_Filter_U0_Output_Stream_TSTRB;
wire   [2:0] Hysteresis_Filter_U0_Output_Stream_TUSER;
wire   [0:0] Hysteresis_Filter_U0_Output_Stream_TLAST;
wire   [4:0] Hysteresis_Filter_U0_Output_Stream_TID;
wire   [5:0] Hysteresis_Filter_U0_Output_Stream_TDEST;
wire    Hysteresis_Filter_U0_Rows_read;
wire    Hysteresis_Filter_U0_Cols_read;
wire    Hysteresis_Filter_U0_High_Threshold_read;
wire    Hysteresis_Filter_U0_Low_Threshold_read;
wire    High_Threshold_c_full_n;
wire   [31:0] High_Threshold_c_dout;
wire    High_Threshold_c_empty_n;
wire   [3:0] High_Threshold_c_num_data_valid;
wire   [3:0] High_Threshold_c_fifo_cap;
wire    Low_Threshold_c_full_n;
wire   [31:0] Low_Threshold_c_dout;
wire    Low_Threshold_c_empty_n;
wire   [3:0] Low_Threshold_c_num_data_valid;
wire   [3:0] Low_Threshold_c_fifo_cap;
wire    Gaussian_to_Sobel_full_n;
wire   [31:0] Gaussian_to_Sobel_dout;
wire    Gaussian_to_Sobel_empty_n;
wire   [3:0] Gaussian_to_Sobel_num_data_valid;
wire   [3:0] Gaussian_to_Sobel_fifo_cap;
wire    Rows_c2_full_n;
wire   [31:0] Rows_c2_dout;
wire    Rows_c2_empty_n;
wire   [2:0] Rows_c2_num_data_valid;
wire   [2:0] Rows_c2_fifo_cap;
wire    Cols_c4_full_n;
wire   [31:0] Cols_c4_dout;
wire    Cols_c4_empty_n;
wire   [2:0] Cols_c4_num_data_valid;
wire   [2:0] Cols_c4_fifo_cap;
wire    Sobel_to_Suppression_full_n;
wire   [31:0] Sobel_to_Suppression_dout;
wire    Sobel_to_Suppression_empty_n;
wire   [3:0] Sobel_to_Suppression_num_data_valid;
wire   [3:0] Sobel_to_Suppression_fifo_cap;
wire    Rows_c1_full_n;
wire   [31:0] Rows_c1_dout;
wire    Rows_c1_empty_n;
wire   [2:0] Rows_c1_num_data_valid;
wire   [2:0] Rows_c1_fifo_cap;
wire    Cols_c3_full_n;
wire   [31:0] Cols_c3_dout;
wire    Cols_c3_empty_n;
wire   [2:0] Cols_c3_num_data_valid;
wire   [2:0] Cols_c3_fifo_cap;
wire    Suppression_to_Hysteresis_full_n;
wire   [31:0] Suppression_to_Hysteresis_dout;
wire    Suppression_to_Hysteresis_empty_n;
wire   [3:0] Suppression_to_Hysteresis_num_data_valid;
wire   [3:0] Suppression_to_Hysteresis_fifo_cap;
wire    Rows_c_full_n;
wire   [31:0] Rows_c_dout;
wire    Rows_c_empty_n;
wire   [2:0] Rows_c_num_data_valid;
wire   [2:0] Rows_c_fifo_cap;
wire    Cols_c_full_n;
wire   [31:0] Cols_c_dout;
wire    Cols_c_empty_n;
wire   [2:0] Cols_c_num_data_valid;
wire   [2:0] Cols_c_fifo_cap;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_Gaussian_Filter_U0_ap_ready;
wire    ap_sync_Gaussian_Filter_U0_ap_ready;
wire   [0:0] start_for_Hysteresis_Filter_U0_din;
wire    start_for_Hysteresis_Filter_U0_full_n;
wire   [0:0] start_for_Hysteresis_Filter_U0_dout;
wire    start_for_Hysteresis_Filter_U0_empty_n;
wire   [0:0] start_for_Sobel_Filter_U0_din;
wire    start_for_Sobel_Filter_U0_full_n;
wire   [0:0] start_for_Sobel_Filter_U0_dout;
wire    start_for_Sobel_Filter_U0_empty_n;
wire   [0:0] start_for_Suppression_Filter_U0_din;
wire    start_for_Suppression_Filter_U0_full_n;
wire   [0:0] start_for_Suppression_Filter_U0_dout;
wire    start_for_Suppression_Filter_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Gaussian_Filter_U0_ap_ready = 1'b0;
end

Canny_Filter_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .Rows(Rows),
    .Cols(Cols),
    .High_Threshold(High_Threshold),
    .Low_Threshold(Low_Threshold),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

Canny_Filter_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_Hysteresis_Filter_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .High_Threshold(High_Threshold),
    .High_Threshold_c_din(entry_proc_U0_High_Threshold_c_din),
    .High_Threshold_c_full_n(High_Threshold_c_full_n),
    .High_Threshold_c_write(entry_proc_U0_High_Threshold_c_write),
    .High_Threshold_c_num_data_valid(High_Threshold_c_num_data_valid),
    .High_Threshold_c_fifo_cap(High_Threshold_c_fifo_cap),
    .Low_Threshold(Low_Threshold),
    .Low_Threshold_c_din(entry_proc_U0_Low_Threshold_c_din),
    .Low_Threshold_c_full_n(Low_Threshold_c_full_n),
    .Low_Threshold_c_write(entry_proc_U0_Low_Threshold_c_write),
    .Low_Threshold_c_num_data_valid(Low_Threshold_c_num_data_valid),
    .Low_Threshold_c_fifo_cap(Low_Threshold_c_fifo_cap)
);

Canny_Filter_Gaussian_Filter Gaussian_Filter_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Gaussian_Filter_U0_ap_start),
    .start_full_n(start_for_Sobel_Filter_U0_full_n),
    .ap_done(Gaussian_Filter_U0_ap_done),
    .ap_continue(Gaussian_Filter_U0_ap_continue),
    .ap_idle(Gaussian_Filter_U0_ap_idle),
    .ap_ready(Gaussian_Filter_U0_ap_ready),
    .start_out(Gaussian_Filter_U0_start_out),
    .start_write(Gaussian_Filter_U0_start_write),
    .Input_Stream_TDATA(Input_Stream_TDATA),
    .Input_Stream_TVALID(Input_Stream_TVALID),
    .Input_Stream_TREADY(Gaussian_Filter_U0_Input_Stream_TREADY),
    .Input_Stream_TKEEP(Input_Stream_TKEEP),
    .Input_Stream_TSTRB(Input_Stream_TSTRB),
    .Input_Stream_TUSER(Input_Stream_TUSER),
    .Input_Stream_TLAST(Input_Stream_TLAST),
    .Input_Stream_TID(Input_Stream_TID),
    .Input_Stream_TDEST(Input_Stream_TDEST),
    .Gaussian_to_Sobel_din(Gaussian_Filter_U0_Gaussian_to_Sobel_din),
    .Gaussian_to_Sobel_full_n(Gaussian_to_Sobel_full_n),
    .Gaussian_to_Sobel_write(Gaussian_Filter_U0_Gaussian_to_Sobel_write),
    .Gaussian_to_Sobel_num_data_valid(Gaussian_to_Sobel_num_data_valid),
    .Gaussian_to_Sobel_fifo_cap(Gaussian_to_Sobel_fifo_cap),
    .Rows(Rows),
    .Cols(Cols),
    .Rows_c2_din(Gaussian_Filter_U0_Rows_c2_din),
    .Rows_c2_full_n(Rows_c2_full_n),
    .Rows_c2_write(Gaussian_Filter_U0_Rows_c2_write),
    .Rows_c2_num_data_valid(Rows_c2_num_data_valid),
    .Rows_c2_fifo_cap(Rows_c2_fifo_cap),
    .Cols_c4_din(Gaussian_Filter_U0_Cols_c4_din),
    .Cols_c4_full_n(Cols_c4_full_n),
    .Cols_c4_write(Gaussian_Filter_U0_Cols_c4_write),
    .Cols_c4_num_data_valid(Cols_c4_num_data_valid),
    .Cols_c4_fifo_cap(Cols_c4_fifo_cap)
);

Canny_Filter_Sobel_Filter Sobel_Filter_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Sobel_Filter_U0_ap_start),
    .start_full_n(start_for_Suppression_Filter_U0_full_n),
    .ap_done(Sobel_Filter_U0_ap_done),
    .ap_continue(Sobel_Filter_U0_ap_continue),
    .ap_idle(Sobel_Filter_U0_ap_idle),
    .ap_ready(Sobel_Filter_U0_ap_ready),
    .start_out(Sobel_Filter_U0_start_out),
    .start_write(Sobel_Filter_U0_start_write),
    .Gaussian_to_Sobel_dout(Gaussian_to_Sobel_dout),
    .Gaussian_to_Sobel_empty_n(Gaussian_to_Sobel_empty_n),
    .Gaussian_to_Sobel_read(Sobel_Filter_U0_Gaussian_to_Sobel_read),
    .Gaussian_to_Sobel_num_data_valid(Gaussian_to_Sobel_num_data_valid),
    .Gaussian_to_Sobel_fifo_cap(Gaussian_to_Sobel_fifo_cap),
    .Sobel_to_Suppression_din(Sobel_Filter_U0_Sobel_to_Suppression_din),
    .Sobel_to_Suppression_full_n(Sobel_to_Suppression_full_n),
    .Sobel_to_Suppression_write(Sobel_Filter_U0_Sobel_to_Suppression_write),
    .Sobel_to_Suppression_num_data_valid(Sobel_to_Suppression_num_data_valid),
    .Sobel_to_Suppression_fifo_cap(Sobel_to_Suppression_fifo_cap),
    .Rows_dout(Rows_c2_dout),
    .Rows_empty_n(Rows_c2_empty_n),
    .Rows_read(Sobel_Filter_U0_Rows_read),
    .Rows_num_data_valid(Rows_c2_num_data_valid),
    .Rows_fifo_cap(Rows_c2_fifo_cap),
    .Cols_dout(Cols_c4_dout),
    .Cols_empty_n(Cols_c4_empty_n),
    .Cols_read(Sobel_Filter_U0_Cols_read),
    .Cols_num_data_valid(Cols_c4_num_data_valid),
    .Cols_fifo_cap(Cols_c4_fifo_cap),
    .Rows_c1_din(Sobel_Filter_U0_Rows_c1_din),
    .Rows_c1_full_n(Rows_c1_full_n),
    .Rows_c1_write(Sobel_Filter_U0_Rows_c1_write),
    .Rows_c1_num_data_valid(Rows_c1_num_data_valid),
    .Rows_c1_fifo_cap(Rows_c1_fifo_cap),
    .Cols_c3_din(Sobel_Filter_U0_Cols_c3_din),
    .Cols_c3_full_n(Cols_c3_full_n),
    .Cols_c3_write(Sobel_Filter_U0_Cols_c3_write),
    .Cols_c3_num_data_valid(Cols_c3_num_data_valid),
    .Cols_c3_fifo_cap(Cols_c3_fifo_cap)
);

Canny_Filter_Suppression_Filter Suppression_Filter_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Suppression_Filter_U0_ap_start),
    .ap_done(Suppression_Filter_U0_ap_done),
    .ap_continue(Suppression_Filter_U0_ap_continue),
    .ap_idle(Suppression_Filter_U0_ap_idle),
    .ap_ready(Suppression_Filter_U0_ap_ready),
    .Sobel_to_Suppression_dout(Sobel_to_Suppression_dout),
    .Sobel_to_Suppression_empty_n(Sobel_to_Suppression_empty_n),
    .Sobel_to_Suppression_read(Suppression_Filter_U0_Sobel_to_Suppression_read),
    .Sobel_to_Suppression_num_data_valid(Sobel_to_Suppression_num_data_valid),
    .Sobel_to_Suppression_fifo_cap(Sobel_to_Suppression_fifo_cap),
    .Suppression_to_Hysteresis_din(Suppression_Filter_U0_Suppression_to_Hysteresis_din),
    .Suppression_to_Hysteresis_full_n(Suppression_to_Hysteresis_full_n),
    .Suppression_to_Hysteresis_write(Suppression_Filter_U0_Suppression_to_Hysteresis_write),
    .Suppression_to_Hysteresis_num_data_valid(Suppression_to_Hysteresis_num_data_valid),
    .Suppression_to_Hysteresis_fifo_cap(Suppression_to_Hysteresis_fifo_cap),
    .Rows_dout(Rows_c1_dout),
    .Rows_empty_n(Rows_c1_empty_n),
    .Rows_read(Suppression_Filter_U0_Rows_read),
    .Rows_num_data_valid(Rows_c1_num_data_valid),
    .Rows_fifo_cap(Rows_c1_fifo_cap),
    .Cols_dout(Cols_c3_dout),
    .Cols_empty_n(Cols_c3_empty_n),
    .Cols_read(Suppression_Filter_U0_Cols_read),
    .Cols_num_data_valid(Cols_c3_num_data_valid),
    .Cols_fifo_cap(Cols_c3_fifo_cap),
    .Rows_c_din(Suppression_Filter_U0_Rows_c_din),
    .Rows_c_full_n(Rows_c_full_n),
    .Rows_c_write(Suppression_Filter_U0_Rows_c_write),
    .Rows_c_num_data_valid(Rows_c_num_data_valid),
    .Rows_c_fifo_cap(Rows_c_fifo_cap),
    .Cols_c_din(Suppression_Filter_U0_Cols_c_din),
    .Cols_c_full_n(Cols_c_full_n),
    .Cols_c_write(Suppression_Filter_U0_Cols_c_write),
    .Cols_c_num_data_valid(Cols_c_num_data_valid),
    .Cols_c_fifo_cap(Cols_c_fifo_cap)
);

Canny_Filter_Hysteresis_Filter Hysteresis_Filter_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Hysteresis_Filter_U0_ap_start),
    .ap_done(Hysteresis_Filter_U0_ap_done),
    .ap_continue(Hysteresis_Filter_U0_ap_continue),
    .ap_idle(Hysteresis_Filter_U0_ap_idle),
    .ap_ready(Hysteresis_Filter_U0_ap_ready),
    .Suppression_to_Hysteresis_dout(Suppression_to_Hysteresis_dout),
    .Suppression_to_Hysteresis_empty_n(Suppression_to_Hysteresis_empty_n),
    .Suppression_to_Hysteresis_read(Hysteresis_Filter_U0_Suppression_to_Hysteresis_read),
    .Suppression_to_Hysteresis_num_data_valid(Suppression_to_Hysteresis_num_data_valid),
    .Suppression_to_Hysteresis_fifo_cap(Suppression_to_Hysteresis_fifo_cap),
    .Output_Stream_TDATA(Hysteresis_Filter_U0_Output_Stream_TDATA),
    .Output_Stream_TVALID(Hysteresis_Filter_U0_Output_Stream_TVALID),
    .Output_Stream_TREADY(Output_Stream_TREADY),
    .Output_Stream_TKEEP(Hysteresis_Filter_U0_Output_Stream_TKEEP),
    .Output_Stream_TSTRB(Hysteresis_Filter_U0_Output_Stream_TSTRB),
    .Output_Stream_TUSER(Hysteresis_Filter_U0_Output_Stream_TUSER),
    .Output_Stream_TLAST(Hysteresis_Filter_U0_Output_Stream_TLAST),
    .Output_Stream_TID(Hysteresis_Filter_U0_Output_Stream_TID),
    .Output_Stream_TDEST(Hysteresis_Filter_U0_Output_Stream_TDEST),
    .Rows_dout(Rows_c_dout),
    .Rows_empty_n(Rows_c_empty_n),
    .Rows_read(Hysteresis_Filter_U0_Rows_read),
    .Rows_num_data_valid(Rows_c_num_data_valid),
    .Rows_fifo_cap(Rows_c_fifo_cap),
    .Cols_dout(Cols_c_dout),
    .Cols_empty_n(Cols_c_empty_n),
    .Cols_read(Hysteresis_Filter_U0_Cols_read),
    .Cols_num_data_valid(Cols_c_num_data_valid),
    .Cols_fifo_cap(Cols_c_fifo_cap),
    .High_Threshold_dout(High_Threshold_c_dout),
    .High_Threshold_empty_n(High_Threshold_c_empty_n),
    .High_Threshold_read(Hysteresis_Filter_U0_High_Threshold_read),
    .High_Threshold_num_data_valid(High_Threshold_c_num_data_valid),
    .High_Threshold_fifo_cap(High_Threshold_c_fifo_cap),
    .Low_Threshold_dout(Low_Threshold_c_dout),
    .Low_Threshold_empty_n(Low_Threshold_c_empty_n),
    .Low_Threshold_read(Hysteresis_Filter_U0_Low_Threshold_read),
    .Low_Threshold_num_data_valid(Low_Threshold_c_num_data_valid),
    .Low_Threshold_fifo_cap(Low_Threshold_c_fifo_cap)
);

Canny_Filter_fifo_w32_d5_S High_Threshold_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_High_Threshold_c_din),
    .if_full_n(High_Threshold_c_full_n),
    .if_write(entry_proc_U0_High_Threshold_c_write),
    .if_dout(High_Threshold_c_dout),
    .if_empty_n(High_Threshold_c_empty_n),
    .if_read(Hysteresis_Filter_U0_High_Threshold_read),
    .if_num_data_valid(High_Threshold_c_num_data_valid),
    .if_fifo_cap(High_Threshold_c_fifo_cap)
);

Canny_Filter_fifo_w32_d5_S Low_Threshold_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_Low_Threshold_c_din),
    .if_full_n(Low_Threshold_c_full_n),
    .if_write(entry_proc_U0_Low_Threshold_c_write),
    .if_dout(Low_Threshold_c_dout),
    .if_empty_n(Low_Threshold_c_empty_n),
    .if_read(Hysteresis_Filter_U0_Low_Threshold_read),
    .if_num_data_valid(Low_Threshold_c_num_data_valid),
    .if_fifo_cap(Low_Threshold_c_fifo_cap)
);

Canny_Filter_fifo_w32_d8_S Gaussian_to_Sobel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Gaussian_Filter_U0_Gaussian_to_Sobel_din),
    .if_full_n(Gaussian_to_Sobel_full_n),
    .if_write(Gaussian_Filter_U0_Gaussian_to_Sobel_write),
    .if_dout(Gaussian_to_Sobel_dout),
    .if_empty_n(Gaussian_to_Sobel_empty_n),
    .if_read(Sobel_Filter_U0_Gaussian_to_Sobel_read),
    .if_num_data_valid(Gaussian_to_Sobel_num_data_valid),
    .if_fifo_cap(Gaussian_to_Sobel_fifo_cap)
);

Canny_Filter_fifo_w32_d2_S Rows_c2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Gaussian_Filter_U0_Rows_c2_din),
    .if_full_n(Rows_c2_full_n),
    .if_write(Gaussian_Filter_U0_Rows_c2_write),
    .if_dout(Rows_c2_dout),
    .if_empty_n(Rows_c2_empty_n),
    .if_read(Sobel_Filter_U0_Rows_read),
    .if_num_data_valid(Rows_c2_num_data_valid),
    .if_fifo_cap(Rows_c2_fifo_cap)
);

Canny_Filter_fifo_w32_d2_S Cols_c4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Gaussian_Filter_U0_Cols_c4_din),
    .if_full_n(Cols_c4_full_n),
    .if_write(Gaussian_Filter_U0_Cols_c4_write),
    .if_dout(Cols_c4_dout),
    .if_empty_n(Cols_c4_empty_n),
    .if_read(Sobel_Filter_U0_Cols_read),
    .if_num_data_valid(Cols_c4_num_data_valid),
    .if_fifo_cap(Cols_c4_fifo_cap)
);

Canny_Filter_fifo_w32_d8_S Sobel_to_Suppression_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_Filter_U0_Sobel_to_Suppression_din),
    .if_full_n(Sobel_to_Suppression_full_n),
    .if_write(Sobel_Filter_U0_Sobel_to_Suppression_write),
    .if_dout(Sobel_to_Suppression_dout),
    .if_empty_n(Sobel_to_Suppression_empty_n),
    .if_read(Suppression_Filter_U0_Sobel_to_Suppression_read),
    .if_num_data_valid(Sobel_to_Suppression_num_data_valid),
    .if_fifo_cap(Sobel_to_Suppression_fifo_cap)
);

Canny_Filter_fifo_w32_d2_S Rows_c1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_Filter_U0_Rows_c1_din),
    .if_full_n(Rows_c1_full_n),
    .if_write(Sobel_Filter_U0_Rows_c1_write),
    .if_dout(Rows_c1_dout),
    .if_empty_n(Rows_c1_empty_n),
    .if_read(Suppression_Filter_U0_Rows_read),
    .if_num_data_valid(Rows_c1_num_data_valid),
    .if_fifo_cap(Rows_c1_fifo_cap)
);

Canny_Filter_fifo_w32_d2_S Cols_c3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_Filter_U0_Cols_c3_din),
    .if_full_n(Cols_c3_full_n),
    .if_write(Sobel_Filter_U0_Cols_c3_write),
    .if_dout(Cols_c3_dout),
    .if_empty_n(Cols_c3_empty_n),
    .if_read(Suppression_Filter_U0_Cols_read),
    .if_num_data_valid(Cols_c3_num_data_valid),
    .if_fifo_cap(Cols_c3_fifo_cap)
);

Canny_Filter_fifo_w32_d8_S Suppression_to_Hysteresis_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Suppression_Filter_U0_Suppression_to_Hysteresis_din),
    .if_full_n(Suppression_to_Hysteresis_full_n),
    .if_write(Suppression_Filter_U0_Suppression_to_Hysteresis_write),
    .if_dout(Suppression_to_Hysteresis_dout),
    .if_empty_n(Suppression_to_Hysteresis_empty_n),
    .if_read(Hysteresis_Filter_U0_Suppression_to_Hysteresis_read),
    .if_num_data_valid(Suppression_to_Hysteresis_num_data_valid),
    .if_fifo_cap(Suppression_to_Hysteresis_fifo_cap)
);

Canny_Filter_fifo_w32_d2_S Rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Suppression_Filter_U0_Rows_c_din),
    .if_full_n(Rows_c_full_n),
    .if_write(Suppression_Filter_U0_Rows_c_write),
    .if_dout(Rows_c_dout),
    .if_empty_n(Rows_c_empty_n),
    .if_read(Hysteresis_Filter_U0_Rows_read),
    .if_num_data_valid(Rows_c_num_data_valid),
    .if_fifo_cap(Rows_c_fifo_cap)
);

Canny_Filter_fifo_w32_d2_S Cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Suppression_Filter_U0_Cols_c_din),
    .if_full_n(Cols_c_full_n),
    .if_write(Suppression_Filter_U0_Cols_c_write),
    .if_dout(Cols_c_dout),
    .if_empty_n(Cols_c_empty_n),
    .if_read(Hysteresis_Filter_U0_Cols_read),
    .if_num_data_valid(Cols_c_num_data_valid),
    .if_fifo_cap(Cols_c_fifo_cap)
);

Canny_Filter_start_for_Hysteresis_Filter_U0 start_for_Hysteresis_Filter_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Hysteresis_Filter_U0_din),
    .if_full_n(start_for_Hysteresis_Filter_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_Hysteresis_Filter_U0_dout),
    .if_empty_n(start_for_Hysteresis_Filter_U0_empty_n),
    .if_read(Hysteresis_Filter_U0_ap_ready)
);

Canny_Filter_start_for_Sobel_Filter_U0 start_for_Sobel_Filter_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Sobel_Filter_U0_din),
    .if_full_n(start_for_Sobel_Filter_U0_full_n),
    .if_write(Gaussian_Filter_U0_start_write),
    .if_dout(start_for_Sobel_Filter_U0_dout),
    .if_empty_n(start_for_Sobel_Filter_U0_empty_n),
    .if_read(Sobel_Filter_U0_ap_ready)
);

Canny_Filter_start_for_Suppression_Filter_U0 start_for_Suppression_Filter_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Suppression_Filter_U0_din),
    .if_full_n(start_for_Suppression_Filter_U0_full_n),
    .if_write(Sobel_Filter_U0_start_write),
    .if_dout(start_for_Suppression_Filter_U0_dout),
    .if_empty_n(start_for_Suppression_Filter_U0_empty_n),
    .if_read(Suppression_Filter_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Gaussian_Filter_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Gaussian_Filter_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Gaussian_Filter_U0_ap_ready <= ap_sync_Gaussian_Filter_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign Gaussian_Filter_U0_ap_continue = 1'b1;

assign Gaussian_Filter_U0_ap_start = ((ap_sync_reg_Gaussian_Filter_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign Hysteresis_Filter_U0_ap_continue = 1'b1;

assign Hysteresis_Filter_U0_ap_start = start_for_Hysteresis_Filter_U0_empty_n;

assign Input_Stream_TREADY = Gaussian_Filter_U0_Input_Stream_TREADY;

assign Output_Stream_TDATA = Hysteresis_Filter_U0_Output_Stream_TDATA;

assign Output_Stream_TDEST = Hysteresis_Filter_U0_Output_Stream_TDEST;

assign Output_Stream_TID = Hysteresis_Filter_U0_Output_Stream_TID;

assign Output_Stream_TKEEP = Hysteresis_Filter_U0_Output_Stream_TKEEP;

assign Output_Stream_TLAST = Hysteresis_Filter_U0_Output_Stream_TLAST;

assign Output_Stream_TSTRB = Hysteresis_Filter_U0_Output_Stream_TSTRB;

assign Output_Stream_TUSER = Hysteresis_Filter_U0_Output_Stream_TUSER;

assign Output_Stream_TVALID = Hysteresis_Filter_U0_Output_Stream_TVALID;

assign Sobel_Filter_U0_ap_continue = 1'b1;

assign Sobel_Filter_U0_ap_start = start_for_Sobel_Filter_U0_empty_n;

assign Suppression_Filter_U0_ap_continue = 1'b1;

assign Suppression_Filter_U0_ap_start = start_for_Suppression_Filter_U0_empty_n;

assign ap_done = Hysteresis_Filter_U0_ap_done;

assign ap_idle = (entry_proc_U0_ap_idle & Suppression_Filter_U0_ap_idle & Sobel_Filter_U0_ap_idle & Hysteresis_Filter_U0_ap_idle & Gaussian_Filter_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Gaussian_Filter_U0_ap_ready = (ap_sync_reg_Gaussian_Filter_U0_ap_ready | Gaussian_Filter_U0_ap_ready);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_Gaussian_Filter_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign start_for_Hysteresis_Filter_U0_din = 1'b1;

assign start_for_Sobel_Filter_U0_din = 1'b1;

assign start_for_Suppression_Filter_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "Canny_Filter_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "Canny_Filter_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //Canny_Filter

