// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module Canny_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Gaussian_to_Sobel_dout,
        Gaussian_to_Sobel_empty_n,
        Gaussian_to_Sobel_read,
        Gaussian_to_Sobel_num_data_valid,
        Gaussian_to_Sobel_fifo_cap,
        Sobel_to_Suppression_din,
        Sobel_to_Suppression_full_n,
        Sobel_to_Suppression_write,
        Sobel_to_Suppression_num_data_valid,
        Sobel_to_Suppression_fifo_cap,
        Cols_2,
        bound
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] Gaussian_to_Sobel_dout;
input   Gaussian_to_Sobel_empty_n;
output   Gaussian_to_Sobel_read;
input  [3:0] Gaussian_to_Sobel_num_data_valid;
input  [3:0] Gaussian_to_Sobel_fifo_cap;
output  [31:0] Sobel_to_Suppression_din;
input   Sobel_to_Suppression_full_n;
output   Sobel_to_Suppression_write;
input  [3:0] Sobel_to_Suppression_num_data_valid;
input  [3:0] Sobel_to_Suppression_fifo_cap;
input  [31:0] Cols_2;
input  [61:0] bound;

reg ap_idle;
reg Gaussian_to_Sobel_read;
reg Sobel_to_Suppression_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln14_reg_846;
reg    ap_block_state3_pp0_stage0_iter2_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln14_fu_243_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    Gaussian_to_Sobel_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    Sobel_to_Suppression_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] icmp_ln14_reg_846_pp0_iter2_reg;
reg   [31:0] Pixel_In_reg_850;
reg   [31:0] Pixel_In_reg_850_pp0_iter3_reg;
reg   [10:0] Line_Buffer_addr_reg_858;
wire   [0:0] addr_cmp31_fu_288_p2;
reg   [0:0] addr_cmp31_reg_864;
wire   [0:0] addr_cmp_fu_297_p2;
reg   [0:0] addr_cmp_reg_874;
wire   [31:0] Top_Pixel_fu_353_p3;
reg   [31:0] Top_Pixel_reg_879;
wire   [30:0] tmp7_fu_384_p2;
reg   [30:0] tmp7_reg_885;
wire   [31:0] sub_ln45_fu_416_p2;
reg   [31:0] sub_ln45_reg_890;
wire   [31:0] add_ln46_fu_421_p2;
reg   [31:0] add_ln46_reg_895;
wire   [31:0] Gx_Value_fu_468_p2;
reg   [31:0] Gx_Value_reg_900;
reg   [31:0] Gx_Value_reg_900_pp0_iter5_reg;
reg   [31:0] Gx_Value_reg_900_pp0_iter6_reg;
wire   [31:0] Gy_Value_2_fu_477_p2;
reg   [31:0] Gy_Value_2_reg_907;
reg   [31:0] Gy_Value_2_reg_907_pp0_iter5_reg;
reg   [31:0] Gy_Value_2_reg_907_pp0_iter6_reg;
reg   [0:0] tmp_1_reg_915;
wire   [31:0] sub_ln50_fu_490_p2;
reg   [31:0] sub_ln50_reg_920;
reg   [0:0] tmp_2_reg_925;
wire   [31:0] Gx_Value_Abs_fu_504_p3;
reg   [31:0] Gx_Value_Abs_reg_930;
wire   [31:0] Gy_Value_Abs_fu_514_p3;
reg   [31:0] Gy_Value_Abs_reg_937;
wire   [31:0] sub_ln56_fu_532_p2;
reg   [31:0] sub_ln56_reg_944;
wire   [31:0] sub_ln57_fu_550_p2;
reg   [31:0] sub_ln57_reg_949;
wire   [31:0] Magnitude_fu_556_p2;
reg   [31:0] Magnitude_reg_954;
wire   [0:0] icmp_ln54_fu_570_p2;
reg   [0:0] icmp_ln54_reg_959;
wire   [0:0] icmp_ln60_fu_636_p2;
reg   [0:0] icmp_ln60_reg_964;
wire   [0:0] icmp_ln61_fu_641_p2;
reg   [0:0] icmp_ln61_reg_970;
wire   [0:0] icmp_ln62_fu_646_p2;
reg   [0:0] icmp_ln62_reg_975;
wire   [0:0] icmp_ln62_2_fu_651_p2;
reg   [0:0] icmp_ln62_2_reg_980;
reg    ap_condition_exit_pp0_iter3_stage0;
wire   [10:0] Line_Buffer_1_address0;
wire   [31:0] Line_Buffer_1_q0;
wire   [10:0] Line_Buffer_address1;
wire   [31:0] Line_Buffer_q1;
wire   [63:0] zext_ln16_fu_279_p1;
reg   [63:0] reuse_addr_reg28_fu_100;
wire    ap_loop_init;
reg   [31:0] reuse_reg27_fu_104;
wire   [31:0] Mid_Pixel_fu_363_p3;
reg   [63:0] reuse_addr_reg_fu_108;
reg   [31:0] reuse_reg_fu_112;
reg   [31:0] Gy_Value_fu_116;
reg   [30:0] empty_fu_120;
reg   [31:0] empty_57_fu_124;
reg   [30:0] J_fu_128;
wire   [30:0] add_ln16_fu_313_p2;
reg   [61:0] indvar_flatten_fu_132;
wire   [61:0] add_ln14_fu_248_p2;
wire    ap_block_pp0_stage0;
reg   [31:0] empty_58_fu_136;
reg   [30:0] empty_59_fu_140;
wire   [30:0] empty_61_fu_371_p1;
reg   [31:0] empty_60_fu_144;
reg    ap_block_pp0_stage0_01001_grp1;
reg    Line_Buffer_ce1_local;
reg    Line_Buffer_we0_local;
reg    Line_Buffer_ce0_local;
reg    Line_Buffer_1_ce0_local;
reg    Line_Buffer_1_we0_local;
wire   [31:0] zext_ln16_1_fu_262_p1;
wire   [0:0] icmp_ln16_fu_266_p2;
wire   [30:0] select_ln14_fu_271_p3;
wire   [30:0] trunc_ln16_1_fu_346_p1;
wire   [30:0] trunc_ln16_fu_342_p1;
wire   [30:0] tmp35_fu_396_p2;
wire   [31:0] add_ln45_fu_410_p2;
wire   [31:0] sub_ln46_fu_390_p2;
wire   [31:0] tmp4_fu_402_p3;
wire   [31:0] tmp1_fu_456_p3;
wire   [31:0] add_ln45_1_fu_463_p2;
wire   [31:0] Gy_Value_3_fu_473_p2;
wire   [31:0] sub_ln51_fu_509_p2;
wire   [31:0] shl_ln56_fu_520_p2;
wire   [31:0] shl_ln56_1_fu_526_p2;
wire   [31:0] shl_ln57_fu_538_p2;
wire   [31:0] add_ln57_fu_544_p2;
wire   [23:0] tmp_3_fu_560_p4;
wire   [31:0] shl_ln56_2_fu_576_p2;
wire   [31:0] add_ln56_fu_581_p2;
wire   [31:0] shl_ln56_3_fu_586_p2;
wire   [31:0] add_ln56_1_fu_591_p2;
wire   [23:0] Tangent_22_5_fu_597_p4;
wire   [31:0] add_ln57_1_fu_611_p2;
wire   [31:0] add_ln57_2_fu_616_p2;
wire   [23:0] Tangent_67_5_fu_622_p4;
wire  signed [31:0] sext_ln56_fu_607_p1;
wire  signed [31:0] sext_ln57_fu_632_p1;
wire   [31:0] and_ln62_1_fu_666_p2;
wire   [0:0] and_ln62_fu_662_p2;
wire   [0:0] tmp_4_fu_670_p3;
wire   [0:0] or_ln62_fu_678_p2;
wire   [0:0] xor_ln60_fu_692_p2;
wire   [0:0] and_ln61_fu_697_p2;
wire   [15:0] Direction_fu_709_p6;
wire   [15:0] Direction_fu_709_p7;
wire   [1:0] Direction_fu_709_p8;
wire   [31:0] Magnitude_1_fu_656_p3;
wire   [15:0] trunc_ln67_fu_729_p1;
wire   [15:0] Direction_fu_709_p9;
wire   [15:0] tmp_fu_739_p4;
wire   [15:0] or_ln67_fu_733_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [1:0] Direction_fu_709_p1;
wire   [1:0] Direction_fu_709_p3;
wire   [1:0] Direction_fu_709_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 reuse_addr_reg28_fu_100 = 64'd0;
#0 reuse_reg27_fu_104 = 32'd0;
#0 reuse_addr_reg_fu_108 = 64'd0;
#0 reuse_reg_fu_112 = 32'd0;
#0 Gy_Value_fu_116 = 32'd0;
#0 empty_fu_120 = 31'd0;
#0 empty_57_fu_124 = 32'd0;
#0 J_fu_128 = 31'd0;
#0 indvar_flatten_fu_132 = 62'd0;
#0 empty_58_fu_136 = 32'd0;
#0 empty_59_fu_140 = 31'd0;
#0 empty_60_fu_144 = 32'd0;
#0 ap_done_reg = 1'b0;
end

Canny_Filter_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_Line_Buffer_1_RAM_AUbkb #(
    .DataWidth( 32 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
Line_Buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Line_Buffer_1_address0),
    .ce0(Line_Buffer_1_ce0_local),
    .we0(Line_Buffer_1_we0_local),
    .d0(Gaussian_to_Sobel_dout),
    .q0(Line_Buffer_1_q0)
);

Canny_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_Line_Buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
Line_Buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Line_Buffer_addr_reg_858),
    .ce0(Line_Buffer_ce0_local),
    .we0(Line_Buffer_we0_local),
    .d0(Mid_Pixel_fu_363_p3),
    .address1(Line_Buffer_address1),
    .ce1(Line_Buffer_ce1_local),
    .q1(Line_Buffer_q1)
);

(* dissolve_hierarchy = "yes" *) Canny_Filter_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U37(
    .din0(16'd0),
    .din1(16'd23040),
    .din2(Direction_fu_709_p6),
    .def(Direction_fu_709_p7),
    .sel(Direction_fu_709_p8),
    .dout(Direction_fu_709_p9)
);

Canny_Filter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            J_fu_128 <= 31'd0;
        end else if (((icmp_ln14_reg_846 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            J_fu_128 <= add_ln16_fu_313_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_132 <= 62'd0;
        end else if (((icmp_ln14_fu_243_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_132 <= add_ln14_fu_248_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg28_fu_100 <= 64'd18446744073709551615;
        end else if (((icmp_ln14_reg_846 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            reuse_addr_reg28_fu_100 <= zext_ln16_fu_279_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg_fu_108 <= 64'd18446744073709551615;
        end else if (((icmp_ln14_reg_846 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            reuse_addr_reg_fu_108 <= zext_ln16_fu_279_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg27_fu_104 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_reg_846_pp0_iter2_reg == 1'd0))) begin
            reuse_reg27_fu_104 <= Mid_Pixel_fu_363_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg_fu_112 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_reg_846_pp0_iter2_reg == 1'd0))) begin
            reuse_reg_fu_112 <= Pixel_In_reg_850;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        Gx_Value_Abs_reg_930 <= Gx_Value_Abs_fu_504_p3;
        Gx_Value_reg_900 <= Gx_Value_fu_468_p2;
        Gx_Value_reg_900_pp0_iter5_reg <= Gx_Value_reg_900;
        Gx_Value_reg_900_pp0_iter6_reg <= Gx_Value_reg_900_pp0_iter5_reg;
        Gy_Value_2_reg_907 <= Gy_Value_2_fu_477_p2;
        Gy_Value_2_reg_907_pp0_iter5_reg <= Gy_Value_2_reg_907;
        Gy_Value_2_reg_907_pp0_iter6_reg <= Gy_Value_2_reg_907_pp0_iter5_reg;
        Gy_Value_Abs_reg_937 <= Gy_Value_Abs_fu_514_p3;
        Line_Buffer_addr_reg_858 <= zext_ln16_fu_279_p1;
        Magnitude_reg_954 <= Magnitude_fu_556_p2;
        Pixel_In_reg_850 <= Gaussian_to_Sobel_dout;
        Pixel_In_reg_850_pp0_iter3_reg <= Pixel_In_reg_850;
        Top_Pixel_reg_879 <= Top_Pixel_fu_353_p3;
        add_ln46_reg_895 <= add_ln46_fu_421_p2;
        addr_cmp31_reg_864 <= addr_cmp31_fu_288_p2;
        addr_cmp_reg_874 <= addr_cmp_fu_297_p2;
        icmp_ln54_reg_959 <= icmp_ln54_fu_570_p2;
        icmp_ln60_reg_964 <= icmp_ln60_fu_636_p2;
        icmp_ln61_reg_970 <= icmp_ln61_fu_641_p2;
        icmp_ln62_2_reg_980 <= icmp_ln62_2_fu_651_p2;
        icmp_ln62_reg_975 <= icmp_ln62_fu_646_p2;
        sub_ln45_reg_890 <= sub_ln45_fu_416_p2;
        sub_ln50_reg_920 <= sub_ln50_fu_490_p2;
        sub_ln56_reg_944 <= sub_ln56_fu_532_p2;
        sub_ln57_reg_949 <= sub_ln57_fu_550_p2;
        tmp7_reg_885 <= tmp7_fu_384_p2;
        tmp_1_reg_915 <= Gx_Value_fu_468_p2[32'd31];
        tmp_2_reg_925 <= Gy_Value_2_fu_477_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_reg_846_pp0_iter2_reg == 1'd0))) begin
        Gy_Value_fu_116 <= empty_58_fu_136;
        empty_57_fu_124 <= empty_60_fu_144;
        empty_58_fu_136 <= Top_Pixel_fu_353_p3;
        empty_59_fu_140 <= empty_61_fu_371_p1;
        empty_60_fu_144 <= Pixel_In_reg_850;
        empty_fu_120 <= empty_59_fu_140;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln14_reg_846 <= icmp_ln14_fu_243_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln14_reg_846_pp0_iter2_reg <= icmp_ln14_reg_846;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln14_reg_846 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Gaussian_to_Sobel_blk_n = Gaussian_to_Sobel_empty_n;
    end else begin
        Gaussian_to_Sobel_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln14_reg_846 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Gaussian_to_Sobel_read = 1'b1;
    end else begin
        Gaussian_to_Sobel_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln14_reg_846 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Line_Buffer_1_ce0_local = 1'b1;
    end else begin
        Line_Buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln14_reg_846 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Line_Buffer_1_we0_local = 1'b1;
    end else begin
        Line_Buffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        Line_Buffer_ce0_local = 1'b1;
    end else begin
        Line_Buffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Line_Buffer_ce1_local = 1'b1;
    end else begin
        Line_Buffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_reg_846_pp0_iter2_reg == 1'd0))) begin
        Line_Buffer_we0_local = 1'b1;
    end else begin
        Line_Buffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        Sobel_to_Suppression_blk_n = Sobel_to_Suppression_full_n;
    end else begin
        Sobel_to_Suppression_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        Sobel_to_Suppression_write = 1'b1;
    end else begin
        Sobel_to_Suppression_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln14_fu_243_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_reg_846_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Direction_fu_709_p6 = ((or_ln62_fu_678_p2[0:0] == 1'b1) ? 16'd11520 : 16'd34560);

assign Direction_fu_709_p7 = 'bx;

assign Direction_fu_709_p8 = {{icmp_ln60_reg_964}, {and_ln61_fu_697_p2}};

assign Gx_Value_Abs_fu_504_p3 = ((tmp_1_reg_915[0:0] == 1'b1) ? sub_ln50_reg_920 : Gx_Value_reg_900);

assign Gx_Value_fu_468_p2 = (add_ln45_1_fu_463_p2 + Top_Pixel_reg_879);

assign Gy_Value_2_fu_477_p2 = (Top_Pixel_reg_879 + Gy_Value_3_fu_473_p2);

assign Gy_Value_3_fu_473_p2 = (add_ln46_reg_895 - Pixel_In_reg_850_pp0_iter3_reg);

assign Gy_Value_Abs_fu_514_p3 = ((tmp_2_reg_925[0:0] == 1'b1) ? sub_ln51_fu_509_p2 : Gy_Value_2_reg_907);

assign Line_Buffer_1_address0 = zext_ln16_fu_279_p1;

assign Line_Buffer_address1 = zext_ln16_fu_279_p1;

assign Magnitude_1_fu_656_p3 = ((icmp_ln54_reg_959[0:0] == 1'b1) ? 32'd255 : Magnitude_reg_954);

assign Magnitude_fu_556_p2 = (Gx_Value_Abs_reg_930 + Gy_Value_Abs_reg_937);

assign Mid_Pixel_fu_363_p3 = ((addr_cmp_reg_874[0:0] == 1'b1) ? reuse_reg_fu_112 : Line_Buffer_1_q0);

assign Sobel_to_Suppression_din = {{tmp_fu_739_p4}, {or_ln67_fu_733_p2}};

assign Tangent_22_5_fu_597_p4 = {{add_ln56_1_fu_591_p2[31:8]}};

assign Tangent_67_5_fu_622_p4 = {{add_ln57_2_fu_616_p2[31:8]}};

assign Top_Pixel_fu_353_p3 = ((addr_cmp31_reg_864[0:0] == 1'b1) ? reuse_reg27_fu_104 : Line_Buffer_q1);

assign add_ln14_fu_248_p2 = (indvar_flatten_fu_132 + 62'd1);

assign add_ln16_fu_313_p2 = (select_ln14_fu_271_p3 + 31'd1);

assign add_ln45_1_fu_463_p2 = (sub_ln45_reg_890 + tmp1_fu_456_p3);

assign add_ln45_fu_410_p2 = (Gy_Value_fu_116 + empty_57_fu_124);

assign add_ln46_fu_421_p2 = (sub_ln46_fu_390_p2 + tmp4_fu_402_p3);

assign add_ln56_1_fu_591_p2 = (add_ln56_fu_581_p2 + shl_ln56_3_fu_586_p2);

assign add_ln56_fu_581_p2 = (sub_ln56_reg_944 + shl_ln56_2_fu_576_p2);

assign add_ln57_1_fu_611_p2 = (sub_ln57_reg_949 + shl_ln56_2_fu_576_p2);

assign add_ln57_2_fu_616_p2 = (add_ln57_1_fu_611_p2 + shl_ln56_3_fu_586_p2);

assign add_ln57_fu_544_p2 = (shl_ln57_fu_538_p2 + shl_ln56_fu_520_p2);

assign addr_cmp31_fu_288_p2 = ((reuse_addr_reg28_fu_100 == zext_ln16_fu_279_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_297_p2 = ((reuse_addr_reg_fu_108 == zext_ln16_fu_279_p1) ? 1'b1 : 1'b0);

assign and_ln61_fu_697_p2 = (xor_ln60_fu_692_p2 & icmp_ln61_reg_970);

assign and_ln62_1_fu_666_p2 = (Gy_Value_2_reg_907_pp0_iter6_reg & Gx_Value_reg_900_pp0_iter6_reg);

assign and_ln62_fu_662_p2 = (icmp_ln62_reg_975 & icmp_ln62_2_reg_980);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == Sobel_to_Suppression_full_n)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == Sobel_to_Suppression_full_n)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == Sobel_to_Suppression_full_n)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == Sobel_to_Suppression_full_n)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2_grp1 = ((icmp_ln14_reg_846 == 1'd0) & (1'b0 == Gaussian_to_Sobel_empty_n));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign empty_61_fu_371_p1 = Mid_Pixel_fu_363_p3[30:0];

assign icmp_ln14_fu_243_p2 = ((indvar_flatten_fu_132 == bound) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_266_p2 = (($signed(zext_ln16_1_fu_262_p1) < $signed(Cols_2)) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_570_p2 = (($signed(tmp_3_fu_560_p4) > $signed(24'd0)) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_636_p2 = (($signed(Gy_Value_Abs_reg_937) < $signed(sext_ln56_fu_607_p1)) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_641_p2 = (($signed(Gy_Value_Abs_reg_937) > $signed(sext_ln57_fu_632_p1)) ? 1'b1 : 1'b0);

assign icmp_ln62_2_fu_651_p2 = (($signed(Gy_Value_2_reg_907_pp0_iter5_reg) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_646_p2 = (($signed(Gx_Value_reg_900_pp0_iter5_reg) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign or_ln62_fu_678_p2 = (tmp_4_fu_670_p3 | and_ln62_fu_662_p2);

assign or_ln67_fu_733_p2 = (trunc_ln67_fu_729_p1 | Direction_fu_709_p9);

assign select_ln14_fu_271_p3 = ((icmp_ln16_fu_266_p2[0:0] == 1'b1) ? J_fu_128 : 31'd0);

assign sext_ln56_fu_607_p1 = $signed(Tangent_22_5_fu_597_p4);

assign sext_ln57_fu_632_p1 = $signed(Tangent_67_5_fu_622_p4);

assign shl_ln56_1_fu_526_p2 = Gx_Value_Abs_fu_504_p3 << 32'd5;

assign shl_ln56_2_fu_576_p2 = Gx_Value_Abs_reg_930 << 32'd3;

assign shl_ln56_3_fu_586_p2 = Gx_Value_Abs_reg_930 << 32'd1;

assign shl_ln56_fu_520_p2 = Gx_Value_Abs_fu_504_p3 << 32'd7;

assign shl_ln57_fu_538_p2 = Gx_Value_Abs_fu_504_p3 << 32'd9;

assign sub_ln45_fu_416_p2 = (Pixel_In_reg_850 - add_ln45_fu_410_p2);

assign sub_ln46_fu_390_p2 = (Gy_Value_fu_116 - empty_57_fu_124);

assign sub_ln50_fu_490_p2 = (32'd0 - Gx_Value_fu_468_p2);

assign sub_ln51_fu_509_p2 = (32'd0 - Gy_Value_2_reg_907);

assign sub_ln56_fu_532_p2 = (shl_ln56_fu_520_p2 - shl_ln56_1_fu_526_p2);

assign sub_ln57_fu_550_p2 = (add_ln57_fu_544_p2 - shl_ln56_1_fu_526_p2);

assign tmp1_fu_456_p3 = {{tmp7_reg_885}, {1'd0}};

assign tmp35_fu_396_p2 = (trunc_ln16_1_fu_346_p1 - trunc_ln16_fu_342_p1);

assign tmp4_fu_402_p3 = {{tmp35_fu_396_p2}, {1'd0}};

assign tmp7_fu_384_p2 = (empty_61_fu_371_p1 - empty_fu_120);

assign tmp_3_fu_560_p4 = {{Magnitude_fu_556_p2[31:8]}};

assign tmp_4_fu_670_p3 = and_ln62_1_fu_666_p2[32'd31];

assign tmp_fu_739_p4 = {{Magnitude_1_fu_656_p3[31:16]}};

assign trunc_ln16_1_fu_346_p1 = empty_58_fu_136[30:0];

assign trunc_ln16_fu_342_p1 = empty_60_fu_144[30:0];

assign trunc_ln67_fu_729_p1 = Magnitude_1_fu_656_p3[15:0];

assign xor_ln60_fu_692_p2 = (icmp_ln60_reg_964 ^ 1'd1);

assign zext_ln16_1_fu_262_p1 = J_fu_128;

assign zext_ln16_fu_279_p1 = select_ln14_fu_271_p3;

endmodule //Canny_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2
