[hls]
relative_roots=C:/F.A.L.C.O.N/Vitis_WS/Canny_Filter_IP
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=gaussian_filter/VITIS_LOOP_15_2  
syn.directive.loop_flatten=hysteresis_filter/VITIS_LOOP_13_2  
syn.directive.loop_flatten=sobel_filter/VITIS_LOOP_16_2  
syn.directive.loop_flatten=suppression_filter/VITIS_LOOP_13_2  


