// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module sobel_filter_sobel_filter_Pipeline_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul_ln17,
        window_keep_address0,
        window_keep_ce0,
        window_keep_we0,
        window_keep_d0,
        window_strb_address0,
        window_strb_ce0,
        window_strb_we0,
        window_strb_d0,
        window_user_address0,
        window_user_ce0,
        window_user_we0,
        window_user_d0,
        window_last_address0,
        window_last_ce0,
        window_last_we0,
        window_last_d0,
        window_id_address0,
        window_id_ce0,
        window_id_we0,
        window_id_d0,
        window_dest_address0,
        window_dest_ce0,
        window_dest_we0,
        window_dest_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] mul_ln17;
output  [3:0] window_keep_address0;
output   window_keep_ce0;
output   window_keep_we0;
output  [3:0] window_keep_d0;
output  [3:0] window_strb_address0;
output   window_strb_ce0;
output   window_strb_we0;
output  [3:0] window_strb_d0;
output  [3:0] window_user_address0;
output   window_user_ce0;
output   window_user_we0;
output  [1:0] window_user_d0;
output  [3:0] window_last_address0;
output   window_last_ce0;
output   window_last_we0;
output  [0:0] window_last_d0;
output  [3:0] window_id_address0;
output   window_id_ce0;
output   window_id_we0;
output  [4:0] window_id_d0;
output  [3:0] window_dest_address0;
output   window_dest_ce0;
output   window_dest_we0;
output  [5:0] window_dest_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln17_fu_178_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln17_1_fu_162_p1;
reg   [1:0] indvars_iv_fu_46;
wire   [1:0] add_ln17_fu_172_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_indvars_iv_load;
reg    window_keep_we0_local;
reg    window_keep_ce0_local;
reg    window_strb_we0_local;
reg    window_strb_ce0_local;
reg    window_user_we0_local;
reg    window_user_ce0_local;
reg    window_last_we0_local;
reg    window_last_ce0_local;
reg    window_id_we0_local;
reg    window_id_ce0_local;
reg    window_dest_we0_local;
reg    window_dest_ce0_local;
wire   [3:0] mul_ln17_cast_fu_140_p1;
wire   [3:0] zext_ln17_fu_152_p1;
wire   [3:0] add_ln17_1_fu_156_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 indvars_iv_fu_46 = 2'd0;
#0 ap_done_reg = 1'b0;
end

sobel_filter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        indvars_iv_fu_46 <= add_ln17_fu_172_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln17_fu_178_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvars_iv_load = 2'd0;
    end else begin
        ap_sig_allocacmp_indvars_iv_load = indvars_iv_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_dest_ce0_local = 1'b1;
    end else begin
        window_dest_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_dest_we0_local = 1'b1;
    end else begin
        window_dest_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_id_ce0_local = 1'b1;
    end else begin
        window_id_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_id_we0_local = 1'b1;
    end else begin
        window_id_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_keep_ce0_local = 1'b1;
    end else begin
        window_keep_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_keep_we0_local = 1'b1;
    end else begin
        window_keep_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_last_ce0_local = 1'b1;
    end else begin
        window_last_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_last_we0_local = 1'b1;
    end else begin
        window_last_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_strb_ce0_local = 1'b1;
    end else begin
        window_strb_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_strb_we0_local = 1'b1;
    end else begin
        window_strb_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_user_ce0_local = 1'b1;
    end else begin
        window_user_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        window_user_we0_local = 1'b1;
    end else begin
        window_user_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln17_1_fu_156_p2 = (mul_ln17_cast_fu_140_p1 + zext_ln17_fu_152_p1);

assign add_ln17_fu_172_p2 = (ap_sig_allocacmp_indvars_iv_load + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln17_fu_178_p2 = ((ap_sig_allocacmp_indvars_iv_load == 2'd2) ? 1'b1 : 1'b0);

assign mul_ln17_cast_fu_140_p1 = mul_ln17;

assign window_dest_address0 = zext_ln17_1_fu_162_p1;

assign window_dest_ce0 = window_dest_ce0_local;

assign window_dest_d0 = 6'd0;

assign window_dest_we0 = window_dest_we0_local;

assign window_id_address0 = zext_ln17_1_fu_162_p1;

assign window_id_ce0 = window_id_ce0_local;

assign window_id_d0 = 5'd0;

assign window_id_we0 = window_id_we0_local;

assign window_keep_address0 = zext_ln17_1_fu_162_p1;

assign window_keep_ce0 = window_keep_ce0_local;

assign window_keep_d0 = 4'd15;

assign window_keep_we0 = window_keep_we0_local;

assign window_last_address0 = zext_ln17_1_fu_162_p1;

assign window_last_ce0 = window_last_ce0_local;

assign window_last_d0 = 1'd0;

assign window_last_we0 = window_last_we0_local;

assign window_strb_address0 = zext_ln17_1_fu_162_p1;

assign window_strb_ce0 = window_strb_ce0_local;

assign window_strb_d0 = 4'd15;

assign window_strb_we0 = window_strb_we0_local;

assign window_user_address0 = zext_ln17_1_fu_162_p1;

assign window_user_ce0 = window_user_ce0_local;

assign window_user_d0 = 2'd0;

assign window_user_we0 = window_user_we0_local;

assign zext_ln17_1_fu_162_p1 = add_ln17_1_fu_156_p2;

assign zext_ln17_fu_152_p1 = ap_sig_allocacmp_indvars_iv_load;

endmodule //sobel_filter_sobel_filter_Pipeline_1
