[hls]
relative_roots=C:/F.A.L.C.O.N/Vitis_WS/Gaussian_Filter_IP
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=gaussian_filter/anonymous 
syn.directive.pipeline=gaussian_filter/anonymous 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=gaussian_filter/VITIS_LOOP_27_2  


