# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vivado_WS/Vector_Mult_Project/Vector_Mult_Project.srcs/sources_1/bd/Design_1/ip/Design_1_axi_mem_intercon_imp_auto_pc_0/Design_1_axi_mem_intercon_imp_auto_pc_0.xci
# IP: The module: 'Design_1_axi_mem_intercon_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_WS/Vector_Mult_Project/Vector_Mult_Project.gen/sources_1/bd/Design_1/ip/Design_1_axi_mem_intercon_imp_auto_pc_0/Design_1_axi_mem_intercon_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_1_axi_mem_intercon_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Vivado_WS/Vector_Mult_Project/Vector_Mult_Project.srcs/sources_1/bd/Design_1/ip/Design_1_axi_mem_intercon_imp_auto_pc_0/Design_1_axi_mem_intercon_imp_auto_pc_0.xci
# IP: The module: 'Design_1_axi_mem_intercon_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_WS/Vector_Mult_Project/Vector_Mult_Project.gen/sources_1/bd/Design_1/ip/Design_1_axi_mem_intercon_imp_auto_pc_0/Design_1_axi_mem_intercon_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_1_axi_mem_intercon_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
