-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Canny_Filter_Sobel_Filter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    Gaussian_to_Sobel_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    Gaussian_to_Sobel_empty_n : IN STD_LOGIC;
    Gaussian_to_Sobel_read : OUT STD_LOGIC;
    Gaussian_to_Sobel_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    Gaussian_to_Sobel_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    Sobel_to_Suppression_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    Sobel_to_Suppression_full_n : IN STD_LOGIC;
    Sobel_to_Suppression_write : OUT STD_LOGIC;
    Sobel_to_Suppression_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    Sobel_to_Suppression_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    Rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    Rows_empty_n : IN STD_LOGIC;
    Rows_read : OUT STD_LOGIC;
    Rows_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Rows_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    Cols_empty_n : IN STD_LOGIC;
    Cols_read : OUT STD_LOGIC;
    Cols_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Cols_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Rows_c1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    Rows_c1_full_n : IN STD_LOGIC;
    Rows_c1_write : OUT STD_LOGIC;
    Rows_c1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Rows_c1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Cols_c3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    Cols_c3_full_n : IN STD_LOGIC;
    Cols_c3_write : OUT STD_LOGIC;
    Cols_c3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Cols_c3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of Canny_Filter_Sobel_Filter is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal Rows_blk_n : STD_LOGIC;
    signal Cols_blk_n : STD_LOGIC;
    signal Rows_c1_blk_n : STD_LOGIC;
    signal Cols_c3_blk_n : STD_LOGIC;
    signal Cols_2_reg_127 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal smax_fu_97_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax_reg_132 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax1_fu_111_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax1_reg_137 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_78_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal bound_reg_152 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_start : STD_LOGIC;
    signal grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done : STD_LOGIC;
    signal grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_idle : STD_LOGIC;
    signal grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_ready : STD_LOGIC;
    signal grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_Gaussian_to_Sobel_read : STD_LOGIC;
    signal grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_Sobel_to_Suppression_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_Sobel_to_Suppression_write : STD_LOGIC;
    signal grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_78_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_78_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_63_fu_91_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_83_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_64_fu_105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_62_fu_87_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal grp_fu_78_p00 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_78_p10 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component Canny_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Gaussian_to_Sobel_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        Gaussian_to_Sobel_empty_n : IN STD_LOGIC;
        Gaussian_to_Sobel_read : OUT STD_LOGIC;
        Gaussian_to_Sobel_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        Gaussian_to_Sobel_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        Sobel_to_Suppression_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        Sobel_to_Suppression_full_n : IN STD_LOGIC;
        Sobel_to_Suppression_write : OUT STD_LOGIC;
        Sobel_to_Suppression_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        Sobel_to_Suppression_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        Cols_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        bound : IN STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component Canny_Filter_mul_31ns_31ns_62_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;



begin
    grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68 : component Canny_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_start,
        ap_done => grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done,
        ap_idle => grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_idle,
        ap_ready => grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_ready,
        Gaussian_to_Sobel_dout => Gaussian_to_Sobel_dout,
        Gaussian_to_Sobel_empty_n => Gaussian_to_Sobel_empty_n,
        Gaussian_to_Sobel_read => grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_Gaussian_to_Sobel_read,
        Gaussian_to_Sobel_num_data_valid => ap_const_lv4_0,
        Gaussian_to_Sobel_fifo_cap => ap_const_lv4_0,
        Sobel_to_Suppression_din => grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_Sobel_to_Suppression_din,
        Sobel_to_Suppression_full_n => Sobel_to_Suppression_full_n,
        Sobel_to_Suppression_write => grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_Sobel_to_Suppression_write,
        Sobel_to_Suppression_num_data_valid => ap_const_lv4_0,
        Sobel_to_Suppression_fifo_cap => ap_const_lv4_0,
        Cols_2 => Cols_2_reg_127,
        bound => bound_reg_152);

    mul_31ns_31ns_62_2_1_U44 : component Canny_Filter_mul_31ns_31ns_62_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        dout_WIDTH => 62)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_78_p0,
        din1 => grp_fu_78_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_78_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_ready = ap_const_logic_1)) then 
                    grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                Cols_2_reg_127 <= Cols_dout;
                smax1_reg_137 <= smax1_fu_111_p3;
                smax_reg_132 <= smax_fu_97_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                bound_reg_152 <= grp_fu_78_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    Cols_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, Cols_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Cols_blk_n <= Cols_empty_n;
        else 
            Cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Cols_c3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, Cols_c3_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Cols_c3_blk_n <= Cols_c3_full_n;
        else 
            Cols_c3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    Cols_c3_din <= Cols_dout;

    Cols_c3_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Cols_c3_write <= ap_const_logic_1;
        else 
            Cols_c3_write <= ap_const_logic_0;
        end if; 
    end process;


    Cols_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Cols_read <= ap_const_logic_1;
        else 
            Cols_read <= ap_const_logic_0;
        end if; 
    end process;

    Gaussian_to_Sobel_read <= grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_Gaussian_to_Sobel_read;

    Rows_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, Rows_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Rows_blk_n <= Rows_empty_n;
        else 
            Rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Rows_c1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, Rows_c1_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Rows_c1_blk_n <= Rows_c1_full_n;
        else 
            Rows_c1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    Rows_c1_din <= Rows_dout;

    Rows_c1_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Rows_c1_write <= ap_const_logic_1;
        else 
            Rows_c1_write <= ap_const_logic_0;
        end if; 
    end process;


    Rows_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Rows_read <= ap_const_logic_1;
        else 
            Rows_read <= ap_const_logic_0;
        end if; 
    end process;

    Sobel_to_Suppression_din <= grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_Sobel_to_Suppression_din;
    Sobel_to_Suppression_write <= grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_Sobel_to_Suppression_write;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done)
    begin
        if ((grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, Rows_empty_n, Cols_empty_n, Rows_c1_full_n, Cols_c3_full_n)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = Cols_c3_full_n) or (ap_const_logic_0 = Rows_c1_full_n) or (ap_const_logic_0 = Cols_empty_n) or (ap_const_logic_0 = Rows_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    empty_62_fu_87_p1 <= Rows_dout(31 - 1 downto 0);
    empty_63_fu_91_p2 <= "1" when (signed(Cols_dout) > signed(ap_const_lv32_0)) else "0";
    empty_64_fu_105_p2 <= "1" when (signed(Rows_dout) > signed(ap_const_lv32_0)) else "0";
    empty_fu_83_p1 <= Cols_dout(31 - 1 downto 0);
    grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_start <= grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_start_reg;
    grp_fu_78_p0 <= grp_fu_78_p00(31 - 1 downto 0);
    grp_fu_78_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax1_reg_137),62));
    grp_fu_78_p1 <= grp_fu_78_p10(31 - 1 downto 0);
    grp_fu_78_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax_reg_132),62));

    internal_ap_ready_assign_proc : process(grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_fu_68_ap_done = ap_const_logic_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    smax1_fu_111_p3 <= 
        empty_62_fu_87_p1 when (empty_64_fu_105_p2(0) = '1') else 
        ap_const_lv31_0;
    smax_fu_97_p3 <= 
        empty_fu_83_p1 when (empty_63_fu_91_p2(0) = '1') else 
        ap_const_lv31_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
