# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/F.A.L.C.O.N/Vitis_WS/Canny_Filter_IP/Canny_Filter_IP/hls/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/F.A.L.C.O.N/Vitis_WS/Canny_Filter_IP/Canny_Filter_IP/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/Canny_Filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/F.A.L.C.O.N/Vitis_WS/Canny_Filter_IP/Canny_Filter_IP/hls/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/F.A.L.C.O.N/Vitis_WS/Canny_Filter_IP/Canny_Filter_IP/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/Canny_Filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
