# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Design_1/Design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1 || ORIG_REF_NAME==Design_1} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_processing_system7_0_0/Design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_processing_system7_0_0 || ORIG_REF_NAME==Design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_Canny_Filter_0_0/Design_1_Canny_Filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_Canny_Filter_0_0 || ORIG_REF_NAME==Design_1_Canny_Filter_0_0} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_smartconnect_0_0/Design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_smartconnect_0_0 || ORIG_REF_NAME==Design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_axi_dma_0_0/Design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_axi_dma_0_0 || ORIG_REF_NAME==Design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_axi_interconnect_0_imp_xbar_0/Design_1_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==Design_1_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_axi_interconnect_0_0/Design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_axi_interconnect_0_0 || ORIG_REF_NAME==Design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_proc_sys_reset_0_0/Design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==Design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_axi_interconnect_0_imp_auto_pc_0/Design_1_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==Design_1_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_axi_interconnect_0_imp_auto_us_0/Design_1_axi_interconnect_0_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_axi_interconnect_0_imp_auto_us_0 || ORIG_REF_NAME==Design_1_axi_interconnect_0_imp_auto_us_0} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_axi_interconnect_0_imp_auto_pc_1/Design_1_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==Design_1_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/Design_1/ip/Design_1_axi_interconnect_0_imp_auto_us_1/Design_1_axi_interconnect_0_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Design_1_axi_interconnect_0_imp_auto_us_1 || ORIG_REF_NAME==Design_1_axi_interconnect_0_imp_auto_us_1} -quiet] -quiet

# XDC: c:/F.A.L.C.O.N/Vivado_WS/Canny_Filter_Project/Canny_Filter_Project.gen/sources_1/bd/Design_1/Design_1_ooc.xdc
