-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vector_mult is
generic (
    C_M_AXI_GMEM_A_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_A_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_A_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_A_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_A_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_A_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_A_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_A_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_B_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_B_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_B_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_B_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_B_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_B_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_B_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_B_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_C_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_C_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_C_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_C_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_C_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_C_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_C_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_C_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_A_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_A_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_A_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_GMEM_B_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_B_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_B_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_GMEM_C_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_C_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_C_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_gmem_A_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_A_AWREADY : IN STD_LOGIC;
    m_axi_gmem_A_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_A_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_ID_WIDTH-1 downto 0);
    m_axi_gmem_A_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_A_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_A_WVALID : OUT STD_LOGIC;
    m_axi_gmem_A_WREADY : IN STD_LOGIC;
    m_axi_gmem_A_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_DATA_WIDTH-1 downto 0);
    m_axi_gmem_A_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_A_WLAST : OUT STD_LOGIC;
    m_axi_gmem_A_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_ID_WIDTH-1 downto 0);
    m_axi_gmem_A_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_A_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_A_ARREADY : IN STD_LOGIC;
    m_axi_gmem_A_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_A_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_ID_WIDTH-1 downto 0);
    m_axi_gmem_A_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_A_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_A_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_A_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_A_RVALID : IN STD_LOGIC;
    m_axi_gmem_A_RREADY : OUT STD_LOGIC;
    m_axi_gmem_A_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_DATA_WIDTH-1 downto 0);
    m_axi_gmem_A_RLAST : IN STD_LOGIC;
    m_axi_gmem_A_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_ID_WIDTH-1 downto 0);
    m_axi_gmem_A_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_A_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_BVALID : IN STD_LOGIC;
    m_axi_gmem_A_BREADY : OUT STD_LOGIC;
    m_axi_gmem_A_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_A_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_ID_WIDTH-1 downto 0);
    m_axi_gmem_A_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_A_BUSER_WIDTH-1 downto 0);
    m_axi_gmem_B_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_B_AWREADY : IN STD_LOGIC;
    m_axi_gmem_B_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_B_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_ID_WIDTH-1 downto 0);
    m_axi_gmem_B_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_B_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_B_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_B_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_B_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_B_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_B_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_B_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_B_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_B_WVALID : OUT STD_LOGIC;
    m_axi_gmem_B_WREADY : IN STD_LOGIC;
    m_axi_gmem_B_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_DATA_WIDTH-1 downto 0);
    m_axi_gmem_B_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_B_WLAST : OUT STD_LOGIC;
    m_axi_gmem_B_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_ID_WIDTH-1 downto 0);
    m_axi_gmem_B_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_B_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_B_ARREADY : IN STD_LOGIC;
    m_axi_gmem_B_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_B_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_ID_WIDTH-1 downto 0);
    m_axi_gmem_B_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_B_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_B_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_B_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_B_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_B_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_B_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_B_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_B_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_B_RVALID : IN STD_LOGIC;
    m_axi_gmem_B_RREADY : OUT STD_LOGIC;
    m_axi_gmem_B_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_DATA_WIDTH-1 downto 0);
    m_axi_gmem_B_RLAST : IN STD_LOGIC;
    m_axi_gmem_B_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_ID_WIDTH-1 downto 0);
    m_axi_gmem_B_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_B_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_B_BVALID : IN STD_LOGIC;
    m_axi_gmem_B_BREADY : OUT STD_LOGIC;
    m_axi_gmem_B_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_B_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_ID_WIDTH-1 downto 0);
    m_axi_gmem_B_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_B_BUSER_WIDTH-1 downto 0);
    m_axi_gmem_C_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_C_AWREADY : IN STD_LOGIC;
    m_axi_gmem_C_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_C_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_ID_WIDTH-1 downto 0);
    m_axi_gmem_C_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_C_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_C_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_C_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_C_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_C_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_C_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_C_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_C_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_C_WVALID : OUT STD_LOGIC;
    m_axi_gmem_C_WREADY : IN STD_LOGIC;
    m_axi_gmem_C_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_DATA_WIDTH-1 downto 0);
    m_axi_gmem_C_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_C_WLAST : OUT STD_LOGIC;
    m_axi_gmem_C_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_ID_WIDTH-1 downto 0);
    m_axi_gmem_C_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_C_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_C_ARREADY : IN STD_LOGIC;
    m_axi_gmem_C_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_C_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_ID_WIDTH-1 downto 0);
    m_axi_gmem_C_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_C_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_C_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_C_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_C_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_C_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_C_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_C_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_C_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_C_RVALID : IN STD_LOGIC;
    m_axi_gmem_C_RREADY : OUT STD_LOGIC;
    m_axi_gmem_C_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_DATA_WIDTH-1 downto 0);
    m_axi_gmem_C_RLAST : IN STD_LOGIC;
    m_axi_gmem_C_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_ID_WIDTH-1 downto 0);
    m_axi_gmem_C_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_C_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_C_BVALID : IN STD_LOGIC;
    m_axi_gmem_C_BREADY : OUT STD_LOGIC;
    m_axi_gmem_C_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_C_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_ID_WIDTH-1 downto 0);
    m_axi_gmem_C_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_C_BUSER_WIDTH-1 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of vector_mult is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "vector_mult_vector_mult,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=2946,HLS_SYN_LUT=2945,HLS_VERSION=2026_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal gmem_A_0_AWREADY : STD_LOGIC;
    signal gmem_A_0_WREADY : STD_LOGIC;
    signal gmem_A_0_ARVALID : STD_LOGIC;
    signal gmem_A_0_ARREADY : STD_LOGIC;
    signal gmem_A_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_A_0_RVALID : STD_LOGIC;
    signal gmem_A_0_RREADY : STD_LOGIC;
    signal gmem_A_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_A_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_A_0_BVALID : STD_LOGIC;
    signal gmem_B_0_AWREADY : STD_LOGIC;
    signal gmem_B_0_WREADY : STD_LOGIC;
    signal gmem_B_0_ARVALID : STD_LOGIC;
    signal gmem_B_0_ARREADY : STD_LOGIC;
    signal gmem_B_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_B_0_RVALID : STD_LOGIC;
    signal gmem_B_0_RREADY : STD_LOGIC;
    signal gmem_B_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_B_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_B_0_BVALID : STD_LOGIC;
    signal gmem_C_0_AWVALID : STD_LOGIC;
    signal gmem_C_0_AWREADY : STD_LOGIC;
    signal gmem_C_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_C_0_WVALID : STD_LOGIC;
    signal gmem_C_0_WREADY : STD_LOGIC;
    signal gmem_C_0_ARREADY : STD_LOGIC;
    signal gmem_C_0_RVALID : STD_LOGIC;
    signal gmem_C_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_C_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_C_0_BVALID : STD_LOGIC;
    signal gmem_C_0_BREADY : STD_LOGIC;
    signal first_iter_0_reg_181 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_io_grp1 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_grp1 : BOOLEAN;
    signal first_iter_0_reg_181_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state12_io_grp1 : BOOLEAN;
    signal icmp_ln20_2_reg_352 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state18_pp0_stage0_iter17_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln20_1_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal A : STD_LOGIC_VECTOR (63 downto 0);
    signal B : STD_LOGIC_VECTOR (63 downto 0);
    signal C : STD_LOGIC_VECTOR (63 downto 0);
    signal length_r : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_A_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem_A_blk_n_R : STD_LOGIC;
    signal gmem_B_blk_n_AR : STD_LOGIC;
    signal gmem_B_blk_n_R : STD_LOGIC;
    signal gmem_C_blk_n_AW : STD_LOGIC;
    signal gmem_C_blk_n_W : STD_LOGIC;
    signal gmem_C_blk_n_B : STD_LOGIC;
    signal first_iter_0_reg_181_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal first_iter_0_reg_181_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_181_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_181_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_181_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_181_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_181_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_181_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_181_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal B_read_reg_326 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal A_read_reg_331 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_207_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_reg_336 : STD_LOGIC_VECTOR (30 downto 0);
    signal gmem_C_addr_reg_341 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_C_addr_reg_341_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_C_addr_reg_341_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_C_addr_reg_341_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_C_addr_reg_341_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_C_addr_reg_341_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_C_addr_reg_341_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_C_addr_reg_341_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_C_addr_reg_341_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_C_addr_reg_341_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_C_addr_reg_341_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln20_1_reg_348 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_2_reg_352_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln20_fu_294_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_362 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_362_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_362_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_362_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_362_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_362_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_362_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_362_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_362_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_362_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_A_addr_read_reg_375 : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_B_addr_read_reg_380 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_193_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_reg_385 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal sext_ln20_2_fu_225_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln20_fu_283_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln20_1_fu_308_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal i_fu_112 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln20_fu_253_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln20_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln20_fu_203_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln20_2_fu_215_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln20_1_fu_243_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln21_fu_259_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln_fu_274_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln20_1_fu_299_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_193_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_847 : BOOLEAN;
    signal ap_condition_725 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component vector_mult_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component vector_mult_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        A : OUT STD_LOGIC_VECTOR (63 downto 0);
        B : OUT STD_LOGIC_VECTOR (63 downto 0);
        C : OUT STD_LOGIC_VECTOR (63 downto 0);
        length_r : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component vector_mult_gmem_A_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component vector_mult_gmem_B_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component vector_mult_gmem_C_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component vector_mult_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component vector_mult_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        A => A,
        B => B,
        C => C,
        length_r => length_r,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    gmem_A_m_axi_U : component vector_mult_gmem_A_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_A_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_A_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_A_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_A_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_A_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_A_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_A_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_A_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_A_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_A_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_A_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_gmem_A_AWVALID,
        AWREADY => m_axi_gmem_A_AWREADY,
        AWADDR => m_axi_gmem_A_AWADDR,
        AWID => m_axi_gmem_A_AWID,
        AWLEN => m_axi_gmem_A_AWLEN,
        AWSIZE => m_axi_gmem_A_AWSIZE,
        AWBURST => m_axi_gmem_A_AWBURST,
        AWLOCK => m_axi_gmem_A_AWLOCK,
        AWCACHE => m_axi_gmem_A_AWCACHE,
        AWPROT => m_axi_gmem_A_AWPROT,
        AWQOS => m_axi_gmem_A_AWQOS,
        AWREGION => m_axi_gmem_A_AWREGION,
        AWUSER => m_axi_gmem_A_AWUSER,
        WVALID => m_axi_gmem_A_WVALID,
        WREADY => m_axi_gmem_A_WREADY,
        WDATA => m_axi_gmem_A_WDATA,
        WSTRB => m_axi_gmem_A_WSTRB,
        WLAST => m_axi_gmem_A_WLAST,
        WID => m_axi_gmem_A_WID,
        WUSER => m_axi_gmem_A_WUSER,
        ARVALID => m_axi_gmem_A_ARVALID,
        ARREADY => m_axi_gmem_A_ARREADY,
        ARADDR => m_axi_gmem_A_ARADDR,
        ARID => m_axi_gmem_A_ARID,
        ARLEN => m_axi_gmem_A_ARLEN,
        ARSIZE => m_axi_gmem_A_ARSIZE,
        ARBURST => m_axi_gmem_A_ARBURST,
        ARLOCK => m_axi_gmem_A_ARLOCK,
        ARCACHE => m_axi_gmem_A_ARCACHE,
        ARPROT => m_axi_gmem_A_ARPROT,
        ARQOS => m_axi_gmem_A_ARQOS,
        ARREGION => m_axi_gmem_A_ARREGION,
        ARUSER => m_axi_gmem_A_ARUSER,
        RVALID => m_axi_gmem_A_RVALID,
        RREADY => m_axi_gmem_A_RREADY,
        RDATA => m_axi_gmem_A_RDATA,
        RLAST => m_axi_gmem_A_RLAST,
        RID => m_axi_gmem_A_RID,
        RUSER => m_axi_gmem_A_RUSER,
        RRESP => m_axi_gmem_A_RRESP,
        BVALID => m_axi_gmem_A_BVALID,
        BREADY => m_axi_gmem_A_BREADY,
        BRESP => m_axi_gmem_A_BRESP,
        BID => m_axi_gmem_A_BID,
        BUSER => m_axi_gmem_A_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gmem_A_0_ARVALID,
        I_CH0_ARREADY => gmem_A_0_ARREADY,
        I_CH0_ARADDR => sext_ln20_fu_283_p1,
        I_CH0_ARLEN => gmem_A_0_ARLEN,
        I_CH0_RVALID => gmem_A_0_RVALID,
        I_CH0_RREADY => gmem_A_0_RREADY,
        I_CH0_RDATA => gmem_A_0_RDATA,
        I_CH0_RFIFONUM => gmem_A_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => gmem_A_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => gmem_A_0_WREADY,
        I_CH0_WDATA => ap_const_lv32_0,
        I_CH0_WSTRB => ap_const_lv4_0,
        I_CH0_BVALID => gmem_A_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    gmem_B_m_axi_U : component vector_mult_gmem_B_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_B_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_B_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_B_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_B_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_B_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_B_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_B_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_B_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_B_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_B_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_B_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_gmem_B_AWVALID,
        AWREADY => m_axi_gmem_B_AWREADY,
        AWADDR => m_axi_gmem_B_AWADDR,
        AWID => m_axi_gmem_B_AWID,
        AWLEN => m_axi_gmem_B_AWLEN,
        AWSIZE => m_axi_gmem_B_AWSIZE,
        AWBURST => m_axi_gmem_B_AWBURST,
        AWLOCK => m_axi_gmem_B_AWLOCK,
        AWCACHE => m_axi_gmem_B_AWCACHE,
        AWPROT => m_axi_gmem_B_AWPROT,
        AWQOS => m_axi_gmem_B_AWQOS,
        AWREGION => m_axi_gmem_B_AWREGION,
        AWUSER => m_axi_gmem_B_AWUSER,
        WVALID => m_axi_gmem_B_WVALID,
        WREADY => m_axi_gmem_B_WREADY,
        WDATA => m_axi_gmem_B_WDATA,
        WSTRB => m_axi_gmem_B_WSTRB,
        WLAST => m_axi_gmem_B_WLAST,
        WID => m_axi_gmem_B_WID,
        WUSER => m_axi_gmem_B_WUSER,
        ARVALID => m_axi_gmem_B_ARVALID,
        ARREADY => m_axi_gmem_B_ARREADY,
        ARADDR => m_axi_gmem_B_ARADDR,
        ARID => m_axi_gmem_B_ARID,
        ARLEN => m_axi_gmem_B_ARLEN,
        ARSIZE => m_axi_gmem_B_ARSIZE,
        ARBURST => m_axi_gmem_B_ARBURST,
        ARLOCK => m_axi_gmem_B_ARLOCK,
        ARCACHE => m_axi_gmem_B_ARCACHE,
        ARPROT => m_axi_gmem_B_ARPROT,
        ARQOS => m_axi_gmem_B_ARQOS,
        ARREGION => m_axi_gmem_B_ARREGION,
        ARUSER => m_axi_gmem_B_ARUSER,
        RVALID => m_axi_gmem_B_RVALID,
        RREADY => m_axi_gmem_B_RREADY,
        RDATA => m_axi_gmem_B_RDATA,
        RLAST => m_axi_gmem_B_RLAST,
        RID => m_axi_gmem_B_RID,
        RUSER => m_axi_gmem_B_RUSER,
        RRESP => m_axi_gmem_B_RRESP,
        BVALID => m_axi_gmem_B_BVALID,
        BREADY => m_axi_gmem_B_BREADY,
        BRESP => m_axi_gmem_B_BRESP,
        BID => m_axi_gmem_B_BID,
        BUSER => m_axi_gmem_B_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gmem_B_0_ARVALID,
        I_CH0_ARREADY => gmem_B_0_ARREADY,
        I_CH0_ARADDR => sext_ln20_1_fu_308_p1,
        I_CH0_ARLEN => gmem_B_0_ARLEN,
        I_CH0_RVALID => gmem_B_0_RVALID,
        I_CH0_RREADY => gmem_B_0_RREADY,
        I_CH0_RDATA => gmem_B_0_RDATA,
        I_CH0_RFIFONUM => gmem_B_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => gmem_B_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => gmem_B_0_WREADY,
        I_CH0_WDATA => ap_const_lv32_0,
        I_CH0_WSTRB => ap_const_lv4_0,
        I_CH0_BVALID => gmem_B_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    gmem_C_m_axi_U : component vector_mult_gmem_C_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 4,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_C_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_C_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_C_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_C_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_C_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_C_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_C_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_C_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_C_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_C_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_C_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 0,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_C_AWVALID,
        AWREADY => m_axi_gmem_C_AWREADY,
        AWADDR => m_axi_gmem_C_AWADDR,
        AWID => m_axi_gmem_C_AWID,
        AWLEN => m_axi_gmem_C_AWLEN,
        AWSIZE => m_axi_gmem_C_AWSIZE,
        AWBURST => m_axi_gmem_C_AWBURST,
        AWLOCK => m_axi_gmem_C_AWLOCK,
        AWCACHE => m_axi_gmem_C_AWCACHE,
        AWPROT => m_axi_gmem_C_AWPROT,
        AWQOS => m_axi_gmem_C_AWQOS,
        AWREGION => m_axi_gmem_C_AWREGION,
        AWUSER => m_axi_gmem_C_AWUSER,
        WVALID => m_axi_gmem_C_WVALID,
        WREADY => m_axi_gmem_C_WREADY,
        WDATA => m_axi_gmem_C_WDATA,
        WSTRB => m_axi_gmem_C_WSTRB,
        WLAST => m_axi_gmem_C_WLAST,
        WID => m_axi_gmem_C_WID,
        WUSER => m_axi_gmem_C_WUSER,
        ARVALID => m_axi_gmem_C_ARVALID,
        ARREADY => m_axi_gmem_C_ARREADY,
        ARADDR => m_axi_gmem_C_ARADDR,
        ARID => m_axi_gmem_C_ARID,
        ARLEN => m_axi_gmem_C_ARLEN,
        ARSIZE => m_axi_gmem_C_ARSIZE,
        ARBURST => m_axi_gmem_C_ARBURST,
        ARLOCK => m_axi_gmem_C_ARLOCK,
        ARCACHE => m_axi_gmem_C_ARCACHE,
        ARPROT => m_axi_gmem_C_ARPROT,
        ARQOS => m_axi_gmem_C_ARQOS,
        ARREGION => m_axi_gmem_C_ARREGION,
        ARUSER => m_axi_gmem_C_ARUSER,
        RVALID => m_axi_gmem_C_RVALID,
        RREADY => m_axi_gmem_C_RREADY,
        RDATA => m_axi_gmem_C_RDATA,
        RLAST => m_axi_gmem_C_RLAST,
        RID => m_axi_gmem_C_RID,
        RUSER => m_axi_gmem_C_RUSER,
        RRESP => m_axi_gmem_C_RRESP,
        BVALID => m_axi_gmem_C_BVALID,
        BREADY => m_axi_gmem_C_BREADY,
        BRESP => m_axi_gmem_C_BRESP,
        BID => m_axi_gmem_C_BID,
        BUSER => m_axi_gmem_C_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => ap_const_logic_0,
        I_CH0_ARREADY => gmem_C_0_ARREADY,
        I_CH0_ARADDR => ap_const_lv64_0,
        I_CH0_ARLEN => ap_const_lv32_0,
        I_CH0_RVALID => gmem_C_0_RVALID,
        I_CH0_RREADY => ap_const_logic_0,
        I_CH0_RDATA => gmem_C_0_RDATA,
        I_CH0_RFIFONUM => gmem_C_0_RFIFONUM,
        I_CH0_AWVALID => gmem_C_0_AWVALID,
        I_CH0_AWREADY => gmem_C_0_AWREADY,
        I_CH0_AWADDR => gmem_C_addr_reg_341_pp0_iter10_reg,
        I_CH0_AWLEN => gmem_C_0_AWLEN,
        I_CH0_WVALID => gmem_C_0_WVALID,
        I_CH0_WREADY => gmem_C_0_WREADY,
        I_CH0_WDATA => result_reg_385,
        I_CH0_WSTRB => ap_const_lv4_F,
        I_CH0_BVALID => gmem_C_0_BVALID,
        I_CH0_BREADY => gmem_C_0_BREADY);

    mul_32s_32s_32_2_1_U1 : component vector_mult_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => gmem_B_addr_read_reg_380,
        din1 => gmem_A_addr_read_reg_375,
        ce => grp_fu_193_ce,
        dout => grp_fu_193_p2);

    flow_control_loop_pipe_U : component vector_mult_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    first_iter_0_reg_181_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    first_iter_0_reg_181 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_condition_847)) then 
                    first_iter_0_reg_181 <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;

    i_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_725)) then
                if ((icmp_ln20_1_fu_247_p2 = ap_const_lv1_1)) then 
                    i_fu_112 <= add_ln20_fu_253_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_112 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                A_read_reg_331 <= A;
                B_read_reg_326 <= B;
                gmem_C_addr_reg_341 <= sext_ln20_2_fu_225_p1;
                gmem_C_addr_reg_341_pp0_iter1_reg <= gmem_C_addr_reg_341;
                    zext_ln20_reg_362(30 downto 0) <= zext_ln20_fu_294_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                first_iter_0_reg_181_pp0_iter10_reg <= first_iter_0_reg_181_pp0_iter9_reg;
                first_iter_0_reg_181_pp0_iter2_reg <= first_iter_0_reg_181_pp0_iter1_reg;
                first_iter_0_reg_181_pp0_iter3_reg <= first_iter_0_reg_181_pp0_iter2_reg;
                first_iter_0_reg_181_pp0_iter4_reg <= first_iter_0_reg_181_pp0_iter3_reg;
                first_iter_0_reg_181_pp0_iter5_reg <= first_iter_0_reg_181_pp0_iter4_reg;
                first_iter_0_reg_181_pp0_iter6_reg <= first_iter_0_reg_181_pp0_iter5_reg;
                first_iter_0_reg_181_pp0_iter7_reg <= first_iter_0_reg_181_pp0_iter6_reg;
                first_iter_0_reg_181_pp0_iter8_reg <= first_iter_0_reg_181_pp0_iter7_reg;
                first_iter_0_reg_181_pp0_iter9_reg <= first_iter_0_reg_181_pp0_iter8_reg;
                icmp_ln20_2_reg_352_pp0_iter10_reg <= icmp_ln20_2_reg_352_pp0_iter9_reg;
                icmp_ln20_2_reg_352_pp0_iter11_reg <= icmp_ln20_2_reg_352_pp0_iter10_reg;
                icmp_ln20_2_reg_352_pp0_iter12_reg <= icmp_ln20_2_reg_352_pp0_iter11_reg;
                icmp_ln20_2_reg_352_pp0_iter13_reg <= icmp_ln20_2_reg_352_pp0_iter12_reg;
                icmp_ln20_2_reg_352_pp0_iter14_reg <= icmp_ln20_2_reg_352_pp0_iter13_reg;
                icmp_ln20_2_reg_352_pp0_iter15_reg <= icmp_ln20_2_reg_352_pp0_iter14_reg;
                icmp_ln20_2_reg_352_pp0_iter16_reg <= icmp_ln20_2_reg_352_pp0_iter15_reg;
                icmp_ln20_2_reg_352_pp0_iter2_reg <= icmp_ln20_2_reg_352_pp0_iter1_reg;
                icmp_ln20_2_reg_352_pp0_iter3_reg <= icmp_ln20_2_reg_352_pp0_iter2_reg;
                icmp_ln20_2_reg_352_pp0_iter4_reg <= icmp_ln20_2_reg_352_pp0_iter3_reg;
                icmp_ln20_2_reg_352_pp0_iter5_reg <= icmp_ln20_2_reg_352_pp0_iter4_reg;
                icmp_ln20_2_reg_352_pp0_iter6_reg <= icmp_ln20_2_reg_352_pp0_iter5_reg;
                icmp_ln20_2_reg_352_pp0_iter7_reg <= icmp_ln20_2_reg_352_pp0_iter6_reg;
                icmp_ln20_2_reg_352_pp0_iter8_reg <= icmp_ln20_2_reg_352_pp0_iter7_reg;
                icmp_ln20_2_reg_352_pp0_iter9_reg <= icmp_ln20_2_reg_352_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                empty_reg_336 <= empty_fu_207_p3;
                first_iter_0_reg_181_pp0_iter1_reg <= first_iter_0_reg_181;
                icmp_ln20_1_reg_348 <= icmp_ln20_1_fu_247_p2;
                icmp_ln20_2_reg_352 <= icmp_ln20_2_fu_263_p2;
                icmp_ln20_2_reg_352_pp0_iter1_reg <= icmp_ln20_2_reg_352;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                gmem_A_addr_read_reg_375 <= gmem_A_0_RDATA;
                gmem_B_addr_read_reg_380 <= gmem_B_0_RDATA;
                gmem_C_addr_reg_341_pp0_iter10_reg <= gmem_C_addr_reg_341_pp0_iter9_reg;
                gmem_C_addr_reg_341_pp0_iter2_reg <= gmem_C_addr_reg_341_pp0_iter1_reg;
                gmem_C_addr_reg_341_pp0_iter3_reg <= gmem_C_addr_reg_341_pp0_iter2_reg;
                gmem_C_addr_reg_341_pp0_iter4_reg <= gmem_C_addr_reg_341_pp0_iter3_reg;
                gmem_C_addr_reg_341_pp0_iter5_reg <= gmem_C_addr_reg_341_pp0_iter4_reg;
                gmem_C_addr_reg_341_pp0_iter6_reg <= gmem_C_addr_reg_341_pp0_iter5_reg;
                gmem_C_addr_reg_341_pp0_iter7_reg <= gmem_C_addr_reg_341_pp0_iter6_reg;
                gmem_C_addr_reg_341_pp0_iter8_reg <= gmem_C_addr_reg_341_pp0_iter7_reg;
                gmem_C_addr_reg_341_pp0_iter9_reg <= gmem_C_addr_reg_341_pp0_iter8_reg;
                result_reg_385 <= grp_fu_193_p2;
                    zext_ln20_reg_362_pp0_iter10_reg(30 downto 0) <= zext_ln20_reg_362_pp0_iter9_reg(30 downto 0);
                    zext_ln20_reg_362_pp0_iter2_reg(30 downto 0) <= zext_ln20_reg_362(30 downto 0);
                    zext_ln20_reg_362_pp0_iter3_reg(30 downto 0) <= zext_ln20_reg_362_pp0_iter2_reg(30 downto 0);
                    zext_ln20_reg_362_pp0_iter4_reg(30 downto 0) <= zext_ln20_reg_362_pp0_iter3_reg(30 downto 0);
                    zext_ln20_reg_362_pp0_iter5_reg(30 downto 0) <= zext_ln20_reg_362_pp0_iter4_reg(30 downto 0);
                    zext_ln20_reg_362_pp0_iter6_reg(30 downto 0) <= zext_ln20_reg_362_pp0_iter5_reg(30 downto 0);
                    zext_ln20_reg_362_pp0_iter7_reg(30 downto 0) <= zext_ln20_reg_362_pp0_iter6_reg(30 downto 0);
                    zext_ln20_reg_362_pp0_iter8_reg(30 downto 0) <= zext_ln20_reg_362_pp0_iter7_reg(30 downto 0);
                    zext_ln20_reg_362_pp0_iter9_reg(30 downto 0) <= zext_ln20_reg_362_pp0_iter8_reg(30 downto 0);
            end if;
        end if;
    end process;
    zext_ln20_reg_362(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln20_reg_362_pp0_iter2_reg(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln20_reg_362_pp0_iter3_reg(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln20_reg_362_pp0_iter4_reg(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln20_reg_362_pp0_iter5_reg(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln20_reg_362_pp0_iter6_reg(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln20_reg_362_pp0_iter7_reg(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln20_reg_362_pp0_iter8_reg(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln20_reg_362_pp0_iter9_reg(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln20_reg_362_pp0_iter10_reg(63 downto 31) <= "000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln20_fu_253_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter17, ap_block_state10_pp0_stage0_iter9_grp1, ap_block_state18_pp0_stage0_iter17_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state18_pp0_stage0_iter17_grp1)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9_grp1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter17, gmem_C_0_WREADY, ap_block_state2_io_grp1, ap_block_state10_pp0_stage0_iter9_grp1, ap_block_state12_io_grp1, ap_block_state18_pp0_stage0_iter17_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state18_pp0_stage0_iter17_grp1)) or ((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (gmem_C_0_WREADY = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_io_grp1)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io_grp1)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter17, gmem_C_0_WREADY, ap_block_state2_io_grp1, ap_block_state10_pp0_stage0_iter9_grp1, ap_block_state12_io_grp1, ap_block_state18_pp0_stage0_iter17_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state18_pp0_stage0_iter17_grp1)) or ((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (gmem_C_0_WREADY = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_io_grp1)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter17, gmem_C_0_WREADY, ap_block_state2_io_grp1, ap_block_state10_pp0_stage0_iter9_grp1, ap_block_state12_io_grp1, ap_block_state18_pp0_stage0_iter17_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state18_pp0_stage0_iter17_grp1)) or ((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (gmem_C_0_WREADY = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_io_grp1)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io_grp1)));
    end process;


    ap_block_state10_pp0_stage0_iter9_grp1_assign_proc : process(gmem_A_0_RVALID, gmem_B_0_RVALID)
    begin
                ap_block_state10_pp0_stage0_iter9_grp1 <= ((gmem_B_0_RVALID = ap_const_logic_0) or (gmem_A_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_state12_io_grp1_assign_proc : process(gmem_C_0_AWREADY, first_iter_0_reg_181_pp0_iter10_reg)
    begin
                ap_block_state12_io_grp1 <= ((first_iter_0_reg_181_pp0_iter10_reg = ap_const_lv1_1) and (gmem_C_0_AWREADY = ap_const_logic_0));
    end process;


    ap_block_state18_pp0_stage0_iter17_grp1_assign_proc : process(gmem_C_0_BVALID, icmp_ln20_2_reg_352_pp0_iter16_reg)
    begin
                ap_block_state18_pp0_stage0_iter17_grp1 <= ((icmp_ln20_2_reg_352_pp0_iter16_reg = ap_const_lv1_0) and (gmem_C_0_BVALID = ap_const_logic_0));
    end process;


    ap_block_state2_io_grp1_assign_proc : process(gmem_A_0_ARREADY, gmem_B_0_ARREADY, first_iter_0_reg_181)
    begin
                ap_block_state2_io_grp1 <= (((first_iter_0_reg_181 = ap_const_lv1_1) and (gmem_B_0_ARREADY = ap_const_logic_0)) or ((first_iter_0_reg_181 = ap_const_lv1_1) and (gmem_A_0_ARREADY = ap_const_logic_0)));
    end process;


    ap_condition_725_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_725 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_847_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln20_1_reg_348)
    begin
                ap_condition_847 <= ((icmp_ln20_1_reg_348 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln20_1_fu_247_p2)
    begin
        if (((icmp_ln20_1_fu_247_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17)
    begin
        if (((ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, i_fu_112)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_112;
        end if; 
    end process;

    empty_fu_207_p3 <= 
        trunc_ln20_fu_203_p1 when (icmp_ln20_fu_197_p2(0) = '1') else 
        ap_const_lv31_0;
    gmem_A_0_ARLEN <= zext_ln20_fu_294_p1(32 - 1 downto 0);

    gmem_A_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, first_iter_0_reg_181, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_iter_0_reg_181 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_A_0_ARVALID <= ap_const_logic_1;
        else 
            gmem_A_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_A_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            gmem_A_0_RREADY <= ap_const_logic_1;
        else 
            gmem_A_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_A_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, first_iter_0_reg_181, m_axi_gmem_A_ARREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_iter_0_reg_181 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_A_blk_n_AR <= m_axi_gmem_A_ARREADY;
        else 
            gmem_A_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_A_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem_A_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem_A_blk_n_R <= m_axi_gmem_A_RVALID;
        else 
            gmem_A_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    gmem_B_0_ARLEN <= zext_ln20_fu_294_p1(32 - 1 downto 0);

    gmem_B_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, first_iter_0_reg_181, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_iter_0_reg_181 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_B_0_ARVALID <= ap_const_logic_1;
        else 
            gmem_B_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_B_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            gmem_B_0_RREADY <= ap_const_logic_1;
        else 
            gmem_B_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_B_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, first_iter_0_reg_181, m_axi_gmem_B_ARREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (first_iter_0_reg_181 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_B_blk_n_AR <= m_axi_gmem_B_ARREADY;
        else 
            gmem_B_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_B_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem_B_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem_B_blk_n_R <= m_axi_gmem_B_RVALID;
        else 
            gmem_B_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    gmem_C_0_AWLEN <= zext_ln20_reg_362_pp0_iter10_reg(32 - 1 downto 0);

    gmem_C_0_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter11, first_iter_0_reg_181_pp0_iter10_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (first_iter_0_reg_181_pp0_iter10_reg = ap_const_lv1_1))) then 
            gmem_C_0_AWVALID <= ap_const_logic_1;
        else 
            gmem_C_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_C_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter17, icmp_ln20_2_reg_352_pp0_iter16_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln20_2_reg_352_pp0_iter16_reg = ap_const_lv1_0))) then 
            gmem_C_0_BREADY <= ap_const_logic_1;
        else 
            gmem_C_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_C_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            gmem_C_0_WVALID <= ap_const_logic_1;
        else 
            gmem_C_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_C_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter11, first_iter_0_reg_181_pp0_iter10_reg, m_axi_gmem_C_AWREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (first_iter_0_reg_181_pp0_iter10_reg = ap_const_lv1_1))) then 
            gmem_C_blk_n_AW <= m_axi_gmem_C_AWREADY;
        else 
            gmem_C_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_C_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter17, icmp_ln20_2_reg_352_pp0_iter16_reg, m_axi_gmem_C_BVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln20_2_reg_352_pp0_iter16_reg = ap_const_lv1_0))) then 
            gmem_C_blk_n_B <= m_axi_gmem_C_BVALID;
        else 
            gmem_C_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem_C_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter12, m_axi_gmem_C_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem_C_blk_n_W <= m_axi_gmem_C_WREADY;
        else 
            gmem_C_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_193_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_193_ce <= ap_const_logic_1;
        else 
            grp_fu_193_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln20_1_fu_247_p2 <= "1" when (signed(zext_ln20_1_fu_243_p1) < signed(length_r)) else "0";
    icmp_ln20_2_fu_263_p2 <= "1" when (signed(zext_ln21_fu_259_p1) < signed(length_r)) else "0";
    icmp_ln20_fu_197_p2 <= "1" when (signed(length_r) > signed(ap_const_lv32_0)) else "0";
        sext_ln20_1_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln20_1_fu_299_p4),64));

        sext_ln20_2_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln20_2_fu_215_p4),64));

        sext_ln20_fu_283_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_274_p4),64));

    trunc_ln20_1_fu_299_p4 <= B_read_reg_326(63 downto 2);
    trunc_ln20_2_fu_215_p4 <= C(63 downto 2);
    trunc_ln20_fu_203_p1 <= length_r(31 - 1 downto 0);
    trunc_ln_fu_274_p4 <= A_read_reg_331(63 downto 2);
    zext_ln20_1_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_load),32));
    zext_ln20_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_336),64));
    zext_ln21_fu_259_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_fu_253_p2),32));
end behav;
