-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Canny_Filter_Hysteresis_Filter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Suppression_to_Hysteresis_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    Suppression_to_Hysteresis_empty_n : IN STD_LOGIC;
    Suppression_to_Hysteresis_read : OUT STD_LOGIC;
    Suppression_to_Hysteresis_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    Suppression_to_Hysteresis_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    Output_Stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    Output_Stream_TVALID : OUT STD_LOGIC;
    Output_Stream_TREADY : IN STD_LOGIC;
    Output_Stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    Output_Stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    Output_Stream_TUSER : OUT STD_LOGIC_VECTOR (2 downto 0);
    Output_Stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    Output_Stream_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    Output_Stream_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0);
    Rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    Rows_empty_n : IN STD_LOGIC;
    Rows_read : OUT STD_LOGIC;
    Rows_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Rows_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    Cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    Cols_empty_n : IN STD_LOGIC;
    Cols_read : OUT STD_LOGIC;
    Cols_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    Cols_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    High_Threshold_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    High_Threshold_empty_n : IN STD_LOGIC;
    High_Threshold_read : OUT STD_LOGIC;
    High_Threshold_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    High_Threshold_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    Low_Threshold_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    Low_Threshold_empty_n : IN STD_LOGIC;
    Low_Threshold_read : OUT STD_LOGIC;
    Low_Threshold_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    Low_Threshold_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of Canny_Filter_Hysteresis_Filter is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal Rows_blk_n : STD_LOGIC;
    signal Cols_blk_n : STD_LOGIC;
    signal High_Threshold_blk_n : STD_LOGIC;
    signal Low_Threshold_blk_n : STD_LOGIC;
    signal Low_Threshold_1_reg_171 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal High_Threshold_1_reg_176 : STD_LOGIC_VECTOR (31 downto 0);
    signal Cols_3_reg_181 : STD_LOGIC_VECTOR (31 downto 0);
    signal Rows_3_reg_187 : STD_LOGIC_VECTOR (31 downto 0);
    signal smax_fu_129_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax_reg_192 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax1_fu_143_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax1_reg_197 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln70_fu_159_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln70_reg_212 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln70_1_fu_165_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln70_1_reg_217 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_110_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal bound_reg_222 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start : STD_LOGIC;
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_done : STD_LOGIC;
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_idle : STD_LOGIC;
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_ready : STD_LOGIC;
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Suppression_to_Hysteresis_read : STD_LOGIC;
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TREADY : STD_LOGIC;
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID : STD_LOGIC;
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TUSER : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TID : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDEST : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal Output_Stream_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Output_Stream_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal Output_Stream_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal Output_Stream_TUSER_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal Output_Stream_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal Output_Stream_TID_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal Output_Stream_TDEST_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_110_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_110_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_71_fu_123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_115_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_72_fu_137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_70_fu_119_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal regslice_both_Output_Stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal Output_Stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal Output_Stream_TVALID_int_regslice : STD_LOGIC;
    signal Output_Stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_Output_Stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_Output_Stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal Output_Stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_Output_Stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_Output_Stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_Output_Stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal Output_Stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_Output_Stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_Output_Stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_Output_Stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal Output_Stream_TUSER_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_Output_Stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_Output_Stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_Output_Stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal Output_Stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_Output_Stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_Output_Stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_Output_Stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal Output_Stream_TID_int_regslice : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_Output_Stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_Output_Stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_Output_Stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal Output_Stream_TDEST_int_regslice : STD_LOGIC_VECTOR (5 downto 0);
    signal regslice_both_Output_Stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_Output_Stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal grp_fu_110_p00 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_110_p10 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component Canny_Filter_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Suppression_to_Hysteresis_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        Suppression_to_Hysteresis_empty_n : IN STD_LOGIC;
        Suppression_to_Hysteresis_read : OUT STD_LOGIC;
        Suppression_to_Hysteresis_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        Suppression_to_Hysteresis_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        Output_Stream_TREADY : IN STD_LOGIC;
        Cols_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        add_ln70 : IN STD_LOGIC_VECTOR (31 downto 0);
        High_Threshold_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        Low_Threshold_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        add_ln70_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        Output_Stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        Output_Stream_TVALID : OUT STD_LOGIC;
        Output_Stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        Output_Stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        Output_Stream_TUSER : OUT STD_LOGIC_VECTOR (2 downto 0);
        Output_Stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        Output_Stream_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
        Output_Stream_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0);
        bound : IN STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component Canny_Filter_mul_31ns_31ns_62_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component Canny_Filter_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84 : component Canny_Filter_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start,
        ap_done => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_done,
        ap_idle => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_idle,
        ap_ready => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_ready,
        Suppression_to_Hysteresis_dout => Suppression_to_Hysteresis_dout,
        Suppression_to_Hysteresis_empty_n => Suppression_to_Hysteresis_empty_n,
        Suppression_to_Hysteresis_read => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Suppression_to_Hysteresis_read,
        Suppression_to_Hysteresis_num_data_valid => ap_const_lv4_0,
        Suppression_to_Hysteresis_fifo_cap => ap_const_lv4_0,
        Output_Stream_TREADY => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TREADY,
        Cols_3 => Cols_3_reg_181,
        add_ln70 => add_ln70_reg_212,
        High_Threshold_1 => High_Threshold_1_reg_176,
        Low_Threshold_1 => Low_Threshold_1_reg_171,
        add_ln70_1 => add_ln70_1_reg_217,
        Output_Stream_TDATA => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDATA,
        Output_Stream_TVALID => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID,
        Output_Stream_TKEEP => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TKEEP,
        Output_Stream_TSTRB => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TSTRB,
        Output_Stream_TUSER => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TUSER,
        Output_Stream_TLAST => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TLAST,
        Output_Stream_TID => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TID,
        Output_Stream_TDEST => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDEST,
        bound => bound_reg_222);

    mul_31ns_31ns_62_2_1_U80 : component Canny_Filter_mul_31ns_31ns_62_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        dout_WIDTH => 62)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_110_p0,
        din1 => grp_fu_110_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_110_p2);

    regslice_both_Output_Stream_V_data_V_U : component Canny_Filter_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => Output_Stream_TDATA_int_regslice,
        vld_in => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID,
        ack_in => Output_Stream_TREADY_int_regslice,
        data_out => Output_Stream_TDATA,
        vld_out => regslice_both_Output_Stream_V_data_V_U_vld_out,
        ack_out => Output_Stream_TREADY,
        apdone_blk => regslice_both_Output_Stream_V_data_V_U_apdone_blk);

    regslice_both_Output_Stream_V_keep_V_U : component Canny_Filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => Output_Stream_TKEEP_int_regslice,
        vld_in => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID,
        ack_in => regslice_both_Output_Stream_V_keep_V_U_ack_in_dummy,
        data_out => Output_Stream_TKEEP,
        vld_out => regslice_both_Output_Stream_V_keep_V_U_vld_out,
        ack_out => Output_Stream_TREADY,
        apdone_blk => regslice_both_Output_Stream_V_keep_V_U_apdone_blk);

    regslice_both_Output_Stream_V_strb_V_U : component Canny_Filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => Output_Stream_TSTRB_int_regslice,
        vld_in => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID,
        ack_in => regslice_both_Output_Stream_V_strb_V_U_ack_in_dummy,
        data_out => Output_Stream_TSTRB,
        vld_out => regslice_both_Output_Stream_V_strb_V_U_vld_out,
        ack_out => Output_Stream_TREADY,
        apdone_blk => regslice_both_Output_Stream_V_strb_V_U_apdone_blk);

    regslice_both_Output_Stream_V_user_V_U : component Canny_Filter_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => Output_Stream_TUSER_int_regslice,
        vld_in => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID,
        ack_in => regslice_both_Output_Stream_V_user_V_U_ack_in_dummy,
        data_out => Output_Stream_TUSER,
        vld_out => regslice_both_Output_Stream_V_user_V_U_vld_out,
        ack_out => Output_Stream_TREADY,
        apdone_blk => regslice_both_Output_Stream_V_user_V_U_apdone_blk);

    regslice_both_Output_Stream_V_last_V_U : component Canny_Filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => Output_Stream_TLAST_int_regslice,
        vld_in => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID,
        ack_in => regslice_both_Output_Stream_V_last_V_U_ack_in_dummy,
        data_out => Output_Stream_TLAST,
        vld_out => regslice_both_Output_Stream_V_last_V_U_vld_out,
        ack_out => Output_Stream_TREADY,
        apdone_blk => regslice_both_Output_Stream_V_last_V_U_apdone_blk);

    regslice_both_Output_Stream_V_id_V_U : component Canny_Filter_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => Output_Stream_TID_int_regslice,
        vld_in => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID,
        ack_in => regslice_both_Output_Stream_V_id_V_U_ack_in_dummy,
        data_out => Output_Stream_TID,
        vld_out => regslice_both_Output_Stream_V_id_V_U_vld_out,
        ack_out => Output_Stream_TREADY,
        apdone_blk => regslice_both_Output_Stream_V_id_V_U_apdone_blk);

    regslice_both_Output_Stream_V_dest_V_U : component Canny_Filter_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => Output_Stream_TDEST_int_regslice,
        vld_in => grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID,
        ack_in => regslice_both_Output_Stream_V_dest_V_U_ack_in_dummy,
        data_out => Output_Stream_TDEST,
        vld_out => regslice_both_Output_Stream_V_dest_V_U_vld_out,
        ack_out => Output_Stream_TREADY,
        apdone_blk => regslice_both_Output_Stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((regslice_both_Output_Stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_ready = ap_const_logic_1)) then 
                    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                Cols_3_reg_181 <= Cols_dout;
                High_Threshold_1_reg_176 <= High_Threshold_dout;
                Low_Threshold_1_reg_171 <= Low_Threshold_dout;
                Rows_3_reg_187 <= Rows_dout;
                smax1_reg_197 <= smax1_fu_143_p3;
                smax_reg_192 <= smax_fu_129_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID = ap_const_logic_1))) then
                Output_Stream_TDATA_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDATA;
                Output_Stream_TDEST_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDEST;
                Output_Stream_TID_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TID;
                Output_Stream_TKEEP_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TKEEP;
                Output_Stream_TLAST_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TLAST;
                Output_Stream_TSTRB_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TSTRB;
                Output_Stream_TUSER_reg <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln70_1_reg_217 <= add_ln70_1_fu_165_p2;
                add_ln70_reg_212 <= add_ln70_fu_159_p2;
                bound_reg_222 <= grp_fu_110_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state5, regslice_both_Output_Stream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((regslice_both_Output_Stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;

    Cols_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Cols_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Cols_blk_n <= Cols_empty_n;
        else 
            Cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Cols_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Cols_read <= ap_const_logic_1;
        else 
            Cols_read <= ap_const_logic_0;
        end if; 
    end process;


    High_Threshold_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, High_Threshold_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            High_Threshold_blk_n <= High_Threshold_empty_n;
        else 
            High_Threshold_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    High_Threshold_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            High_Threshold_read <= ap_const_logic_1;
        else 
            High_Threshold_read <= ap_const_logic_0;
        end if; 
    end process;


    Low_Threshold_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Low_Threshold_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Low_Threshold_blk_n <= Low_Threshold_empty_n;
        else 
            Low_Threshold_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Low_Threshold_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Low_Threshold_read <= ap_const_logic_1;
        else 
            Low_Threshold_read <= ap_const_logic_0;
        end if; 
    end process;


    Output_Stream_TDATA_int_regslice_assign_proc : process(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDATA, grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID, ap_CS_fsm_state4, Output_Stream_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID = ap_const_logic_1))) then 
            Output_Stream_TDATA_int_regslice <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDATA;
        else 
            Output_Stream_TDATA_int_regslice <= Output_Stream_TDATA_reg;
        end if; 
    end process;


    Output_Stream_TDEST_int_regslice_assign_proc : process(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID, grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDEST, ap_CS_fsm_state4, Output_Stream_TDEST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID = ap_const_logic_1))) then 
            Output_Stream_TDEST_int_regslice <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TDEST;
        else 
            Output_Stream_TDEST_int_regslice <= Output_Stream_TDEST_reg;
        end if; 
    end process;


    Output_Stream_TID_int_regslice_assign_proc : process(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID, grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TID, ap_CS_fsm_state4, Output_Stream_TID_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID = ap_const_logic_1))) then 
            Output_Stream_TID_int_regslice <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TID;
        else 
            Output_Stream_TID_int_regslice <= Output_Stream_TID_reg;
        end if; 
    end process;


    Output_Stream_TKEEP_int_regslice_assign_proc : process(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID, grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TKEEP, ap_CS_fsm_state4, Output_Stream_TKEEP_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID = ap_const_logic_1))) then 
            Output_Stream_TKEEP_int_regslice <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TKEEP;
        else 
            Output_Stream_TKEEP_int_regslice <= Output_Stream_TKEEP_reg;
        end if; 
    end process;


    Output_Stream_TLAST_int_regslice_assign_proc : process(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID, grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TLAST, ap_CS_fsm_state4, Output_Stream_TLAST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID = ap_const_logic_1))) then 
            Output_Stream_TLAST_int_regslice <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TLAST;
        else 
            Output_Stream_TLAST_int_regslice <= Output_Stream_TLAST_reg;
        end if; 
    end process;


    Output_Stream_TSTRB_int_regslice_assign_proc : process(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID, grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TSTRB, ap_CS_fsm_state4, Output_Stream_TSTRB_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID = ap_const_logic_1))) then 
            Output_Stream_TSTRB_int_regslice <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TSTRB;
        else 
            Output_Stream_TSTRB_int_regslice <= Output_Stream_TSTRB_reg;
        end if; 
    end process;


    Output_Stream_TUSER_int_regslice_assign_proc : process(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID, grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TUSER, ap_CS_fsm_state4, Output_Stream_TUSER_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID = ap_const_logic_1))) then 
            Output_Stream_TUSER_int_regslice <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TUSER;
        else 
            Output_Stream_TUSER_int_regslice <= Output_Stream_TUSER_reg;
        end if; 
    end process;

    Output_Stream_TVALID <= regslice_both_Output_Stream_V_data_V_U_vld_out;
    Output_Stream_TVALID_int_regslice <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TVALID;

    Rows_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Rows_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Rows_blk_n <= Rows_empty_n;
        else 
            Rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Rows_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Rows_read <= ap_const_logic_1;
        else 
            Rows_read <= ap_const_logic_0;
        end if; 
    end process;

    Suppression_to_Hysteresis_read <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Suppression_to_Hysteresis_read;
    add_ln70_1_fu_165_p2 <= std_logic_vector(unsigned(Cols_3_reg_181) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln70_fu_159_p2 <= std_logic_vector(unsigned(Rows_3_reg_187) + unsigned(ap_const_lv32_FFFFFFFF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_done)
    begin
        if ((grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(regslice_both_Output_Stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_Output_Stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, Rows_empty_n, Cols_empty_n, High_Threshold_empty_n, Low_Threshold_empty_n)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = Low_Threshold_empty_n) or (ap_const_logic_0 = High_Threshold_empty_n) or (ap_const_logic_0 = Cols_empty_n) or (ap_const_logic_0 = Rows_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, regslice_both_Output_Stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_Output_Stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, regslice_both_Output_Stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_Output_Stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_70_fu_119_p1 <= Rows_dout(31 - 1 downto 0);
    empty_71_fu_123_p2 <= "1" when (signed(Cols_dout) > signed(ap_const_lv32_0)) else "0";
    empty_72_fu_137_p2 <= "1" when (signed(Rows_dout) > signed(ap_const_lv32_0)) else "0";
    empty_fu_115_p1 <= Cols_dout(31 - 1 downto 0);
    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_Output_Stream_TREADY <= (ap_CS_fsm_state4 and Output_Stream_TREADY_int_regslice);
    grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start <= grp_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2_fu_84_ap_start_reg;
    grp_fu_110_p0 <= grp_fu_110_p00(31 - 1 downto 0);
    grp_fu_110_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax1_reg_197),62));
    grp_fu_110_p1 <= grp_fu_110_p10(31 - 1 downto 0);
    grp_fu_110_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax_reg_192),62));
    smax1_fu_143_p3 <= 
        empty_70_fu_119_p1 when (empty_72_fu_137_p2(0) = '1') else 
        ap_const_lv31_0;
    smax_fu_129_p3 <= 
        empty_fu_115_p1 when (empty_71_fu_123_p2(0) = '1') else 
        ap_const_lv31_0;
end behav;
