-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Canny_Filter_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Input_Stream_TVALID : IN STD_LOGIC;
    Gaussian_to_Sobel_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    Gaussian_to_Sobel_full_n : IN STD_LOGIC;
    Gaussian_to_Sobel_write : OUT STD_LOGIC;
    Gaussian_to_Sobel_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    Gaussian_to_Sobel_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    Cols : IN STD_LOGIC_VECTOR (31 downto 0);
    Input_Stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    Input_Stream_TREADY : OUT STD_LOGIC;
    Input_Stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    Input_Stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    Input_Stream_TUSER : IN STD_LOGIC_VECTOR (2 downto 0);
    Input_Stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    Input_Stream_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    Input_Stream_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    bound : IN STD_LOGIC_VECTOR (61 downto 0) );
end;


architecture behav of Canny_Filter_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv62_0 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv62_1 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln13_reg_567 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln13_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal Input_Stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal Gaussian_to_Sobel_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal icmp_ln13_reg_567_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln13_reg_567_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_reg_571 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_s_reg_571_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal p_s_reg_571_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal p_s_reg_571_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Line_Buffer_addr_reg_578 : STD_LOGIC_VECTOR (10 downto 0);
    signal addr_cmp25_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp25_reg_583 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp25_reg_583_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_reg_593 : STD_LOGIC_VECTOR (0 downto 0);
    signal reuse_reg21_load_reg_598 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln28_fu_331_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln28_reg_603 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_load18_reg_609 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_load_reg_614 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp25_fu_393_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp25_reg_619 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln43_fu_399_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_reg_624 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_reg_624_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_3_fu_442_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_3_reg_629 : STD_LOGIC_VECTOR (31 downto 0);
    signal Pixel_Out_reg_634 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_condition_exit_pp0_iter4_stage0 : STD_LOGIC;
    signal Line_Buffer_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal Line_Buffer_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Line_Buffer_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_267_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal reuse_addr_reg22_fu_82 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg21_fu_86 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal Mid_Pixel_fu_323_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal reuse_addr_reg_fu_90 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg_fu_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal Sum_fu_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal empty_fu_102 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal empty_73_fu_106 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal J_fu_110 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln15_fu_306_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_114 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    signal add_ln13_fu_236_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal empty_74_fu_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal Top_Pixel_fu_356_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_75_fu_122 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal empty_76_fu_126 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal Line_Buffer_1_ce0_local : STD_LOGIC;
    signal Line_Buffer_1_we0_local : STD_LOGIC;
    signal Line_Buffer_ce0_local : STD_LOGIC;
    signal Line_Buffer_we0_local : STD_LOGIC;
    signal zext_ln15_1_fu_250_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln15_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln13_fu_259_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln43_fu_362_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_78_fu_374_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_79_fu_378_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp1_fu_388_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_382_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_5_fu_366_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp3_fu_429_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_2_fu_436_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_1_fu_456_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Sum_1_fu_460_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Canny_Filter_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_Line_Buffer_1_RAM_AUbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Canny_Filter_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    Line_Buffer_1_U : component Canny_Filter_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_Line_Buffer_1_RAM_AUbkb
    generic map (
        DataWidth => 32,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Line_Buffer_1_address0,
        ce0 => Line_Buffer_1_ce0_local,
        we0 => Line_Buffer_1_we0_local,
        d0 => Input_Stream_TDATA,
        q0 => Line_Buffer_1_q0);

    Line_Buffer_U : component Canny_Filter_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_Line_Buffer_1_RAM_AUbkb
    generic map (
        DataWidth => 32,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Line_Buffer_addr_reg_578,
        ce0 => Line_Buffer_ce0_local,
        we0 => Line_Buffer_we0_local,
        d0 => Mid_Pixel_fu_323_p3,
        q0 => Line_Buffer_q0);

    flow_control_loop_pipe_sequential_init_U : component Canny_Filter_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0)) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    J_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    J_fu_110 <= ap_const_lv31_0;
                elsif (((icmp_ln13_reg_567 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    J_fu_110 <= add_ln15_fu_306_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_114 <= ap_const_lv62_0;
                elsif (((icmp_ln13_fu_231_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_114 <= add_ln13_fu_236_p2;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg22_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg22_fu_82 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln13_reg_567 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    reuse_addr_reg22_fu_82 <= zext_ln15_fu_267_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg_fu_90 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln13_reg_567 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    reuse_addr_reg_fu_90 <= zext_ln15_fu_267_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg21_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg21_fu_86 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln13_reg_567_pp0_iter2_reg = ap_const_lv1_0))) then 
                    reuse_reg21_fu_86 <= Mid_Pixel_fu_323_p3;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg_fu_94 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln13_reg_567_pp0_iter2_reg = ap_const_lv1_0))) then 
                    reuse_reg_fu_94 <= p_s_reg_571;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                Line_Buffer_addr_reg_578 <= zext_ln15_fu_267_p1(11 - 1 downto 0);
                Pixel_Out_reg_634 <= Sum_1_fu_460_p2(31 downto 4);
                add_ln43_3_reg_629 <= add_ln43_3_fu_442_p2;
                add_ln43_reg_624 <= add_ln43_fu_399_p2;
                add_ln43_reg_624_pp0_iter5_reg <= add_ln43_reg_624;
                addr_cmp25_reg_583 <= addr_cmp25_fu_281_p2;
                addr_cmp25_reg_583_pp0_iter3_reg <= addr_cmp25_reg_583;
                addr_cmp_reg_593 <= addr_cmp_fu_290_p2;
                p_load18_reg_609 <= empty_74_fu_118;
                p_load_reg_614 <= empty_76_fu_126;
                p_s_reg_571 <= Input_Stream_TDATA;
                p_s_reg_571_pp0_iter3_reg <= p_s_reg_571;
                p_s_reg_571_pp0_iter4_reg <= p_s_reg_571_pp0_iter3_reg;
                p_s_reg_571_pp0_iter5_reg <= p_s_reg_571_pp0_iter4_reg;
                reuse_reg21_load_reg_598 <= reuse_reg21_fu_86;
                tmp25_reg_619 <= tmp25_fu_393_p2;
                trunc_ln28_reg_603 <= trunc_ln28_fu_331_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                Sum_fu_98 <= p_load18_reg_609;
                empty_73_fu_106 <= p_load_reg_614;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln13_reg_567 <= icmp_ln13_fu_231_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                icmp_ln13_reg_567_pp0_iter2_reg <= icmp_ln13_reg_567;
                icmp_ln13_reg_567_pp0_iter3_reg <= icmp_ln13_reg_567_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln13_reg_567_pp0_iter3_reg = ap_const_lv1_0))) then
                empty_74_fu_118 <= Top_Pixel_fu_356_p3;
                empty_75_fu_122 <= trunc_ln28_reg_603;
                empty_76_fu_126 <= p_s_reg_571_pp0_iter3_reg;
                empty_fu_102 <= empty_75_fu_122;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    Gaussian_to_Sobel_blk_n_assign_proc : process(ap_enable_reg_pp0_iter7, Gaussian_to_Sobel_full_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            Gaussian_to_Sobel_blk_n <= Gaussian_to_Sobel_full_n;
        else 
            Gaussian_to_Sobel_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        Gaussian_to_Sobel_din <= std_logic_vector(IEEE.numeric_std.resize(signed(Pixel_Out_reg_634),32));


    Gaussian_to_Sobel_write_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            Gaussian_to_Sobel_write <= ap_const_logic_1;
        else 
            Gaussian_to_Sobel_write <= ap_const_logic_0;
        end if; 
    end process;


    Input_Stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, Input_Stream_TVALID, icmp_ln13_reg_567, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln13_reg_567 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Input_Stream_TDATA_blk_n <= Input_Stream_TVALID;
        else 
            Input_Stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Input_Stream_TREADY_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln13_reg_567, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln13_reg_567 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Input_Stream_TREADY <= ap_const_logic_1;
        else 
            Input_Stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    Line_Buffer_1_address0 <= zext_ln15_fu_267_p1(11 - 1 downto 0);

    Line_Buffer_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln13_reg_567, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln13_reg_567 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Line_Buffer_1_ce0_local <= ap_const_logic_1;
        else 
            Line_Buffer_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    Line_Buffer_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln13_reg_567, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln13_reg_567 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Line_Buffer_1_we0_local <= ap_const_logic_1;
        else 
            Line_Buffer_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;


    Line_Buffer_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1, icmp_ln13_reg_567_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln13_reg_567_pp0_iter2_reg = ap_const_lv1_0))) then 
            Line_Buffer_ce0_local <= ap_const_logic_1;
        else 
            Line_Buffer_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    Line_Buffer_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1, icmp_ln13_reg_567_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln13_reg_567_pp0_iter2_reg = ap_const_lv1_0))) then 
            Line_Buffer_we0_local <= ap_const_logic_1;
        else 
            Line_Buffer_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    Mid_Pixel_fu_323_p3 <= 
        reuse_reg_fu_94 when (addr_cmp_reg_593(0) = '1') else 
        Line_Buffer_1_q0;
    Sum_1_fu_460_p2 <= std_logic_vector(unsigned(add_ln43_3_reg_629) + unsigned(add_ln43_1_fu_456_p2));
    Top_Pixel_fu_356_p3 <= 
        reuse_reg21_load_reg_598 when (addr_cmp25_reg_583_pp0_iter3_reg(0) = '1') else 
        Line_Buffer_q0;
    add_ln13_fu_236_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_114) + unsigned(ap_const_lv62_1));
    add_ln15_fu_306_p2 <= std_logic_vector(unsigned(select_ln13_fu_259_p3) + unsigned(ap_const_lv31_1));
    add_ln43_1_fu_456_p2 <= std_logic_vector(unsigned(add_ln43_reg_624_pp0_iter5_reg) + unsigned(p_s_reg_571_pp0_iter5_reg));
    add_ln43_2_fu_436_p2 <= std_logic_vector(unsigned(Sum_fu_98) + unsigned(tmp3_fu_429_p3));
    add_ln43_3_fu_442_p2 <= std_logic_vector(unsigned(add_ln43_2_fu_436_p2) + unsigned(empty_73_fu_106));
    add_ln43_fu_399_p2 <= std_logic_vector(unsigned(Top_Pixel_fu_356_p3) + unsigned(tmp_5_fu_366_p3));
    addr_cmp25_fu_281_p2 <= "1" when (reuse_addr_reg22_fu_82 = zext_ln15_fu_267_p1) else "0";
    addr_cmp_fu_290_p2 <= "1" when (reuse_addr_reg_fu_90 = zext_ln15_fu_267_p1) else "0";
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter7, Gaussian_to_Sobel_full_n, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_0 = Gaussian_to_Sobel_full_n)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter7, Gaussian_to_Sobel_full_n, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_0 = Gaussian_to_Sobel_full_n)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter7, Gaussian_to_Sobel_full_n, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_0 = Gaussian_to_Sobel_full_n)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter7, Gaussian_to_Sobel_full_n, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_0 = Gaussian_to_Sobel_full_n)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_grp1_assign_proc : process(Input_Stream_TVALID, icmp_ln13_reg_567)
    begin
                ap_block_state3_pp0_stage0_iter2_grp1 <= ((icmp_ln13_reg_567 = ap_const_lv1_0) and (ap_const_logic_0 = Input_Stream_TVALID));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln13_fu_231_p2)
    begin
        if (((icmp_ln13_fu_231_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter4_stage0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone, icmp_ln13_reg_567_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln13_reg_567_pp0_iter3_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_78_fu_374_p1 <= empty_76_fu_126(31 - 1 downto 0);
    empty_79_fu_378_p1 <= empty_74_fu_118(31 - 1 downto 0);
    icmp_ln13_fu_231_p2 <= "1" when (indvar_flatten_fu_114 = bound) else "0";
    icmp_ln15_fu_254_p2 <= "1" when (signed(zext_ln15_1_fu_250_p1) < signed(Cols)) else "0";
    select_ln13_fu_259_p3 <= 
        J_fu_110 when (icmp_ln15_fu_254_p2(0) = '1') else 
        ap_const_lv31_0;
    tmp1_fu_388_p2 <= std_logic_vector(unsigned(empty_79_fu_378_p1) + unsigned(trunc_ln28_reg_603));
    tmp25_fu_393_p2 <= std_logic_vector(unsigned(tmp1_fu_388_p2) + unsigned(tmp_fu_382_p2));
    tmp3_fu_429_p3 <= (tmp25_reg_619 & ap_const_lv1_0);
    tmp_5_fu_366_p3 <= (trunc_ln43_fu_362_p1 & ap_const_lv2_0);
    tmp_fu_382_p2 <= std_logic_vector(unsigned(empty_fu_102) + unsigned(empty_78_fu_374_p1));
    trunc_ln28_fu_331_p1 <= Mid_Pixel_fu_323_p3(31 - 1 downto 0);
    trunc_ln43_fu_362_p1 <= empty_75_fu_122(30 - 1 downto 0);
    zext_ln15_1_fu_250_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(J_fu_110),32));
    zext_ln15_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln13_fu_259_p3),64));
end behav;
