// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
(* DowngradeIPIdentifiedWarnings="yes" *) module Sobel_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_Line_Buffer_data_RAM_AUcud (
    address0, ce0,
    d0, we0,
    address1, ce1,
    q1,
    reset, clk);

parameter DataWidth = 32;
parameter AddressWidth = 11;
parameter AddressRange = 1920;

input [AddressWidth-1:0] address0;
input ce0;
input [DataWidth-1:0] d0;
input we0;
input [AddressWidth-1:0] address1;
input ce1;
output reg [DataWidth-1:0] q1;
input reset;
input clk;

(* ram_style = "auto" *) reg [DataWidth-1:0] ram[0:AddressRange-1];


always @(posedge clk)
begin
    if (ce0)
    begin
        if (we0)
            ram[address0] <= d0;
    end
end

always @(posedge clk)
begin
    if (ce1)
    begin
        q1 <= ram[address1];
    end
end


endmodule

