// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module Canny_Filter_Gaussian_Filter (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        Input_Stream_TDATA,
        Input_Stream_TVALID,
        Input_Stream_TREADY,
        Input_Stream_TKEEP,
        Input_Stream_TSTRB,
        Input_Stream_TUSER,
        Input_Stream_TLAST,
        Input_Stream_TID,
        Input_Stream_TDEST,
        Gaussian_to_Sobel_din,
        Gaussian_to_Sobel_full_n,
        Gaussian_to_Sobel_write,
        Gaussian_to_Sobel_num_data_valid,
        Gaussian_to_Sobel_fifo_cap,
        Rows,
        Cols,
        Rows_c2_din,
        Rows_c2_full_n,
        Rows_c2_write,
        Rows_c2_num_data_valid,
        Rows_c2_fifo_cap,
        Cols_c4_din,
        Cols_c4_full_n,
        Cols_c4_write,
        Cols_c4_num_data_valid,
        Cols_c4_fifo_cap
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] Input_Stream_TDATA;
input   Input_Stream_TVALID;
output   Input_Stream_TREADY;
input  [3:0] Input_Stream_TKEEP;
input  [3:0] Input_Stream_TSTRB;
input  [2:0] Input_Stream_TUSER;
input  [0:0] Input_Stream_TLAST;
input  [4:0] Input_Stream_TID;
input  [5:0] Input_Stream_TDEST;
output  [31:0] Gaussian_to_Sobel_din;
input   Gaussian_to_Sobel_full_n;
output   Gaussian_to_Sobel_write;
input  [3:0] Gaussian_to_Sobel_num_data_valid;
input  [3:0] Gaussian_to_Sobel_fifo_cap;
input  [31:0] Rows;
input  [31:0] Cols;
output  [31:0] Rows_c2_din;
input   Rows_c2_full_n;
output   Rows_c2_write;
input  [2:0] Rows_c2_num_data_valid;
input  [2:0] Rows_c2_fifo_cap;
output  [31:0] Cols_c4_din;
input   Cols_c4_full_n;
output   Cols_c4_write;
input  [2:0] Cols_c4_num_data_valid;
input  [2:0] Cols_c4_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg Rows_c2_write;
reg Cols_c4_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    Rows_c2_blk_n;
reg    Cols_c4_blk_n;
reg   [31:0] Cols_read_reg_160;
reg    ap_block_state1;
wire   [30:0] smax_fu_130_p3;
reg   [30:0] smax_reg_165;
wire   [30:0] smax1_fu_144_p3;
reg   [30:0] smax1_reg_170;
wire    ap_CS_fsm_state2;
wire   [61:0] grp_fu_112_p2;
reg   [61:0] bound_reg_185;
wire    ap_CS_fsm_state3;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_start;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_done;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_idle;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_ready;
wire   [31:0] grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_Gaussian_to_Sobel_din;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_Gaussian_to_Sobel_write;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_Input_Stream_TREADY;
reg    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_start_reg;
reg   [4:0] ap_NS_fsm;
wire    ap_NS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [30:0] grp_fu_112_p0;
wire   [30:0] grp_fu_112_p1;
wire   [0:0] empty_81_fu_124_p2;
wire   [30:0] empty_80_fu_120_p1;
wire   [0:0] empty_82_fu_138_p2;
wire   [30:0] empty_fu_116_p1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_Input_Stream_V_data_V_U_apdone_blk;
wire   [31:0] Input_Stream_TDATA_int_regslice;
wire    Input_Stream_TVALID_int_regslice;
reg    Input_Stream_TREADY_int_regslice;
wire    regslice_both_Input_Stream_V_data_V_U_ack_in;
wire    regslice_both_Input_Stream_V_keep_V_U_apdone_blk;
wire   [3:0] Input_Stream_TKEEP_int_regslice;
wire    regslice_both_Input_Stream_V_keep_V_U_vld_out;
wire    regslice_both_Input_Stream_V_keep_V_U_ack_in;
wire    regslice_both_Input_Stream_V_strb_V_U_apdone_blk;
wire   [3:0] Input_Stream_TSTRB_int_regslice;
wire    regslice_both_Input_Stream_V_strb_V_U_vld_out;
wire    regslice_both_Input_Stream_V_strb_V_U_ack_in;
wire    regslice_both_Input_Stream_V_user_V_U_apdone_blk;
wire   [2:0] Input_Stream_TUSER_int_regslice;
wire    regslice_both_Input_Stream_V_user_V_U_vld_out;
wire    regslice_both_Input_Stream_V_user_V_U_ack_in;
wire    regslice_both_Input_Stream_V_last_V_U_apdone_blk;
wire   [0:0] Input_Stream_TLAST_int_regslice;
wire    regslice_both_Input_Stream_V_last_V_U_vld_out;
wire    regslice_both_Input_Stream_V_last_V_U_ack_in;
wire    regslice_both_Input_Stream_V_id_V_U_apdone_blk;
wire   [4:0] Input_Stream_TID_int_regslice;
wire    regslice_both_Input_Stream_V_id_V_U_vld_out;
wire    regslice_both_Input_Stream_V_id_V_U_ack_in;
wire    regslice_both_Input_Stream_V_dest_V_U_apdone_blk;
wire   [5:0] Input_Stream_TDEST_int_regslice;
wire    regslice_both_Input_Stream_V_dest_V_U_vld_out;
wire    regslice_both_Input_Stream_V_dest_V_U_ack_in;
wire   [61:0] grp_fu_112_p00;
wire   [61:0] grp_fu_112_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_start_reg = 1'b0;
end

Canny_Filter_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2 grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_start),
    .ap_done(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_done),
    .ap_idle(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_idle),
    .ap_ready(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_ready),
    .Input_Stream_TVALID(Input_Stream_TVALID_int_regslice),
    .Gaussian_to_Sobel_din(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_Gaussian_to_Sobel_din),
    .Gaussian_to_Sobel_full_n(Gaussian_to_Sobel_full_n),
    .Gaussian_to_Sobel_write(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_Gaussian_to_Sobel_write),
    .Gaussian_to_Sobel_num_data_valid(4'd0),
    .Gaussian_to_Sobel_fifo_cap(4'd0),
    .Cols(Cols_read_reg_160),
    .Input_Stream_TDATA(Input_Stream_TDATA_int_regslice),
    .Input_Stream_TREADY(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_Input_Stream_TREADY),
    .Input_Stream_TKEEP(Input_Stream_TKEEP_int_regslice),
    .Input_Stream_TSTRB(Input_Stream_TSTRB_int_regslice),
    .Input_Stream_TUSER(Input_Stream_TUSER_int_regslice),
    .Input_Stream_TLAST(Input_Stream_TLAST_int_regslice),
    .Input_Stream_TID(Input_Stream_TID_int_regslice),
    .Input_Stream_TDEST(Input_Stream_TDEST_int_regslice),
    .bound(bound_reg_185)
);

Canny_Filter_mul_31ns_31ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31ns_31ns_62_2_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_112_p0),
    .din1(grp_fu_112_p1),
    .ce(1'b1),
    .dout(grp_fu_112_p2)
);

Canny_Filter_regslice_both #(
    .DataWidth( 32 ))
regslice_both_Input_Stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Input_Stream_TDATA),
    .vld_in(Input_Stream_TVALID),
    .ack_in(regslice_both_Input_Stream_V_data_V_U_ack_in),
    .data_out(Input_Stream_TDATA_int_regslice),
    .vld_out(Input_Stream_TVALID_int_regslice),
    .ack_out(Input_Stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_Stream_V_data_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_Input_Stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Input_Stream_TKEEP),
    .vld_in(Input_Stream_TVALID),
    .ack_in(regslice_both_Input_Stream_V_keep_V_U_ack_in),
    .data_out(Input_Stream_TKEEP_int_regslice),
    .vld_out(regslice_both_Input_Stream_V_keep_V_U_vld_out),
    .ack_out(Input_Stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_Stream_V_keep_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_Input_Stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Input_Stream_TSTRB),
    .vld_in(Input_Stream_TVALID),
    .ack_in(regslice_both_Input_Stream_V_strb_V_U_ack_in),
    .data_out(Input_Stream_TSTRB_int_regslice),
    .vld_out(regslice_both_Input_Stream_V_strb_V_U_vld_out),
    .ack_out(Input_Stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_Stream_V_strb_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 3 ))
regslice_both_Input_Stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Input_Stream_TUSER),
    .vld_in(Input_Stream_TVALID),
    .ack_in(regslice_both_Input_Stream_V_user_V_U_ack_in),
    .data_out(Input_Stream_TUSER_int_regslice),
    .vld_out(regslice_both_Input_Stream_V_user_V_U_vld_out),
    .ack_out(Input_Stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_Stream_V_user_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_Input_Stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Input_Stream_TLAST),
    .vld_in(Input_Stream_TVALID),
    .ack_in(regslice_both_Input_Stream_V_last_V_U_ack_in),
    .data_out(Input_Stream_TLAST_int_regslice),
    .vld_out(regslice_both_Input_Stream_V_last_V_U_vld_out),
    .ack_out(Input_Stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_Stream_V_last_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 5 ))
regslice_both_Input_Stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Input_Stream_TID),
    .vld_in(Input_Stream_TVALID),
    .ack_in(regslice_both_Input_Stream_V_id_V_U_ack_in),
    .data_out(Input_Stream_TID_int_regslice),
    .vld_out(regslice_both_Input_Stream_V_id_V_U_vld_out),
    .ack_out(Input_Stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_Stream_V_id_V_U_apdone_blk)
);

Canny_Filter_regslice_both #(
    .DataWidth( 6 ))
regslice_both_Input_Stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(Input_Stream_TDEST),
    .vld_in(Input_Stream_TVALID),
    .ack_in(regslice_both_Input_Stream_V_dest_V_U_ack_in),
    .data_out(Input_Stream_TDEST_int_regslice),
    .vld_out(regslice_both_Input_Stream_V_dest_V_U_vld_out),
    .ack_out(Input_Stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_Stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state4) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_start_reg <= 1'b1;
        end else if ((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_ready == 1'b1)) begin
            grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        Cols_read_reg_160 <= Cols;
        smax1_reg_170 <= smax1_fu_144_p3;
        smax_reg_165 <= smax_fu_130_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bound_reg_185 <= grp_fu_112_p2;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Cols_c4_blk_n = Cols_c4_full_n;
    end else begin
        Cols_c4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        Cols_c4_write = 1'b1;
    end else begin
        Cols_c4_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Input_Stream_TREADY_int_regslice = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_Input_Stream_TREADY;
    end else begin
        Input_Stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Rows_c2_blk_n = Rows_c2_full_n;
    end else begin
        Rows_c2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        Rows_c2_write = 1'b1;
    end else begin
        Rows_c2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Cols_c4_din = Cols;

assign Gaussian_to_Sobel_din = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_Gaussian_to_Sobel_din;

assign Gaussian_to_Sobel_write = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_Gaussian_to_Sobel_write;

assign Input_Stream_TREADY = regslice_both_Input_Stream_V_data_V_U_ack_in;

assign Rows_c2_din = Rows;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_NS_fsm_state4 = ap_NS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((1'b0 == Cols_c4_full_n) | (1'b0 == Rows_c2_full_n) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign empty_80_fu_120_p1 = Cols[30:0];

assign empty_81_fu_124_p2 = (($signed(Cols) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_82_fu_138_p2 = (($signed(Rows) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_fu_116_p1 = Rows[30:0];

assign grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_start = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_fu_90_ap_start_reg;

assign grp_fu_112_p0 = grp_fu_112_p00;

assign grp_fu_112_p00 = smax1_reg_170;

assign grp_fu_112_p1 = grp_fu_112_p10;

assign grp_fu_112_p10 = smax_reg_165;

assign smax1_fu_144_p3 = ((empty_82_fu_138_p2[0:0] == 1'b1) ? empty_fu_116_p1 : 31'd0);

assign smax_fu_130_p3 = ((empty_81_fu_124_p2[0:0] == 1'b1) ? empty_80_fu_120_p1 : 31'd0);

assign start_out = real_start;

endmodule //Canny_Filter_Gaussian_Filter
