// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Gaussian_Filter_Gaussian_Filter,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.206000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=1774,HLS_SYN_LUT=1501,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module Gaussian_Filter (
        ap_clk,
        ap_rst_n,
        Input_r_TDATA,
        Input_r_TVALID,
        Input_r_TREADY,
        Input_r_TKEEP,
        Input_r_TSTRB,
        Input_r_TUSER,
        Input_r_TLAST,
        Input_r_TID,
        Input_r_TDEST,
        Output_r_TDATA,
        Output_r_TVALID,
        Output_r_TREADY,
        Output_r_TKEEP,
        Output_r_TSTRB,
        Output_r_TUSER,
        Output_r_TLAST,
        Output_r_TID,
        Output_r_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] Input_r_TDATA;
input   Input_r_TVALID;
output   Input_r_TREADY;
input  [3:0] Input_r_TKEEP;
input  [3:0] Input_r_TSTRB;
input  [2:0] Input_r_TUSER;
input  [0:0] Input_r_TLAST;
input  [4:0] Input_r_TID;
input  [5:0] Input_r_TDEST;
output  [31:0] Output_r_TDATA;
output   Output_r_TVALID;
input   Output_r_TREADY;
output  [3:0] Output_r_TKEEP;
output  [3:0] Output_r_TSTRB;
output  [2:0] Output_r_TUSER;
output  [0:0] Output_r_TLAST;
output  [4:0] Output_r_TID;
output  [5:0] Output_r_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] Rows;
wire   [31:0] Cols;
reg   [31:0] Cols_read_reg_168;
wire   [30:0] smax_fu_138_p3;
reg   [30:0] smax_reg_173;
wire   [30:0] smax1_fu_152_p3;
reg   [30:0] smax1_reg_178;
wire    ap_CS_fsm_state2;
wire   [61:0] grp_fu_120_p2;
reg   [61:0] bound_reg_193;
wire    ap_CS_fsm_state3;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_start;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_done;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_idle;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_ready;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TREADY;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Input_r_TREADY;
wire   [31:0] grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TDATA;
wire    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID;
wire   [3:0] grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TKEEP;
wire   [3:0] grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TSTRB;
wire   [2:0] grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TUSER;
wire   [0:0] grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TLAST;
wire   [4:0] grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TID;
wire   [5:0] grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TDEST;
reg    grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_start_reg;
reg   [5:0] ap_NS_fsm;
wire    ap_NS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [31:0] Output_r_TDATA_reg;
reg   [3:0] Output_r_TKEEP_reg;
reg   [3:0] Output_r_TSTRB_reg;
reg   [2:0] Output_r_TUSER_reg;
reg   [0:0] Output_r_TLAST_reg;
reg   [4:0] Output_r_TID_reg;
reg   [5:0] Output_r_TDEST_reg;
wire   [30:0] grp_fu_120_p0;
wire   [30:0] grp_fu_120_p1;
wire   [0:0] empty_fu_132_p2;
wire   [30:0] trunc_ln9_1_fu_128_p1;
wire   [0:0] empty_30_fu_146_p2;
wire   [30:0] trunc_ln9_fu_124_p1;
wire    ap_CS_fsm_state6;
wire    regslice_both_Output_r_V_data_V_U_apdone_blk;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    regslice_both_Input_r_V_data_V_U_apdone_blk;
wire   [31:0] Input_r_TDATA_int_regslice;
wire    Input_r_TVALID_int_regslice;
reg    Input_r_TREADY_int_regslice;
wire    regslice_both_Input_r_V_data_V_U_ack_in;
wire    regslice_both_Input_r_V_keep_V_U_apdone_blk;
wire   [3:0] Input_r_TKEEP_int_regslice;
wire    regslice_both_Input_r_V_keep_V_U_vld_out;
wire    regslice_both_Input_r_V_keep_V_U_ack_in;
wire    regslice_both_Input_r_V_strb_V_U_apdone_blk;
wire   [3:0] Input_r_TSTRB_int_regslice;
wire    regslice_both_Input_r_V_strb_V_U_vld_out;
wire    regslice_both_Input_r_V_strb_V_U_ack_in;
wire    regslice_both_Input_r_V_user_V_U_apdone_blk;
wire   [2:0] Input_r_TUSER_int_regslice;
wire    regslice_both_Input_r_V_user_V_U_vld_out;
wire    regslice_both_Input_r_V_user_V_U_ack_in;
wire    regslice_both_Input_r_V_last_V_U_apdone_blk;
wire   [0:0] Input_r_TLAST_int_regslice;
wire    regslice_both_Input_r_V_last_V_U_vld_out;
wire    regslice_both_Input_r_V_last_V_U_ack_in;
wire    regslice_both_Input_r_V_id_V_U_apdone_blk;
wire   [4:0] Input_r_TID_int_regslice;
wire    regslice_both_Input_r_V_id_V_U_vld_out;
wire    regslice_both_Input_r_V_id_V_U_ack_in;
wire    regslice_both_Input_r_V_dest_V_U_apdone_blk;
wire   [5:0] Input_r_TDEST_int_regslice;
wire    regslice_both_Input_r_V_dest_V_U_vld_out;
wire    regslice_both_Input_r_V_dest_V_U_ack_in;
reg   [31:0] Output_r_TDATA_int_regslice;
wire    Output_r_TVALID_int_regslice;
wire    Output_r_TREADY_int_regslice;
wire    regslice_both_Output_r_V_data_V_U_vld_out;
wire    regslice_both_Output_r_V_keep_V_U_apdone_blk;
reg   [3:0] Output_r_TKEEP_int_regslice;
wire    regslice_both_Output_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_Output_r_V_keep_V_U_vld_out;
wire    regslice_both_Output_r_V_strb_V_U_apdone_blk;
reg   [3:0] Output_r_TSTRB_int_regslice;
wire    regslice_both_Output_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_Output_r_V_strb_V_U_vld_out;
wire    regslice_both_Output_r_V_user_V_U_apdone_blk;
reg   [2:0] Output_r_TUSER_int_regslice;
wire    regslice_both_Output_r_V_user_V_U_ack_in_dummy;
wire    regslice_both_Output_r_V_user_V_U_vld_out;
wire    regslice_both_Output_r_V_last_V_U_apdone_blk;
reg   [0:0] Output_r_TLAST_int_regslice;
wire    regslice_both_Output_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_Output_r_V_last_V_U_vld_out;
wire    regslice_both_Output_r_V_id_V_U_apdone_blk;
reg   [4:0] Output_r_TID_int_regslice;
wire    regslice_both_Output_r_V_id_V_U_ack_in_dummy;
wire    regslice_both_Output_r_V_id_V_U_vld_out;
wire    regslice_both_Output_r_V_dest_V_U_apdone_blk;
reg   [5:0] Output_r_TDEST_int_regslice;
wire    regslice_both_Output_r_V_dest_V_U_ack_in_dummy;
wire    regslice_both_Output_r_V_dest_V_U_vld_out;
wire   [61:0] grp_fu_120_p00;
wire   [61:0] grp_fu_120_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_start_reg = 1'b0;
end

Gaussian_Filter_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2 grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_start),
    .ap_done(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_done),
    .ap_idle(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_idle),
    .ap_ready(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_ready),
    .Input_r_TVALID(Input_r_TVALID_int_regslice),
    .Output_r_TREADY(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TREADY),
    .Cols(Cols_read_reg_168),
    .bound(bound_reg_193),
    .Input_r_TDATA(Input_r_TDATA_int_regslice),
    .Input_r_TREADY(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Input_r_TREADY),
    .Input_r_TKEEP(Input_r_TKEEP_int_regslice),
    .Input_r_TSTRB(Input_r_TSTRB_int_regslice),
    .Input_r_TUSER(Input_r_TUSER_int_regslice),
    .Input_r_TLAST(Input_r_TLAST_int_regslice),
    .Input_r_TID(Input_r_TID_int_regslice),
    .Input_r_TDEST(Input_r_TDEST_int_regslice),
    .Output_r_TDATA(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TDATA),
    .Output_r_TVALID(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID),
    .Output_r_TKEEP(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TKEEP),
    .Output_r_TSTRB(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TSTRB),
    .Output_r_TUSER(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TUSER),
    .Output_r_TLAST(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TLAST),
    .Output_r_TID(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TID),
    .Output_r_TDEST(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TDEST)
);

Gaussian_Filter_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .Rows(Rows),
    .Cols(Cols),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

Gaussian_Filter_mul_31ns_31ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31ns_31ns_62_2_1_U18(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_120_p0),
    .din1(grp_fu_120_p1),
    .ce(1'b1),
    .dout(grp_fu_120_p2)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 32 ))
regslice_both_Input_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_r_TDATA),
    .vld_in(Input_r_TVALID),
    .ack_in(regslice_both_Input_r_V_data_V_U_ack_in),
    .data_out(Input_r_TDATA_int_regslice),
    .vld_out(Input_r_TVALID_int_regslice),
    .ack_out(Input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_r_V_data_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_Input_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_r_TKEEP),
    .vld_in(Input_r_TVALID),
    .ack_in(regslice_both_Input_r_V_keep_V_U_ack_in),
    .data_out(Input_r_TKEEP_int_regslice),
    .vld_out(regslice_both_Input_r_V_keep_V_U_vld_out),
    .ack_out(Input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_r_V_keep_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_Input_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_r_TSTRB),
    .vld_in(Input_r_TVALID),
    .ack_in(regslice_both_Input_r_V_strb_V_U_ack_in),
    .data_out(Input_r_TSTRB_int_regslice),
    .vld_out(regslice_both_Input_r_V_strb_V_U_vld_out),
    .ack_out(Input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_r_V_strb_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 3 ))
regslice_both_Input_r_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_r_TUSER),
    .vld_in(Input_r_TVALID),
    .ack_in(regslice_both_Input_r_V_user_V_U_ack_in),
    .data_out(Input_r_TUSER_int_regslice),
    .vld_out(regslice_both_Input_r_V_user_V_U_vld_out),
    .ack_out(Input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_r_V_user_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_Input_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_r_TLAST),
    .vld_in(Input_r_TVALID),
    .ack_in(regslice_both_Input_r_V_last_V_U_ack_in),
    .data_out(Input_r_TLAST_int_regslice),
    .vld_out(regslice_both_Input_r_V_last_V_U_vld_out),
    .ack_out(Input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_r_V_last_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 5 ))
regslice_both_Input_r_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_r_TID),
    .vld_in(Input_r_TVALID),
    .ack_in(regslice_both_Input_r_V_id_V_U_ack_in),
    .data_out(Input_r_TID_int_regslice),
    .vld_out(regslice_both_Input_r_V_id_V_U_vld_out),
    .ack_out(Input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_r_V_id_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 6 ))
regslice_both_Input_r_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_r_TDEST),
    .vld_in(Input_r_TVALID),
    .ack_in(regslice_both_Input_r_V_dest_V_U_ack_in),
    .data_out(Input_r_TDEST_int_regslice),
    .vld_out(regslice_both_Input_r_V_dest_V_U_vld_out),
    .ack_out(Input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_r_V_dest_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 32 ))
regslice_both_Output_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Output_r_TDATA_int_regslice),
    .vld_in(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID),
    .ack_in(Output_r_TREADY_int_regslice),
    .data_out(Output_r_TDATA),
    .vld_out(regslice_both_Output_r_V_data_V_U_vld_out),
    .ack_out(Output_r_TREADY),
    .apdone_blk(regslice_both_Output_r_V_data_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_Output_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Output_r_TKEEP_int_regslice),
    .vld_in(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID),
    .ack_in(regslice_both_Output_r_V_keep_V_U_ack_in_dummy),
    .data_out(Output_r_TKEEP),
    .vld_out(regslice_both_Output_r_V_keep_V_U_vld_out),
    .ack_out(Output_r_TREADY),
    .apdone_blk(regslice_both_Output_r_V_keep_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_Output_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Output_r_TSTRB_int_regslice),
    .vld_in(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID),
    .ack_in(regslice_both_Output_r_V_strb_V_U_ack_in_dummy),
    .data_out(Output_r_TSTRB),
    .vld_out(regslice_both_Output_r_V_strb_V_U_vld_out),
    .ack_out(Output_r_TREADY),
    .apdone_blk(regslice_both_Output_r_V_strb_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 3 ))
regslice_both_Output_r_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Output_r_TUSER_int_regslice),
    .vld_in(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID),
    .ack_in(regslice_both_Output_r_V_user_V_U_ack_in_dummy),
    .data_out(Output_r_TUSER),
    .vld_out(regslice_both_Output_r_V_user_V_U_vld_out),
    .ack_out(Output_r_TREADY),
    .apdone_blk(regslice_both_Output_r_V_user_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_Output_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Output_r_TLAST_int_regslice),
    .vld_in(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID),
    .ack_in(regslice_both_Output_r_V_last_V_U_ack_in_dummy),
    .data_out(Output_r_TLAST),
    .vld_out(regslice_both_Output_r_V_last_V_U_vld_out),
    .ack_out(Output_r_TREADY),
    .apdone_blk(regslice_both_Output_r_V_last_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 5 ))
regslice_both_Output_r_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Output_r_TID_int_regslice),
    .vld_in(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID),
    .ack_in(regslice_both_Output_r_V_id_V_U_ack_in_dummy),
    .data_out(Output_r_TID),
    .vld_out(regslice_both_Output_r_V_id_V_U_vld_out),
    .ack_out(Output_r_TREADY),
    .apdone_blk(regslice_both_Output_r_V_id_V_U_apdone_blk)
);

Gaussian_Filter_regslice_both #(
    .DataWidth( 6 ))
regslice_both_Output_r_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Output_r_TDEST_int_regslice),
    .vld_in(grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID),
    .ack_in(regslice_both_Output_r_V_dest_V_U_ack_in_dummy),
    .data_out(Output_r_TDEST),
    .vld_out(regslice_both_Output_r_V_dest_V_U_vld_out),
    .ack_out(Output_r_TREADY),
    .apdone_blk(regslice_both_Output_r_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_NS_fsm_state4))) begin
            grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_ready == 1'b1)) begin
            grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Cols_read_reg_168 <= Cols;
        smax1_reg_178 <= smax1_fu_152_p3;
        smax_reg_173 <= smax_fu_138_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        Output_r_TDATA_reg <= grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TDATA;
        Output_r_TDEST_reg <= grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TDEST;
        Output_r_TID_reg <= grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TID;
        Output_r_TKEEP_reg <= grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TKEEP;
        Output_r_TLAST_reg <= grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TLAST;
        Output_r_TSTRB_reg <= grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TSTRB;
        Output_r_TUSER_reg <= grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bound_reg_193 <= grp_fu_120_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Input_r_TREADY_int_regslice = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Input_r_TREADY;
    end else begin
        Input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        Output_r_TDATA_int_regslice = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TDATA;
    end else begin
        Output_r_TDATA_int_regslice = Output_r_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        Output_r_TDEST_int_regslice = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TDEST;
    end else begin
        Output_r_TDEST_int_regslice = Output_r_TDEST_reg;
    end
end

always @ (*) begin
    if (((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        Output_r_TID_int_regslice = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TID;
    end else begin
        Output_r_TID_int_regslice = Output_r_TID_reg;
    end
end

always @ (*) begin
    if (((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        Output_r_TKEEP_int_regslice = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TKEEP;
    end else begin
        Output_r_TKEEP_int_regslice = Output_r_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        Output_r_TLAST_int_regslice = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TLAST;
    end else begin
        Output_r_TLAST_int_regslice = Output_r_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        Output_r_TSTRB_int_regslice = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TSTRB;
    end else begin
        Output_r_TSTRB_int_regslice = Output_r_TSTRB_reg;
    end
end

always @ (*) begin
    if (((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        Output_r_TUSER_int_regslice = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TUSER;
    end else begin
        Output_r_TUSER_int_regslice = Output_r_TUSER_reg;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_Output_r_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (regslice_both_Output_r_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (regslice_both_Output_r_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (regslice_both_Output_r_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Input_r_TREADY = regslice_both_Input_r_V_data_V_U_ack_in;

assign Output_r_TVALID = regslice_both_Output_r_V_data_V_U_vld_out;

assign Output_r_TVALID_int_regslice = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TVALID;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_NS_fsm_state4 = ap_NS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_30_fu_146_p2 = (($signed(Rows) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_fu_132_p2 = (($signed(Cols) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_Output_r_TREADY = (ap_CS_fsm_state5 & Output_r_TREADY_int_regslice);

assign grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_start = grp_Gaussian_Filter_Pipeline_VITIS_LOOP_25_1_VITIS_LOOP_27_2_fu_86_ap_start_reg;

assign grp_fu_120_p0 = grp_fu_120_p00;

assign grp_fu_120_p00 = smax1_reg_178;

assign grp_fu_120_p1 = grp_fu_120_p10;

assign grp_fu_120_p10 = smax_reg_173;

assign smax1_fu_152_p3 = ((empty_30_fu_146_p2[0:0] == 1'b1) ? trunc_ln9_fu_124_p1 : 31'd0);

assign smax_fu_138_p3 = ((empty_fu_132_p2[0:0] == 1'b1) ? trunc_ln9_1_fu_128_p1 : 31'd0);

assign trunc_ln9_1_fu_128_p1 = Cols[30:0];

assign trunc_ln9_fu_124_p1 = Rows[30:0];

endmodule //Gaussian_Filter
