-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Sobel_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Input_r_TVALID : IN STD_LOGIC;
    Output_r_TREADY : IN STD_LOGIC;
    Cols : IN STD_LOGIC_VECTOR (31 downto 0);
    bound : IN STD_LOGIC_VECTOR (61 downto 0);
    Input_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    Input_r_TREADY : OUT STD_LOGIC;
    Input_r_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    Input_r_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    Input_r_TUSER : IN STD_LOGIC_VECTOR (2 downto 0);
    Input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    Input_r_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    Input_r_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    Output_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    Output_r_TVALID : OUT STD_LOGIC;
    Output_r_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    Output_r_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    Output_r_TUSER : OUT STD_LOGIC_VECTOR (2 downto 0);
    Output_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    Output_r_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    Output_r_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of Sobel_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv62_0 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv62_1 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln26_reg_693 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln26_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal Input_r_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal Output_r_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal icmp_ln26_reg_693_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_reg_697 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_s_reg_697_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal p_1_reg_705 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_1_reg_705_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_1_reg_705_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_2_reg_710 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_2_reg_710_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_2_reg_710_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_3_reg_715 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_3_reg_715_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal p_3_reg_715_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal p_4_reg_720 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_4_reg_720_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_4_reg_720_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_5_reg_725 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_5_reg_725_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal p_5_reg_725_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0_reg_730 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_0_reg_730_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal p_0_reg_730_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal Line_Buffer_data_addr_reg_735 : STD_LOGIC_VECTOR (10 downto 0);
    signal addr_cmp24_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp24_reg_741 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_fu_351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_reg_751 : STD_LOGIC_VECTOR (0 downto 0);
    signal reuse_select25_fu_407_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal reuse_select25_reg_756 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp5_fu_438_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp5_reg_762 : STD_LOGIC_VECTOR (30 downto 0);
    signal sub_ln57_fu_470_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln57_reg_767 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln58_fu_475_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln58_reg_772 : STD_LOGIC_VECTOR (31 downto 0);
    signal Gx_Value_fu_522_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Gx_Value_reg_777 : STD_LOGIC_VECTOR (31 downto 0);
    signal Gy_Value_2_fu_531_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Gy_Value_2_reg_783 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln62_fu_536_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln62_reg_789 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln63_fu_542_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln63_reg_794 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal Line_Buffer_data_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal Line_Buffer_data_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Line_Buffer_data_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal Line_Buffer_data_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln28_fu_304_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal reuse_addr_reg21_fu_96 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg20_fu_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal reuse_select_fu_417_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal reuse_addr_reg_fu_104 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg_fu_108 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal Gy_Value_fu_112 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_0_0_0_0158_1441_fu_116 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal p_0_0_0_0158_2455_fu_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal J_fu_124 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln28_fu_367_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal indvar_flatten_fu_128 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    signal add_ln26_fu_273_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_0_0_0_0158434_fu_132 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_0_0_0_0158_1448_fu_136 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal trunc_ln43_fu_425_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_0_0_0_0158_2462_fu_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal Line_Buffer_data_ce1_local : STD_LOGIC;
    signal Line_Buffer_data_we0_local : STD_LOGIC;
    signal Line_Buffer_data_ce0_local : STD_LOGIC;
    signal Line_Buffer_data_1_ce0_local : STD_LOGIC;
    signal Line_Buffer_data_1_we0_local : STD_LOGIC;
    signal zext_ln28_1_fu_287_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln28_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln26_fu_296_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln28_1_fu_400_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln28_fu_396_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp31_fu_450_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln57_fu_464_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln58_fu_444_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp4_fu_456_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp1_fu_510_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln57_1_fu_517_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Gy_Value_3_fu_527_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_548_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_561_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Gx_Value_Abs_fu_555_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal Gy_Value_Abs_fu_568_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal Magnitude_fu_574_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_580_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln68_fu_590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Sobel_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_Line_Buffer_data_1_RAM_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Sobel_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_Line_Buffer_data_RAM_AUcud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Sobel_Filter_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    Line_Buffer_data_1_U : component Sobel_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_Line_Buffer_data_1_RAM_bkb
    generic map (
        DataWidth => 32,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Line_Buffer_data_1_address0,
        ce0 => Line_Buffer_data_1_ce0_local,
        we0 => Line_Buffer_data_1_we0_local,
        d0 => Input_r_TDATA,
        q0 => Line_Buffer_data_1_q0);

    Line_Buffer_data_U : component Sobel_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_Line_Buffer_data_RAM_AUcud
    generic map (
        DataWidth => 32,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Line_Buffer_data_addr_reg_735,
        ce0 => Line_Buffer_data_ce0_local,
        we0 => Line_Buffer_data_we0_local,
        d0 => reuse_select_fu_417_p3,
        address1 => Line_Buffer_data_address1,
        ce1 => Line_Buffer_data_ce1_local,
        q1 => Line_Buffer_data_q1);

    flow_control_loop_pipe_sequential_init_U : component Sobel_Filter_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    J_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    J_fu_124 <= ap_const_lv11_0;
                elsif (((icmp_ln26_reg_693 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    J_fu_124 <= add_ln28_fu_367_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_128 <= ap_const_lv62_0;
                elsif (((icmp_ln26_fu_268_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_128 <= add_ln26_fu_273_p2;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg21_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg21_fu_96 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln26_reg_693 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    reuse_addr_reg21_fu_96 <= zext_ln28_fu_304_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg_fu_104 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((icmp_ln26_reg_693 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    reuse_addr_reg_fu_104 <= zext_ln28_fu_304_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg20_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg20_fu_100 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln26_reg_693_pp0_iter2_reg = ap_const_lv1_0))) then 
                    reuse_reg20_fu_100 <= reuse_select_fu_417_p3;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg_fu_108 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln26_reg_693_pp0_iter2_reg = ap_const_lv1_0))) then 
                    reuse_reg_fu_108 <= p_s_reg_697;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                Gx_Value_reg_777 <= Gx_Value_fu_522_p2;
                Gy_Value_2_reg_783 <= Gy_Value_2_fu_531_p2;
                Line_Buffer_data_addr_reg_735 <= zext_ln28_fu_304_p1(11 - 1 downto 0);
                add_ln58_reg_772 <= add_ln58_fu_475_p2;
                addr_cmp24_reg_741 <= addr_cmp24_fu_342_p2;
                addr_cmp_reg_751 <= addr_cmp_fu_351_p2;
                p_0_reg_730 <= Input_r_TDEST;
                p_0_reg_730_pp0_iter3_reg <= p_0_reg_730;
                p_0_reg_730_pp0_iter4_reg <= p_0_reg_730_pp0_iter3_reg;
                p_1_reg_705 <= Input_r_TKEEP;
                p_1_reg_705_pp0_iter3_reg <= p_1_reg_705;
                p_1_reg_705_pp0_iter4_reg <= p_1_reg_705_pp0_iter3_reg;
                p_2_reg_710 <= Input_r_TSTRB;
                p_2_reg_710_pp0_iter3_reg <= p_2_reg_710;
                p_2_reg_710_pp0_iter4_reg <= p_2_reg_710_pp0_iter3_reg;
                p_3_reg_715 <= Input_r_TUSER;
                p_3_reg_715_pp0_iter3_reg <= p_3_reg_715;
                p_3_reg_715_pp0_iter4_reg <= p_3_reg_715_pp0_iter3_reg;
                p_4_reg_720 <= Input_r_TLAST;
                p_4_reg_720_pp0_iter3_reg <= p_4_reg_720;
                p_4_reg_720_pp0_iter4_reg <= p_4_reg_720_pp0_iter3_reg;
                p_5_reg_725 <= Input_r_TID;
                p_5_reg_725_pp0_iter3_reg <= p_5_reg_725;
                p_5_reg_725_pp0_iter4_reg <= p_5_reg_725_pp0_iter3_reg;
                p_s_reg_697 <= Input_r_TDATA;
                p_s_reg_697_pp0_iter3_reg <= p_s_reg_697;
                reuse_select25_reg_756 <= reuse_select25_fu_407_p3;
                sub_ln57_reg_767 <= sub_ln57_fu_470_p2;
                sub_ln62_reg_789 <= sub_ln62_fu_536_p2;
                sub_ln63_reg_794 <= sub_ln63_fu_542_p2;
                tmp5_reg_762 <= tmp5_fu_438_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln26_reg_693_pp0_iter2_reg = ap_const_lv1_0))) then
                Gy_Value_fu_112 <= p_0_0_0_0158434_fu_132;
                p_0_0_0_0158434_fu_132 <= reuse_select25_fu_407_p3;
                p_0_0_0_0158_1441_fu_116 <= p_0_0_0_0158_1448_fu_136;
                p_0_0_0_0158_1448_fu_136 <= trunc_ln43_fu_425_p1;
                p_0_0_0_0158_2455_fu_120 <= p_0_0_0_0158_2462_fu_140;
                p_0_0_0_0158_2462_fu_140 <= p_s_reg_697;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln26_reg_693 <= icmp_ln26_fu_268_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                icmp_ln26_reg_693_pp0_iter2_reg <= icmp_ln26_reg_693;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Gx_Value_Abs_fu_555_p3 <= 
        sub_ln62_reg_789 when (tmp_fu_548_p3(0) = '1') else 
        Gx_Value_reg_777;
    Gx_Value_fu_522_p2 <= std_logic_vector(unsigned(add_ln57_1_fu_517_p2) + unsigned(reuse_select25_reg_756));
    Gy_Value_2_fu_531_p2 <= std_logic_vector(unsigned(reuse_select25_reg_756) + unsigned(Gy_Value_3_fu_527_p2));
    Gy_Value_3_fu_527_p2 <= std_logic_vector(unsigned(add_ln58_reg_772) - unsigned(p_s_reg_697_pp0_iter3_reg));
    Gy_Value_Abs_fu_568_p3 <= 
        sub_ln63_reg_794 when (tmp_1_fu_561_p3(0) = '1') else 
        Gy_Value_2_reg_783;

    Input_r_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, Input_r_TVALID, icmp_ln26_reg_693, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln26_reg_693 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Input_r_TDATA_blk_n <= Input_r_TVALID;
        else 
            Input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Input_r_TREADY_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln26_reg_693, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln26_reg_693 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Input_r_TREADY <= ap_const_logic_1;
        else 
            Input_r_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    Line_Buffer_data_1_address0 <= zext_ln28_fu_304_p1(11 - 1 downto 0);

    Line_Buffer_data_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln26_reg_693, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln26_reg_693 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Line_Buffer_data_1_ce0_local <= ap_const_logic_1;
        else 
            Line_Buffer_data_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    Line_Buffer_data_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln26_reg_693, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln26_reg_693 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Line_Buffer_data_1_we0_local <= ap_const_logic_1;
        else 
            Line_Buffer_data_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    Line_Buffer_data_address1 <= zext_ln28_fu_304_p1(11 - 1 downto 0);

    Line_Buffer_data_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            Line_Buffer_data_ce0_local <= ap_const_logic_1;
        else 
            Line_Buffer_data_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    Line_Buffer_data_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            Line_Buffer_data_ce1_local <= ap_const_logic_1;
        else 
            Line_Buffer_data_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    Line_Buffer_data_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1, icmp_ln26_reg_693_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln26_reg_693_pp0_iter2_reg = ap_const_lv1_0))) then 
            Line_Buffer_data_we0_local <= ap_const_logic_1;
        else 
            Line_Buffer_data_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    Magnitude_fu_574_p2 <= std_logic_vector(unsigned(Gx_Value_Abs_fu_555_p3) + unsigned(Gy_Value_Abs_fu_568_p3));
    Output_r_TDATA <= 
        ap_const_lv32_FF when (icmp_ln68_fu_590_p2(0) = '1') else 
        Magnitude_fu_574_p2;

    Output_r_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter5, Output_r_TREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            Output_r_TDATA_blk_n <= Output_r_TREADY;
        else 
            Output_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    Output_r_TDEST <= p_0_reg_730_pp0_iter4_reg;
    Output_r_TID <= p_5_reg_725_pp0_iter4_reg;
    Output_r_TKEEP <= p_1_reg_705_pp0_iter4_reg;
    Output_r_TLAST <= p_4_reg_720_pp0_iter4_reg;
    Output_r_TSTRB <= p_2_reg_710_pp0_iter4_reg;
    Output_r_TUSER <= p_3_reg_715_pp0_iter4_reg;

    Output_r_TVALID_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            Output_r_TVALID <= ap_const_logic_1;
        else 
            Output_r_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    add_ln26_fu_273_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_128) + unsigned(ap_const_lv62_1));
    add_ln28_fu_367_p2 <= std_logic_vector(unsigned(select_ln26_fu_296_p3) + unsigned(ap_const_lv11_1));
    add_ln57_1_fu_517_p2 <= std_logic_vector(unsigned(sub_ln57_reg_767) + unsigned(tmp1_fu_510_p3));
    add_ln57_fu_464_p2 <= std_logic_vector(unsigned(Gy_Value_fu_112) + unsigned(p_0_0_0_0158_2455_fu_120));
    add_ln58_fu_475_p2 <= std_logic_vector(unsigned(sub_ln58_fu_444_p2) + unsigned(tmp4_fu_456_p3));
    addr_cmp24_fu_342_p2 <= "1" when (reuse_addr_reg21_fu_96 = zext_ln28_fu_304_p1) else "0";
    addr_cmp_fu_351_p2 <= "1" when (reuse_addr_reg_fu_104 = zext_ln28_fu_304_p1) else "0";
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, Output_r_TREADY, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_0 = Output_r_TREADY)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, Output_r_TREADY, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_0 = Output_r_TREADY)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, Output_r_TREADY, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_0 = Output_r_TREADY)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, Output_r_TREADY, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_0 = Output_r_TREADY)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_grp1_assign_proc : process(Input_r_TVALID, icmp_ln26_reg_693)
    begin
                ap_block_state3_pp0_stage0_iter2_grp1 <= ((icmp_ln26_reg_693 = ap_const_lv1_0) and (ap_const_logic_0 = Input_r_TVALID));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln26_fu_268_p2)
    begin
        if (((icmp_ln26_fu_268_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, icmp_ln26_reg_693_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln26_reg_693_pp0_iter2_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln26_fu_268_p2 <= "1" when (indvar_flatten_fu_128 = bound) else "0";
    icmp_ln28_fu_291_p2 <= "1" when (signed(zext_ln28_1_fu_287_p1) < signed(Cols)) else "0";
    icmp_ln68_fu_590_p2 <= "1" when (signed(tmp_2_fu_580_p4) > signed(ap_const_lv24_0)) else "0";
    reuse_select25_fu_407_p3 <= 
        reuse_reg20_fu_100 when (addr_cmp24_reg_741(0) = '1') else 
        Line_Buffer_data_q1;
    reuse_select_fu_417_p3 <= 
        reuse_reg_fu_108 when (addr_cmp_reg_751(0) = '1') else 
        Line_Buffer_data_1_q0;
    select_ln26_fu_296_p3 <= 
        J_fu_124 when (icmp_ln28_fu_291_p2(0) = '1') else 
        ap_const_lv11_0;
    sub_ln57_fu_470_p2 <= std_logic_vector(unsigned(p_s_reg_697) - unsigned(add_ln57_fu_464_p2));
    sub_ln58_fu_444_p2 <= std_logic_vector(unsigned(Gy_Value_fu_112) - unsigned(p_0_0_0_0158_2455_fu_120));
    sub_ln62_fu_536_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(Gx_Value_fu_522_p2));
    sub_ln63_fu_542_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(Gy_Value_2_fu_531_p2));
    tmp1_fu_510_p3 <= (tmp5_reg_762 & ap_const_lv1_0);
    tmp31_fu_450_p2 <= std_logic_vector(unsigned(trunc_ln28_1_fu_400_p1) - unsigned(trunc_ln28_fu_396_p1));
    tmp4_fu_456_p3 <= (tmp31_fu_450_p2 & ap_const_lv1_0);
    tmp5_fu_438_p2 <= std_logic_vector(unsigned(trunc_ln43_fu_425_p1) - unsigned(p_0_0_0_0158_1441_fu_116));
    tmp_1_fu_561_p3 <= Gy_Value_2_reg_783(31 downto 31);
    tmp_2_fu_580_p4 <= Magnitude_fu_574_p2(31 downto 8);
    tmp_fu_548_p3 <= Gx_Value_reg_777(31 downto 31);
    trunc_ln28_1_fu_400_p1 <= p_0_0_0_0158434_fu_132(31 - 1 downto 0);
    trunc_ln28_fu_396_p1 <= p_0_0_0_0158_2462_fu_140(31 - 1 downto 0);
    trunc_ln43_fu_425_p1 <= reuse_select_fu_417_p3(31 - 1 downto 0);
    zext_ln28_1_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(J_fu_124),32));
    zext_ln28_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln26_fu_296_p3),64));
end behav;
