[hls]
relative_roots=C:/F.A.L.C.O.N/Vitis_WS/Sobel_Filter_IP
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=sobel_filter/anonymous 
syn.directive.pipeline=sobel_filter/anonymous 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=sobel_filter/VITIS_LOOP_28_2  


