-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2026.1 (win64) Build 6511674 Tue Jun 16 11:02:23 MDT 2026
-- Date        : Mon Sep  7 22:39:14 2026
-- Host        : DESKTOP-55UAODO running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ Design_1_vector_mult_0_0_stub.vhdl
-- Design      : Design_1_vector_mult_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_gmem_A_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_A_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_A_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_A_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_A_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_A_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_A_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_A_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_A_ARREADY : in STD_LOGIC;
    m_axi_gmem_A_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_A_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_A_ARVALID : out STD_LOGIC;
    m_axi_gmem_A_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_A_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_A_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_A_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_A_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_A_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_A_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_A_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_A_AWREADY : in STD_LOGIC;
    m_axi_gmem_A_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_A_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_A_AWVALID : out STD_LOGIC;
    m_axi_gmem_A_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_A_BREADY : out STD_LOGIC;
    m_axi_gmem_A_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_A_BVALID : in STD_LOGIC;
    m_axi_gmem_A_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_A_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_A_RLAST : in STD_LOGIC;
    m_axi_gmem_A_RREADY : out STD_LOGIC;
    m_axi_gmem_A_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_A_RVALID : in STD_LOGIC;
    m_axi_gmem_A_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_A_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_A_WLAST : out STD_LOGIC;
    m_axi_gmem_A_WREADY : in STD_LOGIC;
    m_axi_gmem_A_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_A_WVALID : out STD_LOGIC;
    m_axi_gmem_B_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_B_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_B_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_B_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_B_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_B_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_B_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_B_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_B_ARREADY : in STD_LOGIC;
    m_axi_gmem_B_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_B_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_B_ARVALID : out STD_LOGIC;
    m_axi_gmem_B_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_B_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_B_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_B_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_B_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_B_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_B_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_B_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_B_AWREADY : in STD_LOGIC;
    m_axi_gmem_B_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_B_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_B_AWVALID : out STD_LOGIC;
    m_axi_gmem_B_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_B_BREADY : out STD_LOGIC;
    m_axi_gmem_B_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_B_BVALID : in STD_LOGIC;
    m_axi_gmem_B_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_B_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_B_RLAST : in STD_LOGIC;
    m_axi_gmem_B_RREADY : out STD_LOGIC;
    m_axi_gmem_B_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_B_RVALID : in STD_LOGIC;
    m_axi_gmem_B_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_B_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_B_WLAST : out STD_LOGIC;
    m_axi_gmem_B_WREADY : in STD_LOGIC;
    m_axi_gmem_B_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_B_WVALID : out STD_LOGIC;
    m_axi_gmem_C_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_C_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_C_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_C_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_C_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_C_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_C_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_C_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_C_ARREADY : in STD_LOGIC;
    m_axi_gmem_C_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_C_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_C_ARVALID : out STD_LOGIC;
    m_axi_gmem_C_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_C_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_C_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_C_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_C_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_C_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_C_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_C_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_C_AWREADY : in STD_LOGIC;
    m_axi_gmem_C_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_C_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_C_AWVALID : out STD_LOGIC;
    m_axi_gmem_C_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_C_BREADY : out STD_LOGIC;
    m_axi_gmem_C_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_C_BVALID : in STD_LOGIC;
    m_axi_gmem_C_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_C_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_C_RLAST : in STD_LOGIC;
    m_axi_gmem_C_RREADY : out STD_LOGIC;
    m_axi_gmem_C_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_C_RVALID : in STD_LOGIC;
    m_axi_gmem_C_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_C_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_C_WLAST : out STD_LOGIC;
    m_axi_gmem_C_WREADY : in STD_LOGIC;
    m_axi_gmem_C_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_C_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "Design_1_vector_mult_0_0,vector_mult,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "Design_1_vector_mult_0_0,vector_mult,{x_ipProduct=Vivado 2026.1,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=vector_mult,x_ipVersion=1.0,x_ipCoreRevision=2114775966,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CONTROL_ADDR_WIDTH=6,C_S_AXI_CONTROL_DATA_WIDTH=32,C_M_AXI_GMEM_A_ID_WIDTH=1,C_M_AXI_GMEM_A_ADDR_WIDTH=64,C_M_AXI_GMEM_A_DATA_WIDTH=32,C_M_AXI_GMEM_A_AWUSER_WIDTH=1,C_M_AXI_GMEM_A_ARUSER_WIDTH=1,C_M_AXI_GMEM_A_WUSER_WIDTH=1,C_M_AXI_GMEM_A_RUSER_WIDTH=1,C_M_AXI_GMEM_A_BUSER_WIDTH=1,C_M_AXI_GMEM_A_USER_VALUE=0x00000000,C_M_AXI_GMEM_A_PROT_VALUE=000,C_M_AXI_GMEM_A_CACHE_VALUE=0011,C_M_AXI_GMEM_B_ID_WIDTH=1,C_M_AXI_GMEM_B_ADDR_WIDTH=64,C_M_AXI_GMEM_B_DATA_WIDTH=32,C_M_AXI_GMEM_B_AWUSER_WIDTH=1,C_M_AXI_GMEM_B_ARUSER_WIDTH=1,C_M_AXI_GMEM_B_WUSER_WIDTH=1,C_M_AXI_GMEM_B_RUSER_WIDTH=1,C_M_AXI_GMEM_B_BUSER_WIDTH=1,C_M_AXI_GMEM_B_USER_VALUE=0x00000000,C_M_AXI_GMEM_B_PROT_VALUE=000,C_M_AXI_GMEM_B_CACHE_VALUE=0011,C_M_AXI_GMEM_C_ID_WIDTH=1,C_M_AXI_GMEM_C_ADDR_WIDTH=64,C_M_AXI_GMEM_C_DATA_WIDTH=32,C_M_AXI_GMEM_C_AWUSER_WIDTH=1,C_M_AXI_GMEM_C_ARUSER_WIDTH=1,C_M_AXI_GMEM_C_WUSER_WIDTH=1,C_M_AXI_GMEM_C_RUSER_WIDTH=1,C_M_AXI_GMEM_C_BUSER_WIDTH=1,C_M_AXI_GMEM_C_USER_VALUE=0x00000000,C_M_AXI_GMEM_C_PROT_VALUE=000,C_M_AXI_GMEM_C_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[5:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[5:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_gmem_A_ARADDR[63:0],m_axi_gmem_A_ARBURST[1:0],m_axi_gmem_A_ARCACHE[3:0],m_axi_gmem_A_ARID[0:0],m_axi_gmem_A_ARLEN[7:0],m_axi_gmem_A_ARLOCK[1:0],m_axi_gmem_A_ARPROT[2:0],m_axi_gmem_A_ARQOS[3:0],m_axi_gmem_A_ARREADY,m_axi_gmem_A_ARREGION[3:0],m_axi_gmem_A_ARSIZE[2:0],m_axi_gmem_A_ARVALID,m_axi_gmem_A_AWADDR[63:0],m_axi_gmem_A_AWBURST[1:0],m_axi_gmem_A_AWCACHE[3:0],m_axi_gmem_A_AWID[0:0],m_axi_gmem_A_AWLEN[7:0],m_axi_gmem_A_AWLOCK[1:0],m_axi_gmem_A_AWPROT[2:0],m_axi_gmem_A_AWQOS[3:0],m_axi_gmem_A_AWREADY,m_axi_gmem_A_AWREGION[3:0],m_axi_gmem_A_AWSIZE[2:0],m_axi_gmem_A_AWVALID,m_axi_gmem_A_BID[0:0],m_axi_gmem_A_BREADY,m_axi_gmem_A_BRESP[1:0],m_axi_gmem_A_BVALID,m_axi_gmem_A_RDATA[31:0],m_axi_gmem_A_RID[0:0],m_axi_gmem_A_RLAST,m_axi_gmem_A_RREADY,m_axi_gmem_A_RRESP[1:0],m_axi_gmem_A_RVALID,m_axi_gmem_A_WDATA[31:0],m_axi_gmem_A_WID[0:0],m_axi_gmem_A_WLAST,m_axi_gmem_A_WREADY,m_axi_gmem_A_WSTRB[3:0],m_axi_gmem_A_WVALID,m_axi_gmem_B_ARADDR[63:0],m_axi_gmem_B_ARBURST[1:0],m_axi_gmem_B_ARCACHE[3:0],m_axi_gmem_B_ARID[0:0],m_axi_gmem_B_ARLEN[7:0],m_axi_gmem_B_ARLOCK[1:0],m_axi_gmem_B_ARPROT[2:0],m_axi_gmem_B_ARQOS[3:0],m_axi_gmem_B_ARREADY,m_axi_gmem_B_ARREGION[3:0],m_axi_gmem_B_ARSIZE[2:0],m_axi_gmem_B_ARVALID,m_axi_gmem_B_AWADDR[63:0],m_axi_gmem_B_AWBURST[1:0],m_axi_gmem_B_AWCACHE[3:0],m_axi_gmem_B_AWID[0:0],m_axi_gmem_B_AWLEN[7:0],m_axi_gmem_B_AWLOCK[1:0],m_axi_gmem_B_AWPROT[2:0],m_axi_gmem_B_AWQOS[3:0],m_axi_gmem_B_AWREADY,m_axi_gmem_B_AWREGION[3:0],m_axi_gmem_B_AWSIZE[2:0],m_axi_gmem_B_AWVALID,m_axi_gmem_B_BID[0:0],m_axi_gmem_B_BREADY,m_axi_gmem_B_BRESP[1:0],m_axi_gmem_B_BVALID,m_axi_gmem_B_RDATA[31:0],m_axi_gmem_B_RID[0:0],m_axi_gmem_B_RLAST,m_axi_gmem_B_RREADY,m_axi_gmem_B_RRESP[1:0],m_axi_gmem_B_RVALID,m_axi_gmem_B_WDATA[31:0],m_axi_gmem_B_WID[0:0],m_axi_gmem_B_WLAST,m_axi_gmem_B_WREADY,m_axi_gmem_B_WSTRB[3:0],m_axi_gmem_B_WVALID,m_axi_gmem_C_ARADDR[63:0],m_axi_gmem_C_ARBURST[1:0],m_axi_gmem_C_ARCACHE[3:0],m_axi_gmem_C_ARID[0:0],m_axi_gmem_C_ARLEN[7:0],m_axi_gmem_C_ARLOCK[1:0],m_axi_gmem_C_ARPROT[2:0],m_axi_gmem_C_ARQOS[3:0],m_axi_gmem_C_ARREADY,m_axi_gmem_C_ARREGION[3:0],m_axi_gmem_C_ARSIZE[2:0],m_axi_gmem_C_ARVALID,m_axi_gmem_C_AWADDR[63:0],m_axi_gmem_C_AWBURST[1:0],m_axi_gmem_C_AWCACHE[3:0],m_axi_gmem_C_AWID[0:0],m_axi_gmem_C_AWLEN[7:0],m_axi_gmem_C_AWLOCK[1:0],m_axi_gmem_C_AWPROT[2:0],m_axi_gmem_C_AWQOS[3:0],m_axi_gmem_C_AWREADY,m_axi_gmem_C_AWREGION[3:0],m_axi_gmem_C_AWSIZE[2:0],m_axi_gmem_C_AWVALID,m_axi_gmem_C_BID[0:0],m_axi_gmem_C_BREADY,m_axi_gmem_C_BRESP[1:0],m_axi_gmem_C_BVALID,m_axi_gmem_C_RDATA[31:0],m_axi_gmem_C_RID[0:0],m_axi_gmem_C_RLAST,m_axi_gmem_C_RREADY,m_axi_gmem_C_RRESP[1:0],m_axi_gmem_C_RVALID,m_axi_gmem_C_WDATA[31:0],m_axi_gmem_C_WID[0:0],m_axi_gmem_C_WLAST,m_axi_gmem_C_WREADY,m_axi_gmem_C_WSTRB[3:0],m_axi_gmem_C_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 50000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN Design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control:m_axi_gmem_A:m_axi_gmem_B:m_axi_gmem_C, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 50000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN Design_1_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_A_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_A_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_A, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 50000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN Design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_A_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_A WVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_B_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_B_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_B, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 50000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN Design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_B_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_B WVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_C_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_C_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_C, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 50000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN Design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_C_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_C WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "vector_mult,Vivado 2026.1";
begin
end;
