// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module Canny_Filter_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Suppression_to_Hysteresis_dout,
        Suppression_to_Hysteresis_empty_n,
        Suppression_to_Hysteresis_read,
        Suppression_to_Hysteresis_num_data_valid,
        Suppression_to_Hysteresis_fifo_cap,
        Output_Stream_TREADY,
        Cols_3,
        add_ln70,
        High_Threshold_1,
        Low_Threshold_1,
        add_ln70_1,
        Output_Stream_TDATA,
        Output_Stream_TVALID,
        Output_Stream_TKEEP,
        Output_Stream_TSTRB,
        Output_Stream_TUSER,
        Output_Stream_TLAST,
        Output_Stream_TID,
        Output_Stream_TDEST,
        bound
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] Suppression_to_Hysteresis_dout;
input   Suppression_to_Hysteresis_empty_n;
output   Suppression_to_Hysteresis_read;
input  [3:0] Suppression_to_Hysteresis_num_data_valid;
input  [3:0] Suppression_to_Hysteresis_fifo_cap;
input   Output_Stream_TREADY;
input  [31:0] Cols_3;
input  [31:0] add_ln70;
input  [31:0] High_Threshold_1;
input  [31:0] Low_Threshold_1;
input  [31:0] add_ln70_1;
output  [31:0] Output_Stream_TDATA;
output   Output_Stream_TVALID;
output  [3:0] Output_Stream_TKEEP;
output  [3:0] Output_Stream_TSTRB;
output  [2:0] Output_Stream_TUSER;
output  [0:0] Output_Stream_TLAST;
output  [4:0] Output_Stream_TID;
output  [5:0] Output_Stream_TDEST;
input  [61:0] bound;

reg ap_idle;
reg Suppression_to_Hysteresis_read;
reg Output_Stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln11_reg_767;
reg    ap_block_state3_pp0_stage0_iter2_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln11_fu_298_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    Suppression_to_Hysteresis_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    Output_Stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] icmp_ln11_reg_767_pp0_iter2_reg;
wire   [0:0] icmp_ln13_fu_321_p2;
reg   [0:0] icmp_ln13_reg_771;
wire   [30:0] select_ln11_fu_326_p3;
reg   [30:0] select_ln11_reg_776;
reg   [31:0] Pixel_In_reg_781;
reg   [10:0] Line_Buffer_addr_reg_788;
wire   [0:0] addr_cmp22_fu_347_p2;
reg   [0:0] addr_cmp22_reg_794;
wire   [0:0] addr_cmp_fu_356_p2;
reg   [0:0] addr_cmp_reg_804;
wire   [0:0] icmp_ln70_1_fu_372_p2;
reg   [0:0] icmp_ln70_1_reg_809;
wire   [0:0] icmp_ln38_fu_461_p2;
reg   [0:0] icmp_ln38_reg_814;
wire   [0:0] icmp_ln42_fu_466_p2;
reg   [0:0] icmp_ln42_reg_820;
wire   [0:0] Strong_fu_471_p2;
reg   [0:0] Strong_reg_825;
wire   [0:0] icmp_ln50_fu_476_p2;
reg   [0:0] icmp_ln50_reg_830;
wire   [0:0] icmp_ln50_1_fu_481_p2;
reg   [0:0] icmp_ln50_1_reg_835;
wire   [0:0] icmp_ln50_2_fu_486_p2;
reg   [0:0] icmp_ln50_2_reg_840;
wire   [0:0] icmp_ln50_3_fu_491_p2;
reg   [0:0] icmp_ln50_3_reg_845;
wire   [0:0] icmp_ln50_4_fu_496_p2;
reg   [0:0] icmp_ln50_4_reg_850;
wire   [0:0] icmp_ln50_5_fu_501_p2;
reg   [0:0] icmp_ln50_5_reg_855;
wire   [0:0] icmp_ln50_6_fu_506_p2;
reg   [0:0] icmp_ln50_6_reg_860;
wire   [0:0] icmp_ln69_fu_515_p2;
reg   [0:0] icmp_ln69_reg_865;
wire   [0:0] and_ln70_fu_521_p2;
reg   [0:0] and_ln70_reg_870;
reg    ap_condition_exit_pp0_iter3_stage0;
wire   [10:0] Line_Buffer_1_address0;
wire   [31:0] Line_Buffer_1_q0;
wire   [10:0] Line_Buffer_address1;
wire   [31:0] Line_Buffer_q1;
wire   [63:0] zext_ln13_fu_338_p1;
reg   [63:0] reuse_addr_reg19_fu_100;
wire    ap_loop_init;
reg   [31:0] reuse_reg18_fu_104;
wire   [31:0] Mid_Pixel_fu_444_p3;
reg   [63:0] reuse_addr_reg_fu_108;
reg   [31:0] reuse_reg_fu_112;
reg   [31:0] empty_fu_116;
reg   [31:0] empty_65_fu_120;
reg   [31:0] empty_66_fu_124;
reg   [30:0] J_fu_128;
wire   [30:0] add_ln13_fu_377_p2;
reg   [30:0] I_fu_132;
wire   [30:0] add_ln11_1_fu_416_p2;
reg   [61:0] indvar_flatten_fu_136;
wire   [61:0] add_ln11_fu_303_p2;
wire    ap_block_pp0_stage0;
reg   [31:0] empty_67_fu_140;
wire   [31:0] Top_Pixel_fu_434_p3;
reg   [31:0] Center_Value_fu_144;
reg   [31:0] empty_68_fu_148;
reg    ap_block_pp0_stage0_01001_grp1;
reg    Line_Buffer_ce1_local;
reg    Line_Buffer_we0_local;
reg    Line_Buffer_ce0_local;
reg    Line_Buffer_1_ce0_local;
reg    Line_Buffer_1_we0_local;
wire   [31:0] zext_ln13_2_fu_317_p1;
wire   [31:0] zext_ln70_fu_334_p1;
wire   [30:0] empty_69_fu_409_p3;
wire   [31:0] zext_ln11_fu_422_p1;
wire   [30:0] or_ln69_fu_510_p2;
wire   [0:0] icmp_ln70_fu_426_p2;
wire   [0:0] or_ln57_1_fu_564_p2;
wire   [0:0] or_ln57_fu_560_p2;
wire   [0:0] or_ln57_4_fu_578_p2;
wire   [0:0] or_ln57_3_fu_574_p2;
wire   [0:0] or_ln57_5_fu_582_p2;
wire   [0:0] or_ln57_2_fu_568_p2;
wire   [0:0] xor_ln38_fu_594_p2;
wire   [0:0] and_ln42_fu_599_p2;
wire   [0:0] Final_Value_1_fu_611_p4;
wire   [0:0] Final_Value_1_fu_611_p7;
wire   [1:0] Final_Value_1_fu_611_p8;
wire   [0:0] Final_Value_1_fu_611_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [1:0] Final_Value_1_fu_611_p1;
wire   [1:0] Final_Value_1_fu_611_p3;
wire   [1:0] Final_Value_1_fu_611_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 reuse_addr_reg19_fu_100 = 64'd0;
#0 reuse_reg18_fu_104 = 32'd0;
#0 reuse_addr_reg_fu_108 = 64'd0;
#0 reuse_reg_fu_112 = 32'd0;
#0 empty_fu_116 = 32'd0;
#0 empty_65_fu_120 = 32'd0;
#0 empty_66_fu_124 = 32'd0;
#0 J_fu_128 = 31'd0;
#0 I_fu_132 = 31'd0;
#0 indvar_flatten_fu_136 = 62'd0;
#0 empty_67_fu_140 = 32'd0;
#0 Center_Value_fu_144 = 32'd0;
#0 empty_68_fu_148 = 32'd0;
#0 ap_done_reg = 1'b0;
end

Canny_Filter_Gaussian_Filter_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_15_2_Line_Buffer_1_RAM_AUbkb #(
    .DataWidth( 32 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
Line_Buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Line_Buffer_1_address0),
    .ce0(Line_Buffer_1_ce0_local),
    .we0(Line_Buffer_1_we0_local),
    .d0(Suppression_to_Hysteresis_dout),
    .q0(Line_Buffer_1_q0)
);

Canny_Filter_Sobel_Filter_Pipeline_VITIS_LOOP_14_1_VITIS_LOOP_16_2_Line_Buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
Line_Buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Line_Buffer_addr_reg_788),
    .ce0(Line_Buffer_ce0_local),
    .we0(Line_Buffer_we0_local),
    .d0(Mid_Pixel_fu_444_p3),
    .address1(Line_Buffer_address1),
    .ce1(Line_Buffer_ce1_local),
    .q1(Line_Buffer_q1)
);

(* dissolve_hierarchy = "yes" *) Canny_Filter_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U64(
    .din0(1'd1),
    .din1(Final_Value_1_fu_611_p4),
    .din2(1'd0),
    .def(Final_Value_1_fu_611_p7),
    .sel(Final_Value_1_fu_611_p8),
    .dout(Final_Value_1_fu_611_p9)
);

Canny_Filter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            I_fu_132 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln11_reg_767_pp0_iter2_reg == 1'd0))) begin
            I_fu_132 <= add_ln11_1_fu_416_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            J_fu_128 <= 31'd0;
        end else if (((icmp_ln11_reg_767 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            J_fu_128 <= add_ln13_fu_377_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_136 <= 62'd0;
        end else if (((icmp_ln11_fu_298_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_136 <= add_ln11_fu_303_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg19_fu_100 <= 64'd18446744073709551615;
        end else if (((icmp_ln11_reg_767 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            reuse_addr_reg19_fu_100 <= zext_ln13_fu_338_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_addr_reg_fu_108 <= 64'd18446744073709551615;
        end else if (((icmp_ln11_reg_767 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            reuse_addr_reg_fu_108 <= zext_ln13_fu_338_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg18_fu_104 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln11_reg_767_pp0_iter2_reg == 1'd0))) begin
            reuse_reg18_fu_104 <= Mid_Pixel_fu_444_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            reuse_reg_fu_112 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln11_reg_767_pp0_iter2_reg == 1'd0))) begin
            reuse_reg_fu_112 <= Pixel_In_reg_781;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln11_reg_767_pp0_iter2_reg == 1'd0))) begin
        Center_Value_fu_144 <= Mid_Pixel_fu_444_p3;
        empty_65_fu_120 <= Center_Value_fu_144;
        empty_66_fu_124 <= empty_68_fu_148;
        empty_67_fu_140 <= Top_Pixel_fu_434_p3;
        empty_68_fu_148 <= Pixel_In_reg_781;
        empty_fu_116 <= empty_67_fu_140;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        Line_Buffer_addr_reg_788 <= zext_ln13_fu_338_p1;
        Pixel_In_reg_781 <= Suppression_to_Hysteresis_dout;
        Strong_reg_825 <= Strong_fu_471_p2;
        addr_cmp22_reg_794 <= addr_cmp22_fu_347_p2;
        addr_cmp_reg_804 <= addr_cmp_fu_356_p2;
        and_ln70_reg_870 <= and_ln70_fu_521_p2;
        icmp_ln13_reg_771 <= icmp_ln13_fu_321_p2;
        icmp_ln38_reg_814 <= icmp_ln38_fu_461_p2;
        icmp_ln42_reg_820 <= icmp_ln42_fu_466_p2;
        icmp_ln50_1_reg_835 <= icmp_ln50_1_fu_481_p2;
        icmp_ln50_2_reg_840 <= icmp_ln50_2_fu_486_p2;
        icmp_ln50_3_reg_845 <= icmp_ln50_3_fu_491_p2;
        icmp_ln50_4_reg_850 <= icmp_ln50_4_fu_496_p2;
        icmp_ln50_5_reg_855 <= icmp_ln50_5_fu_501_p2;
        icmp_ln50_6_reg_860 <= icmp_ln50_6_fu_506_p2;
        icmp_ln50_reg_830 <= icmp_ln50_fu_476_p2;
        icmp_ln69_reg_865 <= icmp_ln69_fu_515_p2;
        icmp_ln70_1_reg_809 <= icmp_ln70_1_fu_372_p2;
        select_ln11_reg_776 <= select_ln11_fu_326_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln11_reg_767 <= icmp_ln11_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln11_reg_767_pp0_iter2_reg <= icmp_ln11_reg_767;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln11_reg_767 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Line_Buffer_1_ce0_local = 1'b1;
    end else begin
        Line_Buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln11_reg_767 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Line_Buffer_1_we0_local = 1'b1;
    end else begin
        Line_Buffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        Line_Buffer_ce0_local = 1'b1;
    end else begin
        Line_Buffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Line_Buffer_ce1_local = 1'b1;
    end else begin
        Line_Buffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln11_reg_767_pp0_iter2_reg == 1'd0))) begin
        Line_Buffer_we0_local = 1'b1;
    end else begin
        Line_Buffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        Output_Stream_TDATA_blk_n = Output_Stream_TREADY;
    end else begin
        Output_Stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        Output_Stream_TVALID = 1'b1;
    end else begin
        Output_Stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln11_reg_767 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Suppression_to_Hysteresis_blk_n = Suppression_to_Hysteresis_empty_n;
    end else begin
        Suppression_to_Hysteresis_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln11_reg_767 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Suppression_to_Hysteresis_read = 1'b1;
    end else begin
        Suppression_to_Hysteresis_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln11_fu_298_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln11_reg_767_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Final_Value_1_fu_611_p4 = (or_ln57_5_fu_582_p2 | or_ln57_2_fu_568_p2);

assign Final_Value_1_fu_611_p7 = 'bx;

assign Final_Value_1_fu_611_p8 = {{icmp_ln38_reg_814}, {and_ln42_fu_599_p2}};

assign Line_Buffer_1_address0 = zext_ln13_fu_338_p1;

assign Line_Buffer_address1 = zext_ln13_fu_338_p1;

assign Mid_Pixel_fu_444_p3 = ((addr_cmp_reg_804[0:0] == 1'b1) ? reuse_reg_fu_112 : Line_Buffer_1_q0);

assign Output_Stream_TDATA = ((Final_Value_1_fu_611_p9[0:0] == 1'b1) ? 32'd255 : 32'd0);

assign Output_Stream_TDEST = 6'd0;

assign Output_Stream_TID = 5'd0;

assign Output_Stream_TKEEP = 4'd15;

assign Output_Stream_TLAST = and_ln70_reg_870;

assign Output_Stream_TSTRB = 4'd15;

assign Output_Stream_TUSER = icmp_ln69_reg_865;

assign Strong_fu_471_p2 = (($signed(empty_fu_116) > $signed(High_Threshold_1)) ? 1'b1 : 1'b0);

assign Top_Pixel_fu_434_p3 = ((addr_cmp22_reg_794[0:0] == 1'b1) ? reuse_reg18_fu_104 : Line_Buffer_q1);

assign add_ln11_1_fu_416_p2 = (I_fu_132 + empty_69_fu_409_p3);

assign add_ln11_fu_303_p2 = (indvar_flatten_fu_136 + 62'd1);

assign add_ln13_fu_377_p2 = (select_ln11_fu_326_p3 + 31'd1);

assign addr_cmp22_fu_347_p2 = ((reuse_addr_reg19_fu_100 == zext_ln13_fu_338_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_356_p2 = ((reuse_addr_reg_fu_108 == zext_ln13_fu_338_p1) ? 1'b1 : 1'b0);

assign and_ln42_fu_599_p2 = (xor_ln38_fu_594_p2 & icmp_ln42_reg_820);

assign and_ln70_fu_521_p2 = (icmp_ln70_fu_426_p2 & icmp_ln70_1_reg_809);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == Output_Stream_TREADY)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == Output_Stream_TREADY)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == Output_Stream_TREADY)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == Output_Stream_TREADY)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2_grp1 = ((icmp_ln11_reg_767 == 1'd0) & (1'b0 == Suppression_to_Hysteresis_empty_n));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign empty_69_fu_409_p3 = ((icmp_ln13_reg_771[0:0] == 1'b1) ? 31'd0 : 31'd1);

assign icmp_ln11_fu_298_p2 = ((indvar_flatten_fu_136 == bound) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_321_p2 = (($signed(zext_ln13_2_fu_317_p1) < $signed(Cols_3)) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_461_p2 = (($signed(Center_Value_fu_144) > $signed(High_Threshold_1)) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_466_p2 = (($signed(Center_Value_fu_144) > $signed(Low_Threshold_1)) ? 1'b1 : 1'b0);

assign icmp_ln50_1_fu_481_p2 = (($signed(Top_Pixel_fu_434_p3) > $signed(High_Threshold_1)) ? 1'b1 : 1'b0);

assign icmp_ln50_2_fu_486_p2 = (($signed(empty_65_fu_120) > $signed(High_Threshold_1)) ? 1'b1 : 1'b0);

assign icmp_ln50_3_fu_491_p2 = (($signed(Mid_Pixel_fu_444_p3) > $signed(High_Threshold_1)) ? 1'b1 : 1'b0);

assign icmp_ln50_4_fu_496_p2 = (($signed(empty_66_fu_124) > $signed(High_Threshold_1)) ? 1'b1 : 1'b0);

assign icmp_ln50_5_fu_501_p2 = (($signed(empty_68_fu_148) > $signed(High_Threshold_1)) ? 1'b1 : 1'b0);

assign icmp_ln50_6_fu_506_p2 = (($signed(Pixel_In_reg_781) > $signed(High_Threshold_1)) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_476_p2 = (($signed(empty_67_fu_140) > $signed(High_Threshold_1)) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_515_p2 = ((or_ln69_fu_510_p2 == 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln70_1_fu_372_p2 = ((zext_ln70_fu_334_p1 == add_ln70_1) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_426_p2 = ((zext_ln11_fu_422_p1 == add_ln70) ? 1'b1 : 1'b0);

assign or_ln57_1_fu_564_p2 = (icmp_ln50_2_reg_840 | icmp_ln50_1_reg_835);

assign or_ln57_2_fu_568_p2 = (or_ln57_fu_560_p2 | or_ln57_1_fu_564_p2);

assign or_ln57_3_fu_574_p2 = (icmp_ln50_4_reg_850 | icmp_ln50_3_reg_845);

assign or_ln57_4_fu_578_p2 = (icmp_ln50_6_reg_860 | icmp_ln50_5_reg_855);

assign or_ln57_5_fu_582_p2 = (or_ln57_4_fu_578_p2 | or_ln57_3_fu_574_p2);

assign or_ln57_fu_560_p2 = (icmp_ln50_reg_830 | Strong_reg_825);

assign or_ln69_fu_510_p2 = (select_ln11_reg_776 | add_ln11_1_fu_416_p2);

assign select_ln11_fu_326_p3 = ((icmp_ln13_fu_321_p2[0:0] == 1'b1) ? J_fu_128 : 31'd0);

assign xor_ln38_fu_594_p2 = (icmp_ln38_reg_814 ^ 1'd1);

assign zext_ln11_fu_422_p1 = add_ln11_1_fu_416_p2;

assign zext_ln13_2_fu_317_p1 = J_fu_128;

assign zext_ln13_fu_338_p1 = select_ln11_fu_326_p3;

assign zext_ln70_fu_334_p1 = select_ln11_fu_326_p3;

endmodule //Canny_Filter_Hysteresis_Filter_Pipeline_VITIS_LOOP_11_1_VITIS_LOOP_13_2
